### ISSUE TITLE
L2_NORMALIZATION op support for FaceNet model

### ISSUE THREAD

**Issue by cuiyanx** [intel/webml-polyfill#1001]
FaceNet model has L2_NORMALIZATION op as the last node in the graph.

![Screenshot from 2019-09-29 14-31-08](https://user-images.githubusercontent.com/22387607/65827732-e5011980-e2c5-11e9-9119-427e812a923a.png)

FaceNet model need ops table:

![Screenshot from 2019-09-29 15-01-07](https://user-images.githubusercontent.com/22387607/65828138-23003c80-e2ca-11e9-969f-703af16ec4c8.png)

As a L2_NORMALIZATION op, NNAPI has **ANEURALNETWORKS_L2_NORMALIZATION** op and ONNX has **LpNormalization** op.

<table>
    <tr>
        <th>Type</th>
        <th>Detail</th>
        <th>NNAPI</th>
		<th>ONNX</th>
    </tr>
    <tr>
        <td rowspan="5">L2_<br>NORMALIZATION</td>
		<td>Op</td>
        <td><a href="https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0abf295dee59560ff29d435226ec4c24bd">ANEURALNETWORKS_L2<br>_NORMALIZATION</a></td>
		<td><a href="https://github.com/onnx/onnx/blob/master/docs/Operators.md#LpNormalization">    LpNormalization    </a></td>
    </tr>
	<tr>
        <td>Input</td>
        <td><p>input[0]: <br>Supported tensor rank: 4, with "NHWC" data layout (i.e., Num_samples, Height, Width, and Channels). <br>A 4-D tensor, of shape [batches, height, width, depth].</p></td>
		<td><p>input: Input matrix</p></td>
    </tr>
	<tr>
        <td></td>
        <td></td>
		<td><p>Attributes["axis"] : int (default is -1)<br>The axis on which to apply normalization, -1 mean last axis.<br><br>Attributes["p"] : int (default is 2)<br>The order of the normalization, only 1 or 2 are supported.</p></td>
    </tr>
	<tr>
        <td>Output</td>
        <td><p>output[0]: <br>The output 4-D tensor, of shape [batches, out_height, out_width, depth].</p></td>
		<td><p>output: Matrix after normalization </p></td>
    </tr>
</table>​

**Comment by ibelem** [comment]
@cuiyanx @BruceDai @miaobin If i remembered correctly, we need to follow templates below to report these issues. @Christywl 

> Issue template
> o	Ops to be Proposed
> o	Use Case
> o	Native Mapping and Compatibility
> o	Polyfill Support
>   o	WASM
>   o	WebGL

**Comment by cuiyanx** [comment]
Detail | NNAPI | ONNX | clDNN | MKLDNN | DML | MPS | BNNS
-- | -- | -- | -- | -- | -- | -- | --
Op | [ANEURALNETWORKS_L2_NORMALIZATION](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0abf295dee59560ff29d435226ec4c24bd) | [LpNormalization](https://github.com/onnx/onnx/blob/master/docs/Operators.md#LpNormalization) |   |   |   |   |  
Input | input[0]: <br>Supported tensor rank: 4, with "NHWC" data layout (i.e., Num_samples, Height, Width, and Channels). <br>A 4-D tensor, of shape [batches, height, width, depth]. | input: Input matrix. |   |   |   |   |  
 |  |  | Attributes["axis"] : int (default is -1)<br>The axis on which to apply normalization, -1 mean last axis. |   |   |   |   |  
  |   |  | Attributes["p"] : int (default is 2)<br>The order of the normalization, only 1 or 2 are supported. |   |   |   |   |  
Output | output[0]: <br>The output 4-D tensor, of shape [batches, out_height, out_width, depth]. | output: Matrix after normalization. |   |   |   |   |

**Comment by cuiyanx** [comment]
@fujunwei @lisa0314 Please help fill in above table, thanks!

**Comment by lisa0314** [comment]
@cuiyanx BNNS has been updated. Thanks!

**Comment by fujunwei** [comment]
There is no existing operation to support L2 in MPS normal, maybe Metal Shading language is a optional.

**Comment by cuiyanx** [comment]
PR #984 and #983 has been merged, so closed.
