### ISSUE TITLE
PReLU op support for Face-Reidentification and ESRGAN

### ISSUE THREAD

**Issue by cuiyanx** [intel/webml-polyfill#1002]
Face-Reidentification model has PReLU op in the graph.

PReLU op:

![Screenshot from 2019-09-29 15-04-41](https://user-images.githubusercontent.com/22387607/65828184-b9346280-e2ca-11e9-8647-3b7ff8370a0a.png)

Face-Reidentification model need ops table:

![Screenshot from 2019-09-29 15-04-24](https://user-images.githubusercontent.com/22387607/65828213-ff89c180-e2ca-11e9-867b-842dbe25741a.png)

As a PReLU op, NNAPI has **ANEURALNETWORKS_PRELU** op, and ONNX has **PRelu** op.

<table>
    <tr>
        <th>Type</th>
        <th>Detail</th>
        <th>NNAPI</th>
	<th>ONNX</th>
    </tr>
    <tr>
        <td rowspan="4">PReLU</td>
	<td>Op</td>
        <td><a href="https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a89be86ff36e83254e9b3d0954e7e0729">ANEURALNETWORKS_PRELU</a></td>
	<td><a href="https://github.com/onnx/onnx/blob/master/docs/Operators.md#PRelu">    PRelu</a></td>
    </tr>
    <tr>
        <td>Input</td>
        <td><p>input[0]: <br>Supported tensor rank: from 1. <br>A tensor, specifying the input.</p></td>
	<td><p>inputs[“X”]: An input tensor.</p></td>
    </tr>
    <tr>
        <td>Slope</td>
        <td><p>input[1]: <br>A tensor of the same OperandCode, and compatible dimensions as input0, specifying the alpha.</p></td>
	<td><p>inputs["slope "]:<br>Slope tensor. The shape of slope can be smaller then first input X; if so, its shape must be unidirectional broadcastable to X.</p></td>
    </tr>
	<tr>
        <td>Output</td>
        <td><p>output[0]: <br>A tensor of the same OperandCode as input0. For a ANEURALNETWORKS_TENSOR_QUANT8_ASYMM tensor, the scale and zeroPoint can be diffent from the input0 scale and zeroPoint.</p></td>
		<td><p>outputs["Y "]:<br>Output tensor (same size as inputs[“X”]).</p></td>
    </tr>
</table>​

**Comment by ibelem** [comment]
@cuiyanx @BruceDai @miaobin If i remembered correctly, we need to follow templates below to report these issues. @Christywl 

> Issue template
> o	Ops to be Proposed
> o	Use Case
> o	Native Mapping and Compatibility
> o	Polyfill Support
>   o	WASM
>   o	WebGL

**Comment by cuiyanx** [comment]
Detail | NNAPI | ONNX | clDNN | MKLDNN | DML | MPS | BNNS
-- | -- | -- | -- | -- | -- | -- | --
Op | [ANEURALNETWORKS_PRELU](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a89be86ff36e83254e9b3d0954e7e0729) | [PRelu](https://github.com/onnx/onnx/blob/master/docs/Operators.md#PRelu) |   |   |   |   |  
Input | input[0]: <br>Supported tensor rank: from 1. <br>A tensor, specifying the input. | inputs[“X”]: An input tensor. |   |   |   |   |  
Slope | input[1]: <br>A tensor of the same OperandCode, and compatible dimensions as input0, specifying the alpha. | inputs["slope "]:<br>Slope tensor. The shape of slope can be smaller then first input X; if so, its shape must be unidirectional broadcastable to X. |   |   |   |   |  
Output | output[0]: <br>A tensor of the same OperandCode as input0. For a ANEURALNETWORKS_TENSOR_QUANT8_ASYMM tensor, the scale and zeroPoint can be diffent from the input0 scale and zeroPoint. | outputs["Y "]:<br>Output tensor (same size as inputs[“X”]). |   |   |   |   |

**Comment by cuiyanx** [comment]
@fujunwei @lisa0314 Please help fill in above table, thanks!

**Comment by ibelem** [comment]
The PReLU is also required in ESRGAN for super resolution use case #697

**Comment by cuiyanx** [comment]
This op has been supported and wait PR #983 merged.
