### ISSUE TITLE
Update Tensorflow version from 1.13 to 1.15 for PReLU and LOGISTIC ops

### ISSUE THREAD

**Issue by cuiyanx** [intel/webml-polyfill#1003]
There is old [Tensorflow](https://github.com/tensorflow/tensorflow/tree/r1.13) version as 1.13 in WebML-polyfill and this version does not support most new ops.
Propose to update Tensorflow version from 1.13 to 1.15. That version has supported some new ops like **PReLU** and **LOGISTIC**.

**Comment by ibelem** [comment]
#1032 #1025

**Comment by ibelem** [comment]
@akineeic Please help to investigate the WASM backend upgrade.
