### ISSUE TITLE
Ops support for DeepSpeech model

### ISSUE THREAD

**Issue by miaobin** [intel/webml-polyfill#1005]
DeepSpeech model has Minimum, StridedSlice, Split and Logistic ops in the graph:

Minimum:
![minimum](https://user-images.githubusercontent.com/17840011/65829763-4da6c100-e2db-11e9-9fa1-65493369850c.PNG)

StridedSlice, Split and Logistic:
![stridedslice_split](https://user-images.githubusercontent.com/17840011/65829766-53040b80-e2db-11e9-8a2f-4484b3419e41.PNG)

Now, NNAPI has all of the ops, but ONNX only has Logistic(Sigmoid) and Split.

op | ANEURALNETWORKS_MINIMUM |  
-- | -- | --
inputs | input[0]:     A tensor. |  
  | input[1]:        A tensor of the same OperandCode and compatible dimensions with input0. For   a ANEURALNETWORKS_TENSOR_QUANT8_ASYMM tensor, the scales and zeroPoint can be   different from input0 scale and zeroPoint. |  
outputs | output[0]:         A tensor of the same OperandCode as   input0. For a ANEURALNETWORKS_TENSOR_QUANT8_ASYMM tensor, the scale and   zeroPoint can be different from inputs' scale and zeroPoint. |  
op | ANEURALNETWORKS_LOGISTIC | Sigmoid
describe | Computes   sigmoid activation on the input tensor element-wise.     output = 1 / (1 + exp(-input)) | Sigmoid   takes one input data (Tensor) and produces one output data (Tensor) where the   sigmoid function,      y = 1 / (1 + exp(-x)), is applied to the tensor elementwise.
inputs | input[0]:     A tensor, specifying the input. Since API level 29, this tensor may be   zero-sized. | Input   tensor     T : tensor(float16), tensor(float), tensor(double)
outputs | output[0]:        The output tensor of same shape as input0. For   ANEURALNETWORKS_TENSOR_QUANT8_ASYMM, the scale must be 1.f / 256 and the   zeroPoint must be 0. | Output   tensor     T : tensor(float16), tensor(float), tensor(double)
op | ANEURALNETWORKS_STRIDED_SLICE |  
inputs | input[0]:     An n-D tensor, specifying the tensor to be sliced. |  
begin | input[1]:        begin, a 1-D tensor of ANEURALNETWORKS_TENSOR_INT32. The starts of the   dimensions of the input tensor to be sliced. The length must be of   rank(input0). |  
end | input[2]:        end, a 1-D tensor of ANEURALNETWORKS_TENSOR_INT32. The ends of the   dimensions of the input tensor to be sliced. The length must be of   rank(input0). |  
strides | input[3]:        strides, a 1-D tensor of ANEURALNETWORKS_TENSOR_INT32. The strides of the   dimensions of the input tensor to be sliced. The length must be of   rank(input0). The entries must be non-zero. |  
begin_mask | input[4]:        begin_mask, an ANEURALNETWORKS_INT32 scalar. If the ith bit of begin_mask   is set, begin[i] is ignored and the fullest possible range in that dimension   is used instead. |  
end_mask | input[5]:        end_mask, an ANEURALNETWORKS_INT32 scalar. If the ith bit of end_mask is   set, end[i] is ignored and the fullest possible range in that dimension is   used instead. |  
shrink_axis_mask | input[6]:        shrink_axis_mask, an ANEURALNETWORKS_INT32 scalar. If the ith bit of   shrink_axis_mask is set, the ith dimension specification shrinks the   dimensionality by 1, taking on the value at index begin[i]. In this case, the   ith specification must define a slice of size 1, e.g. begin[i] = x, end[i] =   x + 1. |  
outputs | output[0]:     A tensor of the same OperandCode as input0 and rank (n - k), where k is the   number of bits set in shrink_axis_mask. For a   ANEURALNETWORKS_TENSOR_QUANT8_ASYMM tensor, the scale and zeroPoint must be   the same as input0. |  
op | ANEURALNETWORKS_SPLIT | Split
inputs | input[0]:     An n-D tensor to split. | Inputs.T:     The tensor to split
  | input[1]:     An ANEURALNETWORKS_INT32 scalar specifying the axis along which to split. | Attributes.axis   : int (default is 0)     Which axis to split on. A negative value means counting dimensions from the   back. Accepted range is [-rank, rank-1] where r = rank(input).
  | input[2]:        An ANEURALNETWORKS_INT32 scalar indicating the number of splits along given   axis. Must evenly divide axis size. | Attributes.split   : list of ints     length of each output
outputs | 0   ~ (num_splits - 1): Resulting subtensors. For a   ANEURALNETWORKS_TENSOR_QUANT8_ASYMM tensor, the scale and zeroPoint must be   the same as input0. | One   or more outputs forming list of tensors after splitting

**Comment by ibelem** [comment]
@miaobin @BruceDai @cuiyanx Please create issues one by one for these ops rather than put them together. Team needs to decide if implement each of them .

**Comment by ibelem** [comment]
@cuiyanx @BruceDai @miaobin If i remembered correctly, we need to follow templates below to report these issues. @Christywl 

> Issue template
> o	Ops to be Proposed
> o	Use Case
> o	Native Mapping and Compatibility
> o	Polyfill Support
>   o	WASM
>   o	WebGL

**Comment by ibelem** [comment]
@miaobin @BruceDai @cuiyanx Please create issues one by one for these ops rather than put them together. Team needs to decide if implementing any of them .

@miaobin @BruceDai @cuiyanx Please create issues one by one for these ops rather than put them together. Team needs to decide if implementing any of them .

@miaobin @BruceDai @cuiyanx Please create issues one by one for these ops rather than put them together. Team needs to decide if implementing any of them .

**Comment by ibelem** [comment]
@miaobin @BruceDai @cuiyanx Where is the native comparison table for getting help from developers?

**Comment by miaobin** [comment]
This issue was split to following issues: #1006 #1018 #1019 #1020 
Close the issue.
