### ISSUE TITLE
Sigmoid (logistic) op support for Face-Reidentification and DeepSpeech

### ISSUE THREAD

**Issue by cuiyanx** [intel/webml-polyfill#1006]
Face-Reidentification model has Sigmoid op in the graph.

Activation(Sigmoid) op:

![Screenshot from 2019-09-29 15-06-18](https://user-images.githubusercontent.com/22387607/65828186-bdf91680-e2ca-11e9-9d34-09dbec55d526.png)

Face-Reidentification model need ops table:

![Screenshot from 2019-09-29 15-04-24](https://user-images.githubusercontent.com/22387607/65828213-ff89c180-e2ca-11e9-867b-842dbe25741a.png)

As a  Activation(Sigmoid) op, NNAPI has  **ANEURALNETWORKS_LOGISTIC** op, and ONNX has  **Sigmoid** op.

<table>
    <tr>
        <th>Type</th>
        <th>Detail</th>
        <th>NNAPI</th>
	<th>ONNX</th>
    </tr>
    <tr>
        <td rowspan="3">Sigmoid</td>
	<td>Op</td>
        <td><a href="https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a82a340eb540933f638db420369650483">ANEURALNETWORKS_LOGISTIC</a></td>
	<td><a href="https://github.com/onnx/onnx/blob/master/docs/Operators.md#Sigmoid">Sigmoid</a></td>
    </tr>
    <tr>
        <td>Input</td>
        <td><p>input[0]: <br>Supported tensor rank: up to 4. <br>A tensor, specifying the input.</p></td>
	<td><p>inputs[“X”]: Input tensor.</p></td>
    </tr>
    <tr>
        <td>Output</td>
        <td><p>output[0]: <br>A tensor of the same OperandCode as input0. For a ANEURALNETWORKS_TENSOR_QUANT8_ASYMM tensor, the scale must be 1.f / 256 and the zeroPoint must be 0.</p></td>
		<td><p>outputs["Y "]:<br>Output tensor.</p></td>
    </tr>
</table>​

**Comment by ibelem** [comment]
@cuiyanx @BruceDai @miaobin If i remembered correctly, we need to follow templates below to report these issues. @Christywl 

> Issue template
> o	Ops to be Proposed
> o	Use Case
> o	Native Mapping and Compatibility
> o	Polyfill Support
>   o	WASM
>   o	WebGL

**Comment by cuiyanx** [comment]
Detail | NNAPI | ONNX | clDNN | MKLDNN | DML | MPS | BNNS
-- | -- | -- | -- | -- | -- | -- | --
Op | [ANEURALNETWORKS_LOGISTIC](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a82a340eb540933f638db420369650483) | [Sigmoid](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Sigmoid) |   |   |   |   |  
Input | input[0]: Supported tensor rank: up to 4. A tensor, specifying the input.. | inputs[“X”]: Input tensor. |   |   |   |   |   
Output | output[0]: A tensor of the same OperandCode as input0. For a ANEURALNETWORKS_TENSOR_QUANT8_ASYMM tensor, the scale must be 1.f / 256 and the zeroPoint must be 0. | outputs["Y "]:<br>Output tensor. |   |   |   |   |

**Comment by cuiyanx** [comment]
@fujunwei @lisa0314 Please help fill in above table, thanks!

**Comment by miaobin** [comment]
Logistic is also in the DeepSpeech model:
![logistic](https://user-images.githubusercontent.com/17840011/66693614-5fc22f80-ecdd-11e9-9efd-20855aad693a.png)

**Comment by lisa0314** [comment]
@cuiyanx BNNS has been updated. Thanks!

**Comment by cuiyanx** [comment]
This op has been supported and wait PR #983 merged.

**Comment by pinzhenx** [comment]
MKLDNN updated
