### ISSUE TITLE
Video conference application [CV]

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#1007]
WebNN semantic segmentation use case enhancement, it's OK to create a new example rather than stick to [semantic segmentation example](https://intel.github.io/webml-polyfill/examples/semantic_segmentation/).

Following Intelligent Collaboration features or APIs are needed:

Precondition features
- [x] Host: WebRTC server setup - Open WebRTC Toolkit (OWT)
- [x] Client: Rest API server enabling
- [x] Video Conference enabling with multiple attendees

Web Machine Learning features
- [x] Performance indicators
- [x] Blur my background (Semantic Segmentation)
- [x] Replace my background (Semantic Segmentation)
- [x] Public SS to WebRTC server

Comprehensive features
 - [x] UI and layout for desktop
 - [x] More conference features - Video pause
 - [x] More conference features - Mute
 - [ ] More conference features - Audio only
 - [x] More conference features - Screen Sharing
 - [x] More conference features - Conversation / Text message...
 - [x] UE - Full screen
 - [ ] UE - Seamless switching between normal video and inferenced canvas to WebRTC server
 - [ ] UI and layout for mobile
 - [ ] Performance and optimization

**Comment by BruceDai** [comment]
We can refer to the Video conference demo of [WebRTC-Experiment Repo](https://github.com/muaz-khan/WebRTC-Experiment)

Use API [HTMLMediaElement.captureStream()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream) for handling MediaStream object.

**Comment by BruceDai** [comment]
Link resource https://developers.google.com/web/updates/2016/10/capture-stream
