### ISSUE TITLE
[DML] Investigate the data transformation cost

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#1010]
DML accepts NCHW where WebNN supplies NHWC. It is helpful to understand the data transformation cost.

**Comment by fujunwei** [comment]
For DeppLab 224 atrous(the input tensor is 224 * 224 * 3, output tensor is 224 * 224 * 21), the data transformation only cost ~2ms seeing below steps of testing,

1,  Record inference time as usual
2,  Remove code of data transformation in https://github.com/otcshare/chromium-src/blob/webml/services/ml/execution_impl_dml.cc#L49 and https://github.com/otcshare/chromium-src/blob/webml/services/ml/execution_impl_dml.cc#L93
3, Record inference time again
