### ISSUE TITLE
[Doc] opens of BNNS Conv2D native mapping

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#1012]
There are some opens for BNNS Conv2D doc in [native mapping table](https://docs.google.com/spreadsheets/d/1nthZOwgIKsj34EB-SymEwoNTPsxo4X8Pxavm-JaBwME/edit#gid=0):
1. input: it says "4-D tensor (NCWH)". It should be NCHW according to the formula `data[x + row_stride * y + image_stride * c]`.
2. weigthts: it doesn't say layout explicitly. It would be good to specify the layout in `[depth_out, depth_in, filter_height, filter_width]`.
2. padding: it says "[Note]: right and bottom of explicit padding is not supported". It would be better to say it only supports same left and right paddings and same top and bottom paddings.

What do you think? @lisa0314

**Comment by lisa0314** [comment]
I agree with your above comments. @huningxin

**Comment by huningxin** [comment]
Thanks @lisa0314 . Fixed.
