### ISSUE TITLE
[NNAPI] Support LOGISTIC op

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1026]

**Comment by mingmingtasd** [comment]
LOGISTIC test results:
https://brucedai.github.io/webnnt/test/logistic.html?prefer=sustained
Android: all pass

Manual regression test results:
https://brucedai.github.io/webnnt/test/index-local.html?prefer=sustained
Android : passes: 435 failures: 282 ([baseline](https://github.com/intel/webml-polyfill/blob/master/test/tools/RegressionChecker/baseline/baseline.config.json#L30): "pass": 435, "fail": 282)

**Comment by mingmingtasd** [comment]
LOGISTIC is supported on Android 9 and Android 10 now.

**Comment by Christywl** [comment]
LOGISTIC op works for NNAPI on Google pixel 3(Android 9.0) with build https://github.com/otcshare/chromium-src/commit/270f639f9ab6be2eeeb86fb9ab82930cf94fb60a.
