### ISSUE TITLE
[NNAPI] Support PRELU op

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1033]

**Comment by ibelem** [comment]
@mingmingtasd Could you please close this issue if the PR was merged?

**Comment by mingmingtasd** [comment]
> @mingmingtasd Could you please close this issue if the PR was merged?
OK, I will. Thanks! @ibelem

**Comment by mingmingtasd** [comment]
Please notice that PRELU is only supported on  Android 10.

**Comment by Christywl** [comment]
PRELU works on NNAPI(Android 10) with https://github.com/otcshare/chromium-src/commit/def95eb6c61c0eeb40f654873d6faeb98e1ca66c.
