### ISSUE TITLE
Ops that have not been implemented in tfjs-backend-webgpu

### ISSUE THREAD

**Issue by NALLEIN** [intel/webml-polyfill#1047]
Ops that have not been implemented in webgpu but used in webml-polyfill

Ops | Usage
-- | --
avgPool | SqueezeNet;  Inception v3;  Inception v4;  Inception ResNet v2;  ResNet50;    DenseNet 121;    DeepLab224,267,321,513;
batchToSpaceND | SRGAN;
maximum | Tiny YOLO v2;
softmax | SqueezeNet;  Inception v3;  Inception v4;  Inception ResNet v2;
tanh | SRGAN;

**Comment by huningxin** [comment]
Thanks @NALLEIN . Please edit the ops usage part and make it as a table by using [markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by NALLEIN** [comment]
> Ops that have not been implemented in webgpu but used in webml-polyfill
> 
> Ops	Usage
> avgPool	SqueezeNet;  Inception v3;  Inception v4;  Inception ResNet v2;  ResNet50;  DenseNet 121;  DeepLab224,267,321,513;
> batchToSpaceND	SRGAN;
> maximum	Tiny YOLO v2;
> softmax	SqueezeNet;  Inception v3;  Inception v4;  Inception ResNet v2;
> tanh	SRGAN;

**Comment by NALLEIN** [comment]
Ops with naive implemention : avgPool,tanh,maximum. Trying reduce_op and slice.
[Ops test](https://github.com/NALLEIN/tfjs.git)

**Comment by NALLEIN** [comment]
@huningxin I tried to implement the missing op in webgpu-backend with compute shader, but did not test it carefully. I'm wondering if I need to test these ops with QA to see if these ops can meet the needs of polyfill.
 Maybe we can add a webgpu-backend in webml-polyfill project, and follow the tfjs-webgpu-backend if tfjs-backend-webgpu is officially updated
[Ops test](https://github.com/NALLEIN/tfjs/tree/opsTest)

**Comment by NALLEIN** [comment]
@huningxin @ibelem 
I have integrate with WebGPUBackend of TF.js. Model inference in polyfill does not report error, but the result is incorrect. May need some testing tools to help locate errors.
[opsForPolyfill](https://github.com/NALLEIN/tfjs/tree/opsForPolyfill)
[replace WebGL backend with WebGPU backend](https://github.com/NALLEIN/webml-polyfill/tree/WebGPU-backend-test)
