### ISSUE TITLE
[Example] Update URL for facenet.bin

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#1054]
The URL of facenet.bin in https://github.com/intel/webml-polyfill/tree/master/examples/face_recognition/model is not .bin file but the original .pb and .ckpt files, please update.

**Face Recognition Model**
Download and convert following models here:
facenet.bin and facenet.xml.

**Comment by cuiyanx** [comment]
@ibelem sorry, I have a mistake.
