### ISSUE TITLE
[NNAPI] The prediction results of use cases on Android version 10.0  are incorrect

### ISSUE THREAD

**Issue by mingmingtasd** [intel/webml-polyfill#1060]
Test Env:
Chromium Version:  nightly build 79.0.3917.0 (e7b9a67)
Platform: Android 10; Pixel 2 XL

Expected Result:
The prediction results should be correct on Android version 10.0.

Actual Result:
The prediction results of use cases on Android version 10.0 are incorrect everytime after selecting a new model and then selecting the WebNN backend. But if we click the WebNN backend again, the prediction results will be updated correctly. I choose image classification and semantic segmentation as examples:

![Screenshot from 2019-11-06 09-46-21](https://user-images.githubusercontent.com/52519066/68261662-cbe54880-007b-11ea-870a-d771a1371065.png)
![Screenshot from 2019-11-06 09-46-33](https://user-images.githubusercontent.com/52519066/68261665-d0116600-007b-11ea-9221-8e943692b433.png)
![Screenshot from 2019-11-06 09-45-32](https://user-images.githubusercontent.com/52519066/68261674-d3a4ed00-007b-11ea-949f-f1f950edc7a6.png)
![Screenshot from 2019-11-06 09-45-48](https://user-images.githubusercontent.com/52519066/68261676-d6074700-007b-11ea-92fb-79bb68f81c70.png)

How to Reproduce:

1. Install the chromium apk on the Android phone with version 10.0.

2. Start local server using "npm start", and visit “http://<192.168.42.*>:8080/examples/image_classification" or "http://<192.168.42.*>:8080/examples/semantic_segmentation" on chromium.

3. Select one model and select "SUSTAINED_SPEED" as backend, you'll get wrong prediction results.

4. Click the "SUSTAINED_SPEED" again and then the prediction results will be right.

**Comment by mingmingtasd** [comment]
Android version 10 maps to API level 29 and Android version 9 maps to API level 28. Some ops such as MAXIMUM, PRELU, ARGMAX and ARGMIN are available since API level 29.

**Comment by mingmingtasd** [comment]
I find the reason of this issue on Android version 10.0: 
In the repo webml-polyfill, the function "this._execution.startcompute()" is called twice (first time by warmup process and the second time by actual prediction). Accordingly, the function "ANeuralNetworksExecution_startCompute" in NNAPI is called twice. Then an error will be reported out telling us we  shouldn't call an execution that has already started. But on Android version 9.0, there is noting wrong. 

So I tried to delete the function "this._execution.startcompute()" called by warmup in webml-polyfill, and then there would be no error. But I am not sure whether we could fix this issue in this way and I will try to find other better ways. @fujunwei @ibelem

**Comment by fujunwei** [comment]
@mingmingtasd  Good progress. Maybe some resources have released after first compute, maybe we should can ANeuralNetworksExecution_seInput /output before computer again, It's better to have a native app to reproduce if it's hard to debug on Android platform.

**Comment by mingmingtasd** [comment]
@fujunwei OK, thanks for your suggestions！!

**Comment by mingmingtasd** [comment]
I verified that using the camera to pick a new image wouldn't fix this issue. @fujunwei

**Comment by mingmingtasd** [comment]
I tested using native app on Android studio. I modified the codes [here](https://github.com/mingmingtasd/ndk-samples/blob/master/nn_sample/app/src/main/cpp/simple_model.cpp) to call the "ANeuralNetworksExecution_startCompute" twice. Then Android version 10.0 still reported this issue and  Android version 9.0 was OK. Thus this issue seems to be caused by the API of [Android NDK](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1gad9b39e20b5a2c662865290de11482922) actually. 

So I submitted the issue to Google Issue Tracker https://issuetracker.google.com/issues/144381394 and now it has been assigned to someone. I will keep on tracking the progress. @fujunwei @ibelem @huningxin

**Comment by mingmingtasd** [comment]
I tested using native app on Android studio. I modified the codes [here](https://github.com/mingmingtasd/ndk-samples/blob/master/nn_sample/app/src/main/cpp/simple_model.cpp) to call the "ANeuralNetworksExecution_startCompute" twice. Then Android version 10.0 still reported this issue and Android version 9.0 was OK. Thus this issue seems to be caused by the API of [Android NDK](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1gad9b39e20b5a2c662865290de11482922) actually.

So I submitted the issue to Google Issue Tracker https://issuetracker.google.com/issues/144381394 and now it has been assigned to someone. I will keep on tracking the progress. @fujunwei @ibelem @huningxin

**Comment by huningxin** [comment]
You may need to create a new Execution after started it. 

As doc mentions, for Android 10, you may try [burst execution API](https://developer.android.com/ndk/guides/neuralnetworks#burst-executions) for sustained execution.

**Comment by mingmingtasd** [comment]
I verified that we can use the same compilation instance to create a new [ANeuralNetworksExecution](https://developer.android.com/ndk/reference/group/neural-networks#aneuralnetworksexecution) instance. Codes are shown below:
```
// Apply the compiled model to a different set of inputs
ANeuralNetworksExecution* run2;
ANeuralNetworksExecution_create(compilation, &run2);
ANeuralNetworksExecution_setInput(run2, ...);
ANeuralNetworksExecution_setOutput(run2, ...);
ANeuralNetworksEvent* run2_end = NULL;
ANeuralNetworksExecution_startCompute(run2, &run2_end);
ANeuralNetworksEvent_wait(run2_end);
ANeuralNetworksEvent_free(run2_end);
ANeuralNetworksExecution_free(run2);
```
Also tried [burst execution API](https://developer.android.com/ndk/guides/neuralnetworks#burst-executions) ,but it shows that [ANeuralNetworksBurst](https://developer.android.com/ndk/reference/group/neural-networks#aneuralnetworksburst) object is unkonwn (maybe need to be included in advance?)
@ibelem @huningxin @fujunwei

**Comment by mingmingtasd** [comment]
Fixed by https://github.com/otcshare/chromium-src/pull/16, close it.
