### ISSUE TITLE
[MobileNet.js] Support MobileNetV2

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#107]
Base on [MobileNetV2: The Next Generation of On-Device Computer Vision Networks](http://ai.googleblog.com/2018/04/mobilenetv2-next-generation-of-on.html) , the MobileNetV2 was published and the for detection when paired with the newly introduced SSDLite the new model is about 35% faster with the same accuracy than MobileNetV1, so it's necessary to support MobileNetV2 in our project.

**Repro Steps:**

1. Visit [MobileNetV2 README](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet/README.md), download [mobilenet_v2_1.0_224.tgz](https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz)
2. Unzip mobilenet_v2_1.0_224.tgz
3. Copy unzipped mobilenet_v2_1.0_224.tflite to ~/webml-polyfill/examples/mobilenet/model
4. keep 1.0 labels.txt under ~/webml-polyfill/examples/mobilenet/model
5. Update `const MODEL_FILE = './model/mobilenet_v1_1.0_224.tflite';` to 
`const MODEL_FILE = './model/mobilenet_v2_1.0_224.tflite'; `in /webml-polyfill-run/examples/mobilenet/utils.js 
6. npm start
7. Visit http://127.0.0.1:8081/examples/mobilenet/

**Actual Result:**

```
MobileNet.js:193 Uncaught (in promise) Error: operator type 0 is not supported.
    at MobileNet._addOpsAndParams (MobileNet.js:193)
    at MobileNet.createCompiledModel (MobileNet.js:36)
    at <anonymous>
```

The operator type 0 should be tflite.BuiltinOperator.ADD

**Comment by ibelem** [comment]
Same result, actually I have exactly the same fix code (in both MobileNet.js and TfLiteModelUtils.js) with @GreyZzzzzzXh's last week for this issue, but i didn't submit PR due to the label probability drops to 84.14% for "bee eater" (in 1.0 zip the label probalility is 99.71%) although the inference time 266.80ms is much faster in 2.0 comparing with 465.50ms in 1.0. Hope @GreyZzzzzzXh can investigate native lite app further. :)

**Comment by GreyZzzzzzXh** [comment]
> The WebGL2 path still has issue.

Yes.


 OK I'll try to do some investigattion soon.

**Comment by huningxin** [comment]
#114 only fixes the example. So far, `wasm` and `NNAPI` backends should work (need verification). We still need to support `ADD` in WebGL2 #93 and MPS #92 . So reopen it.

**Comment by GreyZzzzzzXh** [comment]
According to the [TF Lite Android Demo App Page](https://www.tensorflow.org/mobile/tflite/demo_android), I built APK using models float-mobilenet v1([mobilenet_v1_1.0_224_float_2017_11_08.zip](https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_1.0_224_float_2017_11_08.zip)) and v2([mobilenet_v2_1.0_224.tgz](https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz)) respectively. 
But it seems that v1 is still a little more accurate in native lite, e.g., my mouse can get a score 0.99 in v1 while that is 0.90 in v2, and sungless is 0.7(v1) & 0.5(v2).
Could @ibelem please help to do more testing with my built APK? If we still have the same result, there may be something wrong with the model v2 which we download, I guess. :)

**Comment by Christywl** [comment]
@GreyZzzzzzXh , could you please provide your built APK to do more testing?

**Comment by Christywl** [comment]
Hi, @GreyZzzzzzXh , I tried your APKs(V1 and V2) on Google Pixel 2, the results:

Object | V1 | V2 
-- | -- | -- 
mouse | 1.00 | 0.97 
sunglasses | 0.91 | 0.72

**Comment by GreyZzzzzzXh** [comment]
@Christywl , thanks!

**Comment by Wenzhao-Xiang** [comment]
@BruceDai , please help verify. Thanks!

**Comment by Christywl** [comment]
@Wenzhao-Xiang, MobileNet V2 example works fine with NNAPI/WASM/WebGL2, but it doesn't work on MPS.
