### ISSUE TITLE
[clDNN] clDNN doesn't work on Ice Lake(Intel Iris Plus Graphic)

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1073]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0(9642fde)
Platform: Windows/Linux [CPU: Intel i7-1065G7(Ice Lake), GPU: Intel Iris Plus Graphics]

**Expected Result:**
clDNN works on Ice Lake(Intel Iris Plus Graphic)

**Actual Result:**
clDNN doesn't work on Ice Lake(Intel Iris Plus Graphic).
Errors in the terminal:

```
[WARNING]. Device ID (0x8A52) not supported. Pretending to behave like SKL GT2.
[2511:2611:1108/000708.204004:ERROR:compilation_delegate_cl_dnn.cc(155)] [clDNN] failed to create cldnn ocl engine -1 _Map_base::at
```

**How to Reproduce:**
1. Visit https://intel.github.io/webml-polyfill/examples/image_classification/index.html
2. Select SUSTAINED
3. Select one model

**Comment by huningxin** [comment]
Thanks for reporting this issue. The root cause is he M75 build you tested that contains a old clDNN which doesn't support ice lake. Are you able to try M79 build after commit https://github.com/otcshare/chromium-src/commit/dcbd4abd891e918adf5d66b536ac1ba27b34c06e?

**Comment by Christywl** [comment]
Tried M79 builds after https://github.com/otcshare/chromium-src/commit/dcbd4abd891e918adf5d66b536ac1ba27b34c06e, clDNN worked. The M75 and M79 builds before this commit didn't work. I'll close this issue.
