### ISSUE TITLE
[NNAPI] some depthwise_conv_2d tests failed for NNAPI on Android 10

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1075]
**Test Env:**
Chromium Version: nightly build 79.0.3917.0(e7b9a67)
Platform: Google Pixel 2 XL(Android 10)

**Expected Result:**
Depthwise_conv_2d tests should pass for NNAPI on Android 10.

**Actual Result:**
Tests failed on Android 10:
![Screenshot from 2019-11-14 15-40-38](https://user-images.githubusercontent.com/20039821/68836215-cbd8ee80-06f4-11ea-9484-f708f08366d6.png)

**How to Reproduce:**
1. Install Chromium build 
2. Visit https://brucedai.github.io/webnnt/test/issue_depthwise_2.html?prefer=sustained

**Comment by BruceDai** [comment]
According to @mingmingtasd provided output log
![1](https://user-images.githubusercontent.com/1531742/68915451-14e47d80-079d-11ea-90fc-484d8b2156ac.png), we checked [log of nn/common/OperationsUtils.cpp](https://android.googlesource.com/platform/frameworks/ml/+log/master/nn/common/OperationsUtils.cpp), and found the latest **depthwiseConvPrepare** method involved  **depth_multiplier value checking** after landding [8ebaf89](https://android.googlesource.com/platform/frameworks/ml/+/8ebaf89d6365104e053e46eeb19d37ae1b83b7ed) commit for 'Fix tests, add depth_multiplier value check in DEPTHWISE_CONV_2D. '
```c++
NN_OPS_CHECK(depth_multiplier * channels_in == channels_out);
```
So above reported tests(depth_multiplier = 1, channels_in =3, channels_out=4) failed on this  depth_multiplier value checking
```c++
3 * 1 ==  4 # the result is False
```

And we also checked [latest Android CTS test](https://android.googlesource.com/platform/frameworks/ml/+/master/nn/runtime/test), the reported tests have been upgraded by [70b2517](https://android.googlesource.com/platform/frameworks/ml/+/70b2517bf861412d3a6de466e3be55c02c3a0576) commit.

So we should have a discussion about upgrading CTS tests align with latest Android CTS tests. @huningxin @ibelem @fujunwei

**Comment by mingmingtasd** [comment]
Hi, have these CTS tests been upgraded? Please help to check and close this issue. Thanks! @BruceDai @Christywl

**Comment by Christywl** [comment]
@BruceDai  @mingmingtasd  the updated tests passed on NNAPI.
