### ISSUE TITLE
[WebGL2] 2D dimensions shapes are not supported

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#111]
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision 81edd55)
OS : Mac OS
webml-polyfill: commit [ee18609](https://github.com/intel/webml-polyfill/commit/ee18609f980abe735f88e0547a9240c3b2f98ba7)

**Expected Result:**
Support the 2D shapes

**Actual Result:**
2D dimensions shapes are not supported:

`Error: the shape 2,3 is not supported`
`Error: the shape 52,230 is not supported`
`Error: the shape 212,60 is not supported`
`Error: the shape 1,4 is not supported`
`Error: the shape 2,5 is not supported`           
**How to reproduce:**
1. Launch chromium and disable the WebML
2. Run tests: Access to https://brucedai.github.io/nt/test/cts-all.html?backend=webgl2
	
   - check result for Concat float example/1     
   - check result for Concat float example/2  	
   - check result for Concat float example/3  		
   - check result for Softmax float example/1	
   - check result for Softmax float example/2

**Comment by Wenzhao-Xiang** [comment]
Support 2D shapes for ops "concatenation" and "pool".
But I'm not sure if there are any problems with other ops.
Does the case exist that the input of ops "convolution" is 2D?

**Comment by huningxin** [comment]
I understand the conv op is only for 4D tensor. Correct me if I am wrong.
