### ISSUE TITLE
[WASM] The inference time becomes larger after tensorflow version is upgraded to r1.15

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1122]
**Test Env:**
Chromium Version: nightly build  79.0.3917.0(9ecb985)
Platform: all 

**Expected Result:**
No regression was found.

**Actual Result:**
The inference time becomes larger after tensorflow version is upgraded to r1.15: 
[r1.13-a5176d6-Nov-11](https://github.com/intel/webml-polyfill/commit/a5176d611b1b79bef05e5fa53108c23ef375855a)
[r1.15-1e077dc-Nov-12](https://github.com/intel/webml-polyfill/commit/1e077dcf1eb3704078e69610bf53c36ac91d818a)
[r1.15-6ca0493-Dec-31](https://github.com/intel/webml-polyfill/commit/6ca04936f044ad0eac379ac255bc3283693819b1)

For example: 

Examples/macOS | r1.13-a5176d6-Nov-11 | r1.15-1e077dc-Nov-12 | r1.15-6ca0493-Dec-31
-- | -- | -- | -- 
MobileNet v1(TFLite) | 290.33 | 302.08 | 304.57
MobileNet v2(TFLite) | 198.82 | 207.27 | 205.00
SqueezeNet(TFLite) | 401.4 | 418.93 | 425.39
Inception v3(TFLite) | 2505.97 | 2665.76 | 2685.53
Inception v4(TFLite) | 5285.32 | 5663.08 | 5627.65
MobileNet v2(ONNX) | 273.75 | 285.97 | 284.38
ResNet50 v1(ONNX) | 1701.97 | 1807.79 | 1807.86
MobileNet v2(OpenVino) | 201.53 | 205.36 | 203.22

**How to Reproduce:**

1. Setup two local servers with [r1.13-a5176d6-Nov-11](https://github.com/intel/webml-polyfill/commit/a5176d611b1b79bef05e5fa53108c23ef375855a) and [r1.15-1e077dc-Nov-12](https://github.com/intel/webml-polyfill/commit/1e077dcf1eb3704078e69610bf53c36ac91d818a) commits
2. Select WASM backend
3. Select one model

**Comment by akineeic** [comment]
I have compare the output of the two commit in the workload, and just find that the inference time become larger mainly because each Conv op consumes a little more time. I think this may caused by the update of tensorflow's native API.
