### ISSUE TITLE
GNA1 enabling

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#1125]

**Comment by fujunwei** [comment]
Task ID | Task Title | Assignee | Notes / Status
-- | -- | -- | --
[Issue-1146](https://github.com/intel/webml-polyfill/issues/1146)  |  Parse ark file to get input data | Mingming |  Code Refactoring
[Issue-1145](https://github.com/intel/webml-polyfill/issues/1145)  |  Integrate kaldi model to example | Miaobin |  Code Refactoring
[Issue-1142](https://github.com/intel/webml-polyfill/issues/1142)  |  Add ultra-low button  | Miaobin |  Code Refactoring
[Issue-1143](https://github.com/intel/webml-polyfill/issues/1143)  | Use ultra-low-lower preference to select GNA | Junwei |  Done
