### ISSUE TITLE
[Doc] Update native mapping doc for clDNN

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1129]
https://github.com/intel/webml-polyfill/blob/master/docs/native_mapping.md

Need add the following ops into native mapping doc:

- TRANSPOSE
- BATCH_TO_SPACE_ND
- MAXIMUM
- TANH
- ARGMAX
- LOGISTIC
- PRELU

**Comment by ibelem** [comment]
@Christywl please 4 seperate issues and assigne to developers to track and update.

**Comment by Christywl** [comment]
Done:
MPS/DirectML(https://github.com/intel/webml-polyfill/issues/1137): junwei
BNNS/DNNL(https://github.com/intel/webml-polyfill/issues/1138): lisha
NNAPI/ONNX(https://github.com/intel/webml-polyfill/issues/1139): mingming
clDNN(https://github.com/intel/webml-polyfill/issues/1129): ningxin

**Comment by huningxin** [comment]
ARGMAX, LOGISTIC, PRELU are done. Others are not implemented by clDNN now.
