### ISSUE TITLE
How to support Convolution2DTransposeBias, MaxPoolArgmax, and MaxUnpooling

### ISSUE THREAD

**Issue by sitharakrishnamurthy** [intel/webml-polyfill#1136]
Hi,

How can I add custom opCode like Convolution2DTransposeBias, MaxPoolArgmax, and MaxUnpooling to load my model? Please guide me on how to proceed.

Thanks

**Comment by BruceDai** [comment]
Hi @sitharakrishnamurthy , thanks for reporting this issue.
Current Web NN polyfill API could support TensorFlow(TFLite), ONNX and OpenVINO three format models, here're these model importers [TFliteModelImporter](https://github.com/intel/webml-polyfill/tree/master/examples/util/tflite), [OnnxModelImporter](https://github.com/intel/webml-polyfill/tree/master/examples/util/onnx) and [OpenVINOModelImporter](https://github.com/intel/webml-polyfill/tree/master/examples/util/openvino).What's the format of your model? 
If your model format was one of our supported formats, you could add implementation for your required ops by referring to PR #1043.

**Comment by BruceDai** [comment]
@sitharakrishnamurthy Did I answer your question before? We plan to close this issue, thanks.

**Comment by sitharakrishnamurthy** [comment]
Thank you for the pointers.
