### ISSUE TITLE
[Doc] Update native mapping doc for MPS and DirectML

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1137]
https://github.com/intel/webml-polyfill/blob/master/docs/native_mapping.md

Need add the following ops into native mapping doc:

- TRANSPOSE
- BATCH_TO_SPACE_ND
- MAXIMUM
- TANH
- ARGMAX
- LOGISTIC
- PRELU

**Comment by fujunwei** [comment]
Done in https://drive.google.com/file/d/1jTcB5hjrFUNnCaI1SC7yIgxwf7xQ0WjL/view?usp=sharing

**Comment by huningxin** [comment]
Looks good and merged.
