### ISSUE TITLE
[Doc] Update native mapping doc for NNAPI and ONNX

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1139]
https://github.com/intel/webml-polyfill/blob/master/docs/native_mapping.md

Need add the following ops into native mapping doc:

- TRANSPOSE
- BATCH_TO_SPACE_ND
- MAXIMUM
- TANH
- ARGMAX
- LOGISTIC
- PRELU

**Comment by mingmingtasd** [comment]
https://docs.google.com/spreadsheets/d/1PoS_lhr7wsO-jW0FYM9ecvAADPMfXxZJFu5oaIJOwCs/edit?usp=sharing
I have updated mapping doc for NNAPI and ONNX, please help to review these highlighted contents, thanks! @huningxin

**Comment by huningxin** [comment]
Thanks @mingmingtasd . For argument mapping, please keep it simple. It is just needed to list the parameter name in native API with necessary information. It isn't needed to copy and paste all content from native API documentation. Please refer to previous ones as example.

**Comment by mingmingtasd** [comment]
> Thanks @mingmingtasd . For argument mapping, please keep it simple. It is just needed to list the parameter name in native API with necessary information. It isn't needed to copy and paste all content from native API documentation. Please refer to previous ones as example.

I have updated this doc as you suggested. Thanks! @huningxin

**Comment by huningxin** [comment]
Thanks @mingmingtasd ! NNAPI column looks good and I merged it.

For ONNX part, we may need to remove that column as it is not used for implementation. @belem , any thoughts?

**Comment by mingmingtasd** [comment]
Merged, so close this issue.
