### ISSUE TITLE
[INT8][DNNL] Implementation of CONV_2D and DEPTHWISE_CONV_2D 

### ISSUE THREAD

**Issue by lisa0314** [intel/webml-polyfill#1166]
i.	Map TENSOR_QUANT8_ASYMM_SIGNED  and TENSOR_QUANT8_ASYMM for input and output to s8 memory primitive
ii.	Map TENSOR_QUANT8_SYMM_PER_CHANNEL for weights to s8 memory primitive
iii.	Map TENSOR_INT32 for bias to s32 memory primitive
iv.	Set output scales primitive attribute based on input scale, weight’s per channel scale and output scale (scale_input * scale_weights / scale_output).

**Comment by huningxin** [comment]
For title, I would suggest to remove `VNNI` and probably add `INT8`. In general we would support INT8  in CONV_2D by using DNNL. DNNL will decide to generate `VNNI` instructions or other instructions based on CPU it runs.

**Comment by huningxin** [comment]
Please see whether it implements API change #1173
