### ISSUE TITLE
[MPS] MUL is not supported for MPS

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#117]
`MUL` operation is not supported for MPS:
https://github.com/intel/webml-polyfill/blob/master/docs/supported_ops.md

Op Type |  MPS
-- | -- 
ADD | no 
MUL | no

**Comment by huningxin** [comment]
Fixed. @BruceDai , please verify. Thanks!

**Comment by Christywl** [comment]
Verified this with MPS backend on nightly build b7ce158, the test passed. https://brucedai.github.io/nt/test/mul.html?backend=mps
