### ISSUE TITLE
[example] Add new SRmodel in polyfill

### ISSUE THREAD

**Issue by NALLEIN** [intel/webml-polyfill#1174]
We can run a SR model in [polyfill](https://github.com/NALLEIN/webml-polyfill/tree/Add-SR-Model). But there is still a problem with UI for update result.
New IDN model is in progress.

**Comment by NALLEIN** [comment]
We can run agora-model in [polyfill](https://github.com/NALLEIN/webml-polyfill/tree/Add-SR-Model).But there is still a problem with UI for update result.
New IDN model is in progress.

**Comment by NALLEIN** [comment]
The inferencetime in polyfill is about 200-250ms and the inference time of the sr_tfjs example is about 350-400ms .
![SR  in polyfill](https://raw.githubusercontent.com/NALLEIN/MarkdownFigures/master/SR_in_polyfill.png)
![SR in sr_tfjs](https://raw.githubusercontent.com/NALLEIN/MarkdownFigures/master/sr-tf-example.png)

**Comment by ibelem** [comment]
Close this issue, use OpenVINO model instead.
