### ISSUE TITLE
[Test] Add CTS test cases for 'CONV_2D' and 'DEPTHWISE_CONV_2D' with TENSOR_QUANT8_ASYMM_SIGNED input

### ISSUE THREAD

**Issue by cuiyanx** [intel/webml-polyfill#1178]
Add CTS test cases for 'CONV_2D' and 'DEPTHWISE_CONV_2D':
 - CONV_2D with TENSOR_QUANT8_ASYMM_SIGNED input and TENSOR_QUANT8_SYMM_PER_CHANNEL weights
- DEPTHWISE_CONV_2D with TENSOR_QUANT8_ASYMM_SIGNED input and TENSOR_QUANT8_SYMM_PER_CHANNEL weights

**Comment by cuiyanx** [comment]
Not support by release version(newest: [android-cts-10.0_r3](https://android.googlesource.com/platform/frameworks/ml/+/refs/tags/android-cts-10.0_r3)), but [master branch](https://android.googlesource.com/platform/frameworks/ml/+/refs/heads/master/nn/runtime/test/specs) has supported. I will create CTS test cases by our CTS vonverter tool. If create fail, I will by manual.

**Comment by huningxin** [comment]
Hi @cuiyanx , any updates? I depend on the test cases for WASM polyfill implementation. Thanks!

**Comment by cuiyanx** [comment]
@huningxin I add CTS test cases to [per-channel-and-quant8-asymm-signed](https://github.com/cuiyanx/dnnl-models/tree/master/select-CTS-test/per-channel-and-quant8-asymm-signed), please test.

**Comment by huningxin** [comment]
@cuiyanx thanks! Could you please create a PR to add those tests.

**Comment by cuiyanx** [comment]
@huningxin OK, I will do it.
