### ISSUE TITLE
[Doc] The WebML API native mapping

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#118]
I've initiated a spreadsheet to capture this. 

https://docs.google.com/spreadsheets/d/1nthZOwgIKsj34EB-SymEwoNTPsxo4X8Pxavm-JaBwME/edit?usp=sharing

Will keep updated it.

**Comment by ibelem** [comment]
Add BNNS mapping by Lisa

**Comment by huningxin** [comment]
@lisa0314 , in your copy https://docs.google.com/spreadsheets/d/1PvsGWmVrbfuDJNXBM-tD7KV4xckj8rHmzh1Z60WHf9c/edit#gid=0, there are two comments unresolved. Please take a look.

**Comment by lisa0314** [comment]
@huningxin , Done. Please help to review.

**Comment by huningxin** [comment]
Merged. Thanks!
