### ISSUE TITLE
[Test] almostEqual doesn't support quant8 data types

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#1182]
The current [`almostEqual`](https://github.com/intel/webml-polyfill/blob/master/test/utils.js#L14) only supports float data type. It needs to be fixed to support quant8 data type. According to [android cts test](https://android.googlesource.com/platform/frameworks/ml/+/master/nn/tools/test_generator/test_harness/TestHarness.cpp#248), the default tolerance of quant8 is 1.

**Comment by cuiyanx** [comment]
I have fixed by #1163 and #1180.

**Comment by cuiyanx** [comment]
PR merged and closed!
