### ISSUE TITLE
[IE] Upgrade Inference Engine with source code

### ISSUE THREAD

**Issue by fujunwei** [intel/webml-polyfill#1192]
1, IE-CLDNN fail to run on Ice Lake similar with [the issue](https://github.com/intel/webml-polyfill/issues/1073), there are below error messages on Windows.
`Device lookup failed - unsupported device id:0x8A52. Note HD5xx+ devices are supported`

2, GNA device must be closed before opening again seeing [the issue](https://github.com/intel/webml-polyfill/issues/1154)

We still need to integrate source code because nGraph is C++ API although DLDT has supported C API.

**Comment by huningxin** [comment]
Thanks for opening this issue and sharing the status. Do you have a target version of Inference Engine to be integrated?

**Comment by fujunwei** [comment]
How about focusing on the latest version 2020.1?

**Comment by huningxin** [comment]
It sounds good to me. Thanks.
