### ISSUE TITLE
Enhance Image classification example using OpenCV.js

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#1205]
Run Image classification example with SqueezeNet(ONNX)/MobileNet v2(ONNX)/ResNet v1(ONNX)/ResNet v2(ONNX) models using OpenCV.js.

**Comment by BruceDai** [comment]
Added **Framework** on the UI page to enable user select target testing framework, as following image:

![1](https://user-images.githubusercontent.com/1531742/79932023-0b172280-847f-11ea-8c80-0cb805e8ff39.JPG)

and url of the example is updated by adding 'f' parameter,likes
```js
https://127.0.0.1:8080/examples/image_classification/?prefer=none&b=WebGL&m=squeezenet_onnx&s=image&d=0&f=WebNN
```
or
```js
https://127.0.0.1:8080/examples/image_classification/?prefer=none&b=WebGL&m=squeezenet_onnx&s=image&d=0&f=OpenCV.js
```

Here's the result image after using OpenCV.js framework with selected SqueezeNet ONNX model & Threads backend:

![2](https://user-images.githubusercontent.com/1531742/79932030-0d797c80-847f-11ea-93a8-cad3ebf6f1dc.JPG)

Currently the supported models for OpenCV.js are sub set of the modes for WebNN, so if we selected the SqueezeNet ONNX model to run by OpenCV.js, when we switch to using WebNN Framework, the same SqueezeNet ONNX model will also ran with default WASM backend:

![3](https://user-images.githubusercontent.com/1531742/79932506-41a16d00-8480-11ea-8407-b34c3e5a5c7e.JPG)
 
While there will be none model being selected when switching to run Framework OpenCV.js after running TFLite or OpenVINO models by WebNN.

**Comment by huningxin** [comment]
It looks pretty good. Thanks @BruceDai ! Can we support 'Live Camera' by OpenCV.js framework?
