### ISSUE TITLE
[Test] Add cts test for Int8AveragePool

### ISSUE THREAD

**Issue by lisa0314** [intel/webml-polyfill#1212]
@cuiyanx please help to preppare the cts test for int8 average pool. Thanks!

**Comment by cuiyanx** [comment]
@lisa0314 @huningxin 
Add some CTS test cases for `avg-pool` ops. If any change, please tell me.
https://github.com/cuiyanx/dnnl-models/tree/master/select-CTS-test/AVERAGE_POOL_2D

**Comment by huningxin** [comment]
Thanks @cuiyanx ! Could you please tell which test cases are for int8 average pool? I only found https://github.com/cuiyanx/dnnl-models/blob/master/select-CTS-test/AVERAGE_POOL_2D/V1_3/avg_pool_quant8_signed.js. Any others?

**Comment by cuiyanx** [comment]
Those are all CTS test cases we can convert. The [V1_3](https://github.com/cuiyanx/dnnl-models/tree/master/select-CTS-test/AVERAGE_POOL_2D/V1_3) is newest CTS test cases by `zeroPoint: -128`. The [V1_2](https://github.com/cuiyanx/dnnl-models/tree/master/select-CTS-test/AVERAGE_POOL_2D/V1_2) is `zeroPoint: 0`.
