### ISSUE TITLE
[Test]Add cts test for QUANTIZE and DEQUANTIZE

### ISSUE THREAD

**Issue by lisa0314** [intel/webml-polyfill#1216]

**Comment by cuiyanx** [comment]
@lisa0314 @huningxin
Add some CTS test cases for `dequantize` and `quantize` ops. If any change, please tell me.
https://github.com/cuiyanx/dnnl-models/tree/master/select-CTS-test/DEQUANTIZE
https://github.com/cuiyanx/dnnl-models/tree/master/select-CTS-test/QUANTIZE

**Comment by cuiyanx** [comment]
Done, so closed
