### ISSUE TITLE
WebNN API is not supported in ubuntu 18.04

### ISSUE THREAD

**Issue by maheshpalkar** [intel/webml-polyfill#1235]
I am trying to run WebNN API examples in ubuntu 18.04.
I have installed openVino.
When I want to choose WebNN as backend but it shows WebNN api not supported.
This is my system configuration : (uname -a)
Linux test-NUC8i7BEH 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

![webnn_error](https://user-images.githubusercontent.com/65035270/81510102-18f8ee80-932d-11ea-94cb-0fca65f5cd72.PNG)
 

I have attached screenshot of page it shows that WebNN API not supported.

Can someone help me to enable WebNN API support ?

**Comment by ibelem** [comment]
@maheshpalkar Thanks for trying WebNN examples! Are you using WebNN builds built from [How to build chromium on Linux](https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux)? Also please try [otcshare/chromium-src](https://github.com/otcshare/chromium-src) via [Run Chromium builds with WebNN API](https://github.com/intel/webml-polyfill/wiki/How-to-Run-Chromium-builds-with-WebNN-API).

@Christywl

**Comment by fujunwei** [comment]
@maheshpalkar Could you please try to refresh the page, and then what's the result after clicking FAST_SINGLE_ANSWER button?

**Comment by maheshpalkar** [comment]
> @maheshpalkar Thanks for trying WebNN examples! Are you using WebNN builds built from [otcshare/chromium-src](https://github.com/otcshare/chromium-src)? Also please try [How to build chromium on Linux](https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux) and [Run Chromium builds with WebNN API](https://github.com/intel/webml-polyfill/wiki/How-to-Run-Chromium-builds-with-WebNN-API).
> 
> @Christywl
Hi,
Thanks for your reply. 
I had tried to install[ chromium repo using the mentioned steps](https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux). But while doing client sync I have faced following error 
FileNotFoundError: [Errno 2] No such file or directory: '/chromium_webml/src/buildtools/third_party/libc++abi/trunk'

I have found that while building some files are missing, so it is throwing error.
 
I have attached the screenshot for the missing trunk file.

![webnn_error2](https://user-images.githubusercontent.com/65035270/81789528-bd438680-9521-11ea-808c-ffd0c04d2617.PNG)

**Comment by maheshpalkar** [comment]
> hen what's the result afte

Hi,
Thanks for replying. As you suggested I have refreshed the page, then also I have faced the same error saying WebNN API is not supported.

**Comment by miaobin** [comment]
> > @maheshpalkar Thanks for trying WebNN examples! Are you using WebNN builds built from [otcshare/chromium-src](https://github.com/otcshare/chromium-src)? Also please try [How to build chromium on Linux](https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux) and [Run Chromium builds with WebNN API](https://github.com/intel/webml-polyfill/wiki/How-to-Run-Chromium-builds-with-WebNN-API).
> > @Christywl
> > Hi,
> > Thanks for your reply.
> > I had tried to install[ chromium repo using the mentioned steps](https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux). But while doing client sync I have faced following error
> > FileNotFoundError: [Errno 2] No such file or directory: '/chromium_webml/src/buildtools/third_party/libc++abi/trunk'
> 
> I have found that while building some files are missing, so it is throwing error.
> 
> I have attached the screenshot for the missing trunk file.
> 
> ![webnn_error2](https://user-images.githubusercontent.com/65035270/81789528-bd438680-9521-11ea-808c-ffd0c04d2617.PNG)

Hi,
There is an error in the [build wiki](https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux) that I have corrected. We need to change the folder name from chromium-src to src and also modify "name" in .gclient file.
If there is an automatically generated src file after you run gclient sync. Please remove it and rename chromium-src to src then run gclient sync.
You can try it and if you meet any problems, please contact us in time.

**Comment by maheshpalkar** [comment]
> > > @maheshpalkar Thanks for trying WebNN examples! Are you using WebNN builds built from [otcshare/chromium-src](https://github.com/otcshare/chromium-src)? Also please try [How to build chromium on Linux](https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux) and [Run Chromium builds with WebNN API](https://github.com/intel/webml-polyfill/wiki/How-to-Run-Chromium-builds-with-WebNN-API).
> > > @Christywl
> > > Hi,
> > > Thanks for your reply.
> > > I had tried to install[ chromium repo using the mentioned steps](https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux). But while doing client sync I have faced following error
> > > FileNotFoundError: [Errno 2] No such file or directory: '/chromium_webml/src/buildtools/third_party/libc++abi/trunk'
> > 
> > 
> > I have found that while building some files are missing, so it is throwing error.
> > I have attached the screenshot for the missing trunk file.
> > ![webnn_error2](https://user-images.githubusercontent.com/65035270/81789528-bd438680-9521-11ea-808c-ffd0c04d2617.PNG)
> 
> Hi,
> There is an error in the [build wiki](https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux) that I have corrected. We need to change the folder name from chromium-src to src and also modify "name" in .gclient file.
> If there is an automatically generated src file after you run gclient sync. Please remove it and rename chromium-src to src then run gclient sync.
> You can try it and if you meet any problems, please contact us in time.

Hi,
The build is working fine and now WebNN API is enabled.
Thank you.

**Comment by miaobin** [comment]
@maheshpalkar That's great and thanks for trying WebNN examples!
Close this issue.

**Comment by ibelem** [comment]
@maheshpalkar Awesome, thank you for trying WebNN API, please let us know if you have more questions. :)
