### ISSUE TITLE
[DML] fail to run DirectML on NVIDIA graphic with Chromium M79

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1236]
**Test Env:**
Chromium Version: nightly build  79.0.3917.0(2e4d91c)
Platform: Windows
GPU: NVIDIA GeForce RTX 2080(26.21.14.4587)

**Expected Result:**
DirectML should work on NVIDIA graphic with Chromium M79.

**Actual Result:**
Failed to run DirectML on NVIDIA graphic with Chromium M79. 
<img width="901" alt="dml" src="https://user-images.githubusercontent.com/20039821/81630326-dcfe8000-9437-11ea-994d-603618ea3cd4.png">

But _**DML worked on NVIDIA graphic with Chromium M75**_.

**How to Reproduce:**
1. launch chromium with the argument '--use-dml'
2. visit https://intel.github.io/webml-polyfill/examples/image_classification
3. select `SUSTAINED_SPEED`
4. select one model

**Comment by fujunwei** [comment]
Thanks @Christywl .

**Comment by Christywl** [comment]
This issue was fixed with https://github.com/otcshare/chromium-src/commit/d3768f3e29f1f0aa6eb62c2d15899e5be34b7f6f. But found another issue #1240.
