### ISSUE TITLE
[WASM] memory issue occurs for WASM(TF.js) backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1258]
**Test Env:**
webml-polyfill commit: https://github.com/intel/webml-polyfill/commit/a58f9f5340ca87eca4cda18db019f42752317f9e
Platforms: all

**Expected Result:**
No memory issue.

**Actual Result:**
memory issue occurs for WASM(TF.js) backend:
<img width="948" alt="wasm-1" src="https://user-images.githubusercontent.com/20039821/83390963-57ae3000-a425-11ea-8622-be07d28f006e.png">
<img width="949" alt="wasm-2" src="https://user-images.githubusercontent.com/20039821/83390971-5bda4d80-a425-11ea-9440-229fde0feb4b.png">

**_Notes: In this case, all models can't be ran, need restart Chromium to continue the testing when meeting this issue._**

**How to Reproduce:**
1. Setup server with commit https://github.com/intel/webml-polyfill/commit/a58f9f5340ca87eca4cda18db019f42752317f9e
2. launch chrome or chromium(disable webml)
3. Visit http://localhost:8080/examples/image_classification
4. Switch models between ResNet50 v1(ONNX) and ResNet50 v2(ONNX) for several times (larger models usually meet this issue)

**Comment by akineeic** [comment]
This issue may caused by that  I didn‘t  free the variables created in the wasm module, I'll create a PR to fix that.

**Comment by ibelem** [comment]
@Christywl Could you please verify this issue? Thanks

**Comment by Christywl** [comment]
This issue has been fixed with commit https://github.com/intel/webml-polyfill/commit/58db335267a9c1232efee0282e01cc4f11f614d7.
