### ISSUE TITLE
[test] Support test automation for examples

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#126]
1. Support automation testing under ../examples
2. Platform: Mac, Android, Windows

Based on https://github.com/GoogleChrome/puppeteer/issues/2957, Puppeteer still doesn't support Android, we need to use WebDriver instead for the automation solution.

**Comment by BruceDai** [comment]
Currently we have enabled automation test tool to support Linux and MacOS platform.
We also new implemented to support BNNS and MPS backend on MacOS platform.
For Android and Windows platforms, use #172 to track.
Close it.
