### ISSUE TITLE
[GNA] fail to run examples for GNA backend with the latest builds

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#1266]
**Test Env:**
Chromium commit: https://github.com/otcshare/chromium-src/commit/bf3bd893b5aed9e84fde08ff501dca09eb9357a1
Platform: Windows

**Actual Result:**
fail to run examples for GNA backend with the latest builds:
`[2924:8868:0610/135905.687:ERROR:execution_impl_ie.cc(97)] [IE] exception Cannot find plugin to use: Tried load plugin : GNAPlugin for device GNA,  error: Plugin GNAPlugin cannot be loaded: cannot load plugin: GNAPlugin from : Cannot load library 'GNAPlugin.dll': 126 from cwd: <build_dir>\bf3bd89\win_x64_SUCCEED\Chrome-bin\79.0.3917.0, skipping`

It works fine on https://github.com/otcshare/chromium-src/commit/d3768f3e29f1f0aa6eb62c2d15899e5be34b7f6f

**How to Reproduce:**

1. Install the latest build, and launch it with `--use-inference-engine`
2. Run Speech Recognition example
3. Select `ULTRA_LOW_POWER`

**Comment by fujunwei** [comment]
There is a workaround with `set "PATH=\path\to\Chrome-bin\79.0.3917.0;%PATH%"`, i confuse `MKLDNNPlugin.dll/CLDNNPlugin.dll` can be found because they are in the same directory.
