### ISSUE TITLE
[test] Add CI with WASM backendfor webml-polyfill project

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#127]
After submitting PRs in webml-polyfill repo, CI is needed for verifying the quality of the new codes. 

1. Add Unit/CTS Tests in CI
2. Node.js + Travis CI
3. Add examples automation in CI when https://github.com/intel/webml-polyfill/issues/126 is resolved.
4. Add buliding/status badge ![CI badge](https://img.shields.io/travis/USER/REPO.svg) in README.md

Links:
- Travis CI .yml sample: https://gist.github.com/ibelem/330762849f3023bbfefa5e53b8ed20a1 
- https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode

**Comment by BruceDai** [comment]
In processing, currently we met webdriver installation failure by npm , we will low its priority, move to September release milestone.

**Comment by BruceDai** [comment]
PRs #292  #295 to add CI for testing on Linux / Mac OS with WASM backend have been landed, we are working on WebGL2 backend

**Comment by BruceDai** [comment]
We have enabled CI with WASM, close it. Next we will resolve https://github.com/intel/webml-polyfill/issues/309 .
