### ISSUE TITLE
[Chromium] Implement DirectML backend for Windows

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#13]
![37130031-b1ea8b14-22bc-11e8-844c-a276a063c94e](https://user-images.githubusercontent.com/1531742/38066877-8db40794-333c-11e8-9ea2-c3460d9e0d77.PNG)

screenshot of [Windows Developer Day on March 7](https://developer.microsoft.com/en-us/windows/projects/campaigns/windows-developer-day).

**Comment by huningxin** [comment]
https://docs.microsoft.com/en-us/windows/desktop/direct3d12/dml

**Comment by ibelem** [comment]
@fujunwei I think we can close this issue now. :)
