### ISSUE TITLE
[WASM] Check if TF.js can be upgraded to 2.0 in WASM backend

### ISSUE THREAD

**Issue by akineeic** [intel/webml-polyfill#1313]

**Comment by NALLEIN** [comment]
Upgrade Tensorflow.js to the latest 2.0.1 version, it should be noted that Tensorflow.js has separated `tfjs-backend-webgl` from `tfjs-core`
```
    "@tensorflow/tfjs-backend-wasm": "2.0.1",
    "@tensorflow/tfjs-backend-webgl": "2.0.1",
    "@tensorflow/tfjs-core": "2.0.1",
```
The RegressionChecker test results are as follows:
![image](https://raw.githubusercontent.com/NALLEIN/MarkdownFigures/master/RegressionChecker.png)
No regression occurs, and the model in the example can run normally.

**Comment by ibelem** [comment]
Good to know, could you please submit a PR for upgrading the backends? @NALLEIN Thanks!
