### ISSUE TITLE
[Example] Semantc Segmentation - Incorrect colorized person with OpenCV.js

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#1336]
Rero Steps:
1. Visit http://127.0.0.1/examples/semantic_segmentation/?b=WASM&m=opt_deeplabv3_mnv2_224&s=camera&d=0&f=OpenCV.js or http://127.0.0.1/examples/semantic_segmentation/?b=Threads%20SIMD&m=opt_deeplabv3_mnv2_224&s=camera&d=0&f=OpenCV.js
2. Check the colorized person

Actual Result:
The colorized area is not correct.

![ss_opencv](https://user-images.githubusercontent.com/5017359/90489432-dd619200-e16f-11ea-9562-274186d5873a.png)

**Comment by BruceDai** [comment]
@ibelem I have fixed this issue, pr will be submitted soon, thanks.
