### ISSUE TITLE
Reduce file size of OpenCV.js when build the file with configs

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#1348]
The file size of OpenCV.js is 8.1MB (Wasm) and 9.0MB (Threads+SIMD) which is too huge, there should be some parameters to use to reduce the file size, we only need a deep learning module. 

We could try to change

`white_list = makeWhiteList([core, imgproc, objdetect, video, dnn, features2d, photo, aruco, calib3d])`

to

`white_list = makeWhiteList([core, dnn])`

in

https://github.com/opencv/opencv/blob/master/platforms/js/opencv_js.config.py 

then follow https://docs.opencv.org/4.3.0/d4/da1/tutorial_js_setup.html to build OpenCV.js.

Based on https://github.com/intel/webml-polyfill/pull/1326, @akineeic built the files with emscripten 1.39.16 and opencv 4.3.0.

@BruceDai or @miaobin please try it when you have time and compare the file sizes.

**Comment by ashishpapanai** [comment]
Are contributions from outside the organization also accepted?
I would like to work on this issue.

**Comment by huningxin** [comment]
> Are contributions from outside the organization also accepted?

Yes. The contributions would be highly appreciated. 

> I would like to work on this issue.

Thanks in advance. Feel free to send out the pull request and link to this issue.
