### ISSUE TITLE
sw.js reports "ReferenceError: evt is not defined"

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#1366]
The error happens at https://github.com/intel/webml-polyfill/blob/gh-pages/sw.js#L16

This issue breaks https://intel.github.io/webml-polyfill/examples/index.html.

**Comment by BruceDai** [comment]
@huningxin What's your test environment? We couldn't reproduce it.

**Comment by huningxin** [comment]
Is your sw.js the latest version ([v37](https://github.com/intel/webml-polyfill/blob/gh-pages/sw.js#L1))?

**Comment by BruceDai** [comment]
@huningxin Thanks for you reminding. @ibelem helped fix it.
