### ISSUE TITLE
Android P NN API update

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#137]
https://developer.android.com/about/versions/pie/android-9.0 

> Android 9 features and APIs
> 
> Neural Networks API 1.1
> The Neural Networks API was introduced in Android 8.1 (API level 27) to accelerate on-device machine learning on Android. Android 9 expands and improves the API, adding support for nine new operations.

**Comment by fujunwei** [comment]
`ANeuralNetworksModel_relaxComputationFloat32toFloat16` allow is 'true' indicates ANEURALNETWORKS_TENSOR_FLOAT32 may be calculated with range and/or precision as low as that of the IEEE 754 16-bit floating point format.
@BruceDai @pinzhenx  Could you please help to verify performance after calling the API.

**Comment by fujunwei** [comment]
`ANEURALNETWORKS_BATCH_TO_SPACE_ND` This operation reshapes the batch dimension (dimension 0) into M + 1 dimensions of shape block_shape + [batch], interleaves these blocks back into the grid defined by the spatial dimensions [1, ..., M], to obtain a result with the same rank as the input.

**Comment by fujunwei** [comment]
`ANEURALNETWORKS_DIV` Element-wise division of two tensors. Takes two input tensors of identical OperandCode and compatible dimensions. The output is the result of dividing the first input tensor by the second, optionally modified by an activation function.

**Comment by fujunwei** [comment]
`ANEURALNETWORKS_MEAN`

Computes the mean of elements across dimensions of a tensor.

Reduces the input tensor along the given dimensions to reduce. Unless keep_dims is true, the rank of the tensor is reduced by 1 for each entry in axis. If keep_dims is true, the reduced dimensions are retained with length 1.

If dimensions to reduce have no entries, all dimensions are reduced, and a tensor with a single element is returned.

**Comment by fujunwei** [comment]
`ANEURALNETWORKS_PAD` This operation pads a tensor according to the specified paddings.

Inputs:

0: An n-D tensor, specifying the tensor to be padded.
1: A 2-D Tensor of ANEURALNETWORKS_TENSOR_INT32, the paddings for each spatial dimension of the input tensor. The shape of the tensor must be {rank(input0), 2}. padding[i, 0] specifies the number of elements to be padded in the front of dimension i. padding[i, 1] specifies the number of elements to be padded after the end of dimension i.

Outputs:

0: A tensor of the same OperandCode as input0. The output tensor has the same rank as input0, and each dimension of the output tensor has the same size as the corresponding dimension of the input tensor plus the size of the padding: output0.dimension[i] = padding[i, 0] + input0.dimension[i] + padding[i, 1]

**Comment by fujunwei** [comment]
`ANEURALNETWORKS_SPACE_TO_BATCH_ND`
This operation divides "spatial" dimensions [1, ..., M] of the input into a grid of blocks of shape block_shape, and interleaves these blocks with the "batch" dimension (0) such that in the output, the spatial dimensions [1, ..., M] correspond to the position within the grid, and the batch dimension combines both the position within a spatial block and the original batch position. Prior to division into blocks, the spatial dimensions of the input are optionally zero padded according to paddings.

**Comment by fujunwei** [comment]
`ANEURALNETWORKS_SQUEEZE`
Removes dimensions of size 1 from the shape of a tensor.

Given a tensor input, this operation returns a tensor of the same OperandCode with all dimensions of size 1 removed. If you don't want to remove all size 1 dimensions, you can remove specific size 1 dimensions by specifying the axes (input1).

**Comment by fujunwei** [comment]
`ANEURALNETWORKS_STRIDED_SLICE`
Extracts a strided slice of a tensor.

Roughly speaking, this op extracts a slice of size (end - begin) / stride from the given input tensor. Starting at the location specified by begin the slice continues by adding stride to the index until all dimensions are not less than end. Note that a stride can be negative, which causes a reverse slice.

**Comment by fujunwei** [comment]
`ANEURALNETWORKS_SUB`
Element-wise subtraction of two tensors.

Takes two input tensors of identical OperandCode and compatible dimensions. The output is the result of subtracting the second input tensor from the first one, optionally modified by an activation function.

**Comment by fujunwei** [comment]
`ANEURALNETWORKS_TRANSPOSE`
Transposes the input tensor, permuting the dimensions according to the perm tensor.

The returned tensor's dimension i corresponds to the input dimension perm[i]. If perm is not given, it is set to (n-1...0), where n is the rank of the input tensor. Hence by default, this operation performs a regular matrix transpose on 2-D input Tensors.

**Comment by fujunwei** [comment]
You can also get detailed new API in https://developer.android.com/ndk/reference/group/neural-networks with searching `API level 28`.
