### ISSUE TITLE
[WebGL2] An error occurs when the tensor is 1 dimension for Reshape operation

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#138]
**Test Env:**
Chromium Version : nightly build 70.0.3503.0 (revision 3dd7088)
OS : Mac OS
webml-polyfill: commit 777b85f

**Expected Result:**
Tests should pass.

**Actual Result:**
 An error occurs when the tensor is 1 dimension for Reshape operation
`TypeError: Reduce of empty array with no initial value`

**How to reproduce:**
1. Launch chromium and disable the WebML
2. Run tests: access to https://brucedai.github.io/nt/test/cts-all.html?backend=webgl2
3. Check the tests: 
- check result for Reshape example
- check result for Reshape weights as inputs example

```
async function() {
    let model = await nn.createModel(options);
    let operandIndex = 0;
    let op1_value = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    let op3_expect = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    let type0 = {type: nn.TENSOR_FLOAT32, dimensions: [1, 1, 3, 3]};
    let type0_length = product(type0.dimensions);
    let type2 = {type: nn.TENSOR_FLOAT32, dimensions: [9]};
    let type2_length = product(type2.dimensions);
    let type1 = {type: nn.TENSOR_INT32, dimensions: [1]};
    let type1_length = product(type1.dimensions);
    let op1 = operandIndex++;
    model.addOperand(type0);
    let op2 = operandIndex++;
    model.addOperand(type1);
    let op3 = operandIndex++;
    model.addOperand(type2);
    model.setOperandValue(op2, new Int32Array([-1]));
    model.addOperation(nn.RESHAPE, [op1, op2], [op3]);
    model.identifyInputsAndOutputs([op1], [op3]);
    await model.finish();
    let compilation = await model.createCompilation();
    compilation.setPreference(nn.PREFER_FAST_SINGLE_ANSWER);
    await compilation.finish();
    let execution = await compilation.createExecution();
    let op1_input = new Float32Array(op1_value);
    execution.setInput(0, op1_input);
    let op3_output = new Float32Array(type2_length);
    execution.setOutput(0, op3_output);
    await execution.startCompute();
    for (let i = 0; i < type2_length; ++i) {
      assert.isTrue(almostEqualCTS(op3_output[i], op3_expect[i]));
    }
  }

```

**Comment by Christywl** [comment]
Close this issue since the test case with special value -1 has been removed.

**Comment by Wenzhao-Xiang** [comment]
I think this case is OK because the special value "-1" exists in targetShape. The test case in #110 is not OK mainly because the special value "-1" appears in the dimension of outputShape, contrary to the fact that this API requires a certain tensor shape when init. And I think this issue still exist. @Christywl @BruceDai
