### ISSUE TITLE
[MPS] 'Neural Network service unavailable' error happened when running CTS tests on Mac

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#149]
**Test Env:**
Chromium Version : nightly build 70.0.3503.0 (public/webml/nightly/**_007f215_**/)
OS : Mac OS
webml-polyfill: commit 777b85f

**Expected Result:**
Test should pass.

**Actual Result:**
`NotSupportedError: Neural Network service unavailable.`

**How to Reproduce:**
1. Launch chromium and enable the WebML
2. Access to https://brucedai.github.io/nt/test/cts-all.html?backend=mps

Most tests failed due to this issue:
<img width="1280" alt="screen shot 2018-08-16 at 3 36 34 pm" src="https://user-images.githubusercontent.com/20039821/44195369-66055c00-a16b-11e8-959c-5e379a9a1e09.png">

**Comment by Christywl** [comment]
Sometimes, I also met the same issue when running CTS tests with BNNS backend on Mac:
<img width="1280" alt="screen shot 2018-08-17 at 9 43 50 am" src="https://user-images.githubusercontent.com/20039821/44244642-7e2ab900-a207-11e8-83fd-410beea20939.png">

**Comment by ibelem** [comment]
Re-assign to @sunlin-link as it's MPS issue

**Comment by sunlin-link** [comment]
Same with https://github.com/intel/webml-polyfill/issues/171.
Some test cases crashed and broke the neural network service

**Comment by sunlin-link** [comment]
@Christywl Fixed. Please verify

**Comment by Christywl** [comment]
Same as #171, this issue was still reproduced sometimes when the chromium crashed. Wait for the further fix in #171.
