### ISSUE TITLE
[BNNS] 'InvalidStateError: startComputefails: 4' error happened for AVERAGE_POOL_2D and MAX_POOL_2D operations

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#150]
**Test Env:**
Chromium Version : nightly build 70.0.3503.0 (public/webml/nightly/**_007f215_**/)
OS : Mac OS
webml-polyfill: commit 777b85f

**Expected Result:**
Test should pass.

**Actual Result:**
`InvalidStateError: startComputefails: 4`

**How to Reproduce:**
1. Launch chromium and enable the WebML
2. Access to https://brucedai.github.io/nt/test/cts-all.html?backend=bnns
3. Check the tests: 
```
check result for Avg pool float example/2
check result for Avg pool float example/4
check result for Max pool float example/2
check result for Max pool float example/3
```

**Comment by lisa0314** [comment]
@BruceDai @huningxin , when I run these sample in Xcode, there shows a error message - "POOLING: invalid kernel dimensions: max supported kernel width/height is 16". But the document doesn't mention this restriction for kernel dimension.

**Comment by Christywl** [comment]
This issue wan't reproduced from Chromium nightly build **4dc45a2**.

**Comment by Christywl** [comment]
Close this issue since the error can't reproduce on several builds. The tests failed due to #207.
