### ISSUE TITLE
[BNNS] An error happened and the testing was unstable for SOFTMAX operation on Mac

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#152]
**Test Env:**
Chromium Version : nightly build 70.0.3503.0 (public/webml/nightly/**_007f215_**/)
OS : Mac OS
webml-polyfill: commit 777b85f

**Expected Result:**
Test should pass.

**Actual Result:**
Ran SOFTMAX tests of CTS, the testing was unstable, and got the different results when running it several times.
![image](https://user-images.githubusercontent.com/20039821/44244399-5a1aa800-a206-11e8-9482-164c9ebd2f72.png)

**How to Reproduce:**
1. Launch chromium and enable the WebML
2. Access to https://brucedai.github.io/nt/test/cts-all.html?backend=bnns
3. Check the tests: 
```
check result for Softmax float example/1 
check result for Softmax float example/2
```
4. Run several times and check the results

**Comment by lisa0314** [comment]
@Christywl Please help to verify.

**Comment by Christywl** [comment]
Verified this with the Chromium nightly build **41afa08**, the unstable issue was fixed.
