### ISSUE TITLE
[Chromium] build error on macOS

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#155]
commit https://github.com/otcshare/chromium-src/commit/4dc45a2e8b0e1fe2879893b303bbbce5728296c6 build error on macOS

**Comment by huningxin** [comment]
Fixed by https://github.com/otcshare/chromium-src/pull/15 merge, @BruceDai , please help verify. Thanks!

**Comment by Christywl** [comment]
The chromium nightly build(279911e) on Mac works.
