### ISSUE TITLE
[MPS] 'InvalidStateError: startCompute fails: 4' error happened for DEPTHWISE_CONV_2D operation with MPS backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#162]
**Test Env:**
Chromium Version : nightly build 70.0.3503.0 (**public/webml/nightly/50746ae/**)
OS : Mac OS
webml-polyfill: commit 801b0d7

**Expected Result:**
Test should pass.

**Actual Result:**
- check result for Depthwise conv2d float large 2 weights as inputs example
`NotSupportedError: Execution is not implemented.`

**How to Reproduce:**
1. Launch chromium and enable the WebML
2. Run the test: https://brucedai.github.io/nt/test/depthwise-startcompute-issue.html?backend=mps

**Comment by Christywl** [comment]
The error message changed on the Chromium nightly build **_313c1c2_**:
`InvalidStateError: startCompute fails: 4`

**Comment by fujunwei** [comment]
outputFeatureChannels in MPS depthwise convolution descriptor must be multiplie of inFeatureChannels, but the outputFeatureChannels  is 4, inFeatureChannels is 3 in the test case.
And [NNAPI said the output has depth_out = depth_in * depth_multiplier channels](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a2b49a44b7ebba243fad01556c1f0392e), however it support the test case that keep remain channel value.

The PR of refactoring relative code is https://github.com/otcshare/chromium-src/pull/57.

**Comment by fujunwei** [comment]
It also can add a concatenation operation to append remain channels if it need to be supported.

**Comment by Christywl** [comment]
This issue wasn't reproduced after https://github.com/otcshare/chromium-src/pull/57/commits/3e5cbb963ffe52def3c34a88f00ad7247ba99c5f, now the tests failed due to #58, so close it.
