### ISSUE TITLE
[Example] MobileNet example doesn't handle error of BNNS backend

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#163]
Chromium version: https://github.com/otcshare/chromium-src/commit/d3994c9c0993eca66865d8812867d49f998460f4

MobileNet compilation preference as `PREFER_FAST_SINGLE_ANSWER`

Expected result:
Fall back to WASM backend if BNNS doesn't support MobileNet

Actual result:
Example UI hangs on setting...

**Comment by BruceDai** [comment]
@huningxin Currently, MobileNet /SSD MobileNet/PoseNet all don't support BNNS backend.  How about switch to use MPS backend when setting preference as PREFER_FAST_SINGLE_ANSWER? 
I use this above solution in [PR#170](https://github.com/intel/webml-polyfill/pull/170).

**Comment by BruceDai** [comment]
[PR#170](https://github.com/intel/webml-polyfill/pull/170) has landed, close it.

**Comment by BruceDai** [comment]
@Christywl please help verify it.

**Comment by Christywl** [comment]
With Chromium nightly build **8d111d1** on Mac:

The examples(PoseNet/MobileNet/SDD MobileNet) fall back to WASM with BNNS backend and show 'Failed to setup WebML backend'.
