### ISSUE TITLE
[Example][MPS] MobileNet example doesn't work with PREFER_SUSTAINED_SPEED

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#164]
Chromium version: https://github.com/otcshare/chromium-src/commit/d3994c9c0993eca66865d8812867d49f998460f4

MobileNet compilation preference as `PREFER_SUSTAINED_SPEED` which runs by MPS

Expected result:
It should work with MPS backend.

Actual result:
Example UI hangs on setting...
Open console, it shows
```
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
Uncaught (in promise) DOMException: Execution is not implemented.
```

**Comment by huningxin** [comment]
I suspect this issue happens after BNNS code merged. It works on https://github.com/otcshare/chromium-src/commit/dc3da1fd9ebe6a8f1a3f7a74e9dc0d66e1b97148

@lisa0314 , please take a look.

**Comment by BruceDai** [comment]
This issue is not reproduced by the latest chromium 41afa08, close it.

**Comment by sunlin-link** [comment]
This bug is regression by https://github.com/otcshare/chromium-src/pull/11
