### ISSUE TITLE
[Example][MPS] Squeezenet example doesn't work with MPS backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#173]
**Test Env:**
Chromium Version : nightly build 70.0.3503.0 **1fd54ed**
OS : Mac OS

**Expected Result:**
Squeezenet example should work.

**Actual Result:**
Squeezenet example doesn't work with MPS backend.
`DOMException: Execution is not implemented.`

**How to Reproduce:**
1. Launch chromium and enable the WebML
2. Open https://brucedai.github.io/nt/benchmark/index.html, choose Squeezenet and MPS

**Comment by huningxin** [comment]
Thanks for reporting! This is a regression. Could we identify which version is the last working one?

**Comment by Christywl** [comment]
The last working version is [50746ae](http://powerbuilder.sh.intel.com/public/webml/nightly/50746ae/mac_x64_SUCCEED/).

**Comment by huningxin** [comment]
So the earliest one has this regression is https://github.com/otcshare/chromium-src/commit/4dc45a2e8b0e1fe2879893b303bbbce5728296c6. Correct?

If that is true, there are two PRs merged between them:
https://github.com/otcshare/chromium-src/pull/16 (@fujunwei) 
https://github.com/otcshare/chromium-src/pull/11 (@sunlin-link)

@fujunwei @sunlin-link , could you please take a look? I suspect https://github.com/otcshare/chromium-src/pull/11 cause the issue.

**Comment by Christywl** [comment]
Yes, this issue happens from the nightly build **4dc45a2**.

**Comment by fujunwei** [comment]
Maybe @sunlin-link 's [PR-25](https://github.com/otcshare/chromium-src/pull/25) is fixing this issue, please add reference in commit log if it's.

**Comment by Christywl** [comment]
Mobilenet example has the same issue. There was #164, so I didn't report a new issue.

**Comment by BruceDai** [comment]
This issue is not reproduced by latest chromium 41afa08, close it.

**Comment by sunlin-link** [comment]
This bug is regression by https://github.com/otcshare/chromium-src/pull/11
