### ISSUE TITLE
[BNNS] Crash happened when attempting to do extra actions for the finished model with BNNS backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#174]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 **279911e** **1fd54ed**
OS : Mac OS X 10.13.6
WebML Polyfill: [bb00e86](https://github.com/intel/webml-polyfill/commit/bb00e8686af5fd8bd525e7b9090c36cb6b1130f2)

**Expected Result:**
No crash happens

**Actual Result:**
Crash happened when attempting to do extra actions for the finished model with BNNS backend
```
Received signal 11 SEGV_MAPERR 00000000000c
 [0x0001125bc2ec]
 [0x0001125bc1e1]
 [0x7fff51373f5a]
 [0x7ffee17b99d8]
 [0x0001160a298f]
 [0x000111704e18]
 [0x00011170433d]
 [0x000111703a2b]
 [0x000111edd0ae]
 [0x002a2d7086a6]
 [0x002a2d7086a6]
 [0x000111e4c046]
 [0x002a2d7086a6]
 [0x000111e4c046]
[end of stack trace]
```

**How to reproduce:**
1.Download and install Chromium
2.Launch Chromium
3.Run the tests: https://brucedai.github.io/nt/test/model.html?backend=bnns

_This issue happened before and was fixed on the nightly build 81edd55._

**Comment by sunlin-link** [comment]
@Christywl Fixed. Please verify

**Comment by Christywl** [comment]
Verified it with the chromium nightly build 3677b5f, this issue wasn't reproduced.
