### ISSUE TITLE
[Linux] enable clDNN backend on Linux

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#179]

**Comment by fujunwei** [comment]
@BruceDai  please help to verify, thanks.

**Comment by BruceDai** [comment]
@fujunwei there isn't Chromium build for Linux platform in latest nightly build, please check build server, thanks

**Comment by fujunwei** [comment]
Trigger a new version in http://powerbuilder.sh.intel.com/public/webml/nightly/3677b5f/.
