### ISSUE TITLE
[Examples][win] SqueezeNet doesn't work on Windows

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#183]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**41afa08**)
OS: Windows 10 Pro(Dell XPS 13)

**Expected Result:**
SqueezeNet works on Windows.

**Actual Result:**
SqueezeNet doesn't work on Windows:

`DOMException: finishfails: 5`

<img width="960" alt="squeezenet" src="https://user-images.githubusercontent.com/20039821/45067369-c1927d80-b077-11e8-945a-98f1fe3f3aaf.png">

**How to Reproduce:**
1. Run SqueezeNet example: https://brucedai.github.io/nt/examples/squeezenet/index.html
2. Select WebML backend
3. Open Devtools, and check the console log

**Comment by huningxin** [comment]
Thanks for reporting this issue. Should be fixed by https://github.com/otcshare/chromium-src/pull/30 which is merged. Close this one. And please help verify. @Christywl

**Comment by Christywl** [comment]
Verified this with the Chromium nightly build **8d111d1**, this issue wasn't reproduced.
