### ISSUE TITLE
[benchmark] WASM data for WebML workloads

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#184]
Liftoff is enabled by default in V8 v6.9 (Chrome 69), and can be controlled explicitly with the --liftoff/--no-liftoff and chrome://flags/#enable-webassembly-baseline flags in each, respectively.

> Liftoff: the new baseline compiler for WebAssembly in v8. 
> https://v8project.blogspot.com/2018/08/liftoff.html

We need to understand the performance improvement for ML use cases as WASM is used in our polyfill, WebDNN and OpenCV.js for ML workload. Collect latest data is necessary.

**Comment by ibelem** [comment]
@Christywl the stable 69.0.3497.81 (Official Build) has been released, please start the testing when you have time and add comparison report.

**Comment by Christywl** [comment]
Benchmark data with Chrome stable on Mac and Android: 
**Test URL:** https://brucedai.github.io/nt/benchmark/index.html 
**Iterations:** 1(warming up) +200

**MacBook Pro(10.13.6):**

Model | Backend | 68.0.3440.106 |  69.0.3497.91
-- | -- | -- | --
MobileNet | WASM | 503.96+-6.87 | 486.94+-4.11 
SqueezeNet | WASM | 298.77+-5.56 | 284.27+-3.46 

**Google Pixel 2(8.1.0):**

Model | Backend | 68.0.3440.91 |  69.0.3497.91
-- | -- | -- | --
MobileNet | WASM | 1731.64+-11.20 | 1570.34+-6.96
SqueezeNet | WASM | 1017.54+-7.42 | 919.45+-7.09

**Comment by huningxin** [comment]
Thanks for the results! As liftoff improves the code generation, it would be good to measure the improvement of warming up time as well. @BruceDai

**Comment by BruceDai** [comment]
From collecting data with counting warming up time in, this results are similar as above.  Collected data, so close it.
