### ISSUE TITLE
[Examples][Android] Crash happened when running SqueezeNet example with WebGL2 backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#185]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**8d111d1**)
Device: Google Pixel 2

**Expected Result:**
SqueezeNet works on Android.

**Actual Result:**
Chromium crashed when running SqueezeNet example with WebGL2 backend, and the result: 
![screenshot_20180906-162706](https://user-images.githubusercontent.com/20039821/45144894-f6c2db00-b1f1-11e8-8a2e-c517d203ef6f.png)

![image](https://user-images.githubusercontent.com/20039821/45144534-0392ff00-b1f1-11e8-9df6-41f1f92528fa.png)

[squeezenet_webgl2.log](https://github.com/intel/webml-polyfill/files/2356149/squeezenet_webgl2.log)

**How to Reproduce:**
1. Visit https://brucedai.github.io/nt/benchmark/index.html
2. Select WebGL2 backend and SqueezeNet 
3. Set Iterations: `1(warming up) +200`

Notes:
1. If Iterations are <=100, the example works fine. When Iterations are about >140, crash occurs.
2. This issue doesn't happen on Huawei P20 Pro.

**Comment by GreyZzzzzzXh** [comment]
This is a memory leak on webgl2 backend, which results in the crash and inaccuracy of the benchmark.
Fixed by #262 , @Christywl ,please help verify, thanks!

**Comment by Christywl** [comment]
Verified this on Android, it can't reproduce.
