### ISSUE TITLE
Easier unit testing automation process for WebML PR Submission Criteria

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#187]
We need to provide easier unit testing automation process for WebML PR Submission Criteria:
1. Run native and polyfill unit tests with webdriver by switching webml flags
2. Maintain expected result data, provide automatic comparison results, highlight regression cases for developer

**Comment by BruceDai** [comment]
Currently this tool kit for Android/Mac OS/Linux platform is under testing, and would be delivered to developer side soon. 
And took kit for Windows platform is in developing.

**Comment by fujunwei** [comment]
Copy that, thanks.

**Comment by BruceDai** [comment]
@fujunwei @lisa0314 Please git pull latest [intel/webml-polyfill](https://github.com/intel/webml-polyfill/) code since [PR#293](https://github.com/intel/webml-polyfill/pull/293) has been landed to improve the performance of this tool kit and also update baseline test cases/result data, thanks
