### ISSUE TITLE
[BNNS] The actual outputs don't match the expected values for CONV_2D operation

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#191]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**8d111d1**)
Device: Mac Book Pro

**Expected Result:**
The test should pass.

**Actual Result:**
The actual outputs don't match the expected values.
For example:
- check result for Conv float large example
actual:
`[30.0, 66.0, 102.0, 138.0, 174.0, 210.0, 36.0, 81.0, 126.0, 171.0, 216.0, 261.0, 42.0, 96.0, 150.0, 204.0, 258.0, 312.0]`
expected:
`[30.0, 36.0, 42.0, 66.0, 81.0, 96.0, 102.0, 126.0, 150.0, 138.0, 171.0, 204.0, 174.0, 216.0, 258.0, 210.0, 261.0, 312.0]
`

**How to Reproduce:**
1. Launch chromium and enable WebML flag
2. Visit https://brucedai.github.io/nt/test/cts-all.html?backend=bnns
3. Check the failed tests:
- check result for Conv 3 h3 w2 same example-1
- check result for Conv 3 h3 w2 same example-2
- check result for Conv 3 h3 w2 same relu example-1
- check result for Conv 3 h3 w2 same relu example-2
- check result for Conv 3 h3 w2 same relu1 example-1
- check result for Conv 3 h3 w2 same relu1 example-2
- check result for Conv 3 h3 w2 same relu6 example-1
- check result for Conv 3 h3 w2 same relu6 example-2
- check result for Conv 3 h3 w2 valid example-1
- check result for Conv 3 h3 w2 valid example-2
- check result for Conv 3 h3 w2 valid relu example-1
- check result for Conv 3 h3 w2 valid relu example-2
- check result for Conv 3 h3 w2 valid relu1 example-1
- check result for Conv 3 h3 w2 valid relu1 example-2
- check result for Conv 3 h3 w2 valid relu6 example-1
- check result for Conv 3 h3 w2 valid relu6 example-2
- check result for Conv float large example
- check result for Conv float large relu example
- check result for Conv float large weights as inputs example
- check result for Conv float large weights as inputs relu example

**Comment by Christywl** [comment]
The tests still failed when running the tests separately. 
And updated the impacted tests in the description since more newly added tests failed for CONV_2D operation.

**Comment by lisa0314** [comment]
@Christywl this issue is related to this [PR](https://github.com/otcshare/chromium-src/pull/28). After this PR is merged, this issue will be solved.

**Comment by Christywl** [comment]
The PR https://github.com/otcshare/chromium-src/pull/28  was merged and the tests passed on nightly build 0ff81ee.
