### ISSUE TITLE
[Polyfill][WebGL] investigate to leverage TensorFlow.js core as WebGL backend implementation

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#199]

**Comment by GreyZzzzzzXh** [comment]
I create a simple plan in Google Drive and will document the results in the future.
https://docs.google.com/document/d/1cXmg76--76yky7ghfQPMTyEM0a6R9RIBm86v6y5DsyY/edit?usp=sharing
Welcome to add more content :)

**Comment by GreyZzzzzzXh** [comment]
Finished the backend based on tfjs-core, see https://github.com/GreyZzzzzzXh/webml-polyfill/tree/tfjs.

Result for **example/image_classification_tflite**:

inference time(ms) | WASM | WebGL2 | TFJS
-- | -- | -- | --
mobilenet_v1 | 351.4 | 65.3 | 19.8
mobilenet_v2 | 230.9 | 38.9 | 20.3
inception_v3 | 3073.9 | 902.1 | 420
squeezenet | 478.6 | 112.8 | 72.8

Faster than current backend.

Temporary steps for use: https://github.com/GreyZzzzzzXh/webml-polyfill/blob/tfjs/src/nn/tfjs/README.md
