### ISSUE TITLE
[Example][MobileNet] Update the README.md for MobileNet v1 and v2

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#202]
Please update the README.md of model (https://github.com/intel/webml-polyfill/blob/master/examples/mobilenet/model/README.md):
1. update the URL of v1 model to latest one
2. add the URL and steps of v2 model

**Comment by Wenzhao-Xiang** [comment]
@huningxin 
For new [Mobilenet_V1_1.0_224_Float](http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz) and [Mobilenet_V2_1.0_224_Float](http://download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224.tgz), there are not `label.txt` in the download file. Shuold I keep the old V1 model URL for a way to get `label.txt`?

**Comment by huningxin** [comment]
I think we can share the `label.txt` between models. And this task can be covered by https://github.com/intel/webml-polyfill/issues/220
