### ISSUE TITLE
[Linux] Document the steps of installing OpenVINO for chromium ml

### ISSUE THREAD

**Issue by fujunwei** [intel/webml-polyfill#217]
Current the documentation of [installing OpenVINO](https://software.intel.com/en-us/articles/OpenVINO-Install-Linux) is too complex for using clDNN, it can be simplified  two steps or add a new script in OpenVINI to merge those:

1, Install openvino sdk with sudo ./install.sh
2, Install openCL driver with cd /opt/intel/computer_vision_sdk/install_dependencies/ && ./install_NEO_OCL_driver.sh

It's better to be used in js exception if fail to load clDNN library.

**Comment by ibelem** [comment]
To do: Create it in wiki.

**Comment by fujunwei** [comment]
Done with https://github.com/otcshare/chromium-src/wiki/Steps-of-installing-OpenVINO-for-chromium-ml-on-Linux

**Comment by fujunwei** [comment]
Thanks, Done.
