### ISSUE TITLE
[Win][clDNN] Add is not supported on Windows

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#230]
Add operation is not supported on clDNN for windows. 

How to Reproduce:

- Visit https://brucedai.github.io/nt/testa/add.html

**Comment by BruceDai** [comment]
@huningxin PTAL, thanks

**Comment by huningxin** [comment]
@BruceDai , thanks for reporting this issue! This was introduced by upgrade clDNN to 0.8. I will fix that. It should fix #231 as well.

**Comment by huningxin** [comment]
Fixed. Please verify. @BruceDai
