### ISSUE TITLE
[clDNN] "InvalidStateError: fails: 4" occurs for DEPTHWISE_CONV_2D and SOFTMAX operations

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#243]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**48326a5**)
Platform: Windows(Dell XPS 13), Linux Ubuntu 16.04

**Expected Result:**
The test should pass.

**Actual Result:**
"InvalidStateError: fails: 4" occurs for DEPTHWISE_CONV_2D and SOFTMAX operations.

`InvalidStateError: fails: 4`

**How to Reproduce:**
1. Launch chromium and enable WebML flag
2. Visit https://brucedai.github.io/nt/test/cts-all.html

**Comment by huningxin** [comment]
@Christywl , could you please provide a set of failure test cases instead of cts-all?

**Comment by huningxin** [comment]
@ibelem , could you please confirm the onnx mobile issue? What are the reproduce steps? Thanks!

**Comment by Christywl** [comment]
@huningxin , please see the failure test cases in cts-all.html for this issue:

- [check result for Depthwise conv2d float example](https://github.com/BruceDai/nt/blob/master/test/cts/test/V1_0/depthwise_conv2d_float.js) 
- [check result for Depthwise conv2d float relu example](https://github.com/BruceDai/nt/blob/master/test/cts/test/V1_0_plus/depthwise_conv2d_float_relu.js)
- [check result for Depthwise conv2d float relu1 example](https://github.com/BruceDai/nt/blob/master/test/cts/test/V1_0_plus/depthwise_conv2d_float_relu1.js)
- [check result for Depthwise conv2d float relu6 example](https://github.com/BruceDai/nt/blob/master/test/cts/test/V1_0_plus/depthwise_conv2d_float_relu6.js)
- [check result for Depthwise conv2d float weights as inputs example](https://github.com/BruceDai/nt/blob/master/test/cts/test/V1_0/depthwise_conv2d_float_weights_as_inputs.js)
- [check result for Depthwise conv2d float weights as inputs relu example](https://github.com/BruceDai/nt/blob/master/test/cts/test/V1_0_plus/depthwise_conv2d_float_weights_as_inputs_relu.js)
- [check result for Depthwise conv2d float weights as inputs relu1 example](https://github.com/BruceDai/nt/blob/master/test/cts/test/V1_0_plus/depthwise_conv2d_float_weights_as_inputs_relu1.js)
- [check result for Depthwise conv2d float weights as inputs relu6 example](https://github.com/BruceDai/nt/blob/master/test/cts/test/V1_0_plus/depthwise_conv2d_float_weights_as_inputs_relu6.js)
- [check result for Softmax float example/1](https://github.com/BruceDai/nt/blob/master/test/cts/test/V1_0/softmax_float_1.js)

**Comment by pinzhenx** [comment]
__Results for onnx mobilenet__

![screenshot from 2018-11-27 16-19-08](https://user-images.githubusercontent.com/7313938/49068073-beff8880-f260-11e8-81c3-ee20fc293d0c.png)

As is shown above, the layer outputs diverge at `mobilenetv20_features_linearbottleneck0_relu1_fwd`, which is a fused node of depthwise convolution.

__Test Env__

Chromium
Platform: Linux Ubuntu 16.04


__How to reproduce__

Link: https://pinzhenx.github.io/webml-demo/examples/image_classification_onnx/testlayer?model=mobilenetv2-1.0
Set log level to `Verbose`, mute `Info` & `Warnings`

**Comment by Christywl** [comment]
On the nightly build efb0f90, this issue wasn't reproduced. The tests still failed due to #565 and #244. Please see the details in #565 and #244, so close this issue.
