### ISSUE TITLE
[Doc] create wiki page for required ops of ONNX models

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#252]
Create a wiki page to capture the required ops of ONNX image classification models (https://github.com/onnx/models#image_classification).

Please refer to TFLite one: https://github.com/intel/webml-polyfill/wiki/Tflite-Model-for-Image-Classification-and-the-Ops-They-Include. Thanks!

**Comment by pinzhenx** [comment]
Done.
Please refer to [Onnx Models](https://github.com/intel/webml-polyfill/wiki/Onnx-Model-for-Image-Classification-and-the-Ops-They-Include)
