### ISSUE TITLE
[MPS] fails to run Inception-v3

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#255]
To reproduce this:
1. git clone https://github.com/huningxin/webml-polyfill/tree/inception_v3/examples/Inception_V3
2. download inception v3 model by following https://github.com/huningxin/webml-polyfill/tree/inception_v3/examples/Inception_V3/model
3. launch Chromium to run

The result will be compilation error.

The root case is current MPS implementation doesn't handle connected concatenation ops as following diagram shows

<img width="1095" alt="screen shot 2018-10-17 at 10 13 46 am" src="https://user-images.githubusercontent.com/1005673/47057473-84331b00-d1f3-11e8-86d1-3c70d6470617.png">

**Comment by huningxin** [comment]
> To reproduce this:
> 
> 1. git clone https://github.com/huningxin/webml-polyfill/tree/inception_v3/examples/Inception_V3
> 2. download inception v3 model by following https://github.com/huningxin/webml-polyfill/tree/inception_v3/examples/Inception_V3/model
> 3. launch Chromium to run
> 
> The result will be compilation error.

@ibelem

**Comment by Christywl** [comment]
Verified this on nightly build b7ce158, this example works.
