### ISSUE TITLE
[BNNS] BNNS backend doesn't work on the Chromium build 2338ea6

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#258]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**2338ea6**)
Platform: Mac OS 

**Expected Result:**
The tests or example should work with BNNS backend.

**Actual Result:**
BNNS backend doesn't work on Chromium build **2338ea6**

**How to Reproduce:**
1. Visit https://brucedai.github.io/nt/examples/squeezenet/index.html?prefer=fast:
   `The example switches to WASM with the error message 'Failed to setup WebML backend'`
2. Visit https://brucedai.github.io/nt/testm/cts-all.html?backend=bnns:
` InvalidStateError: createExecution fails: 4`

**Comment by huningxin** [comment]
Thanks for reporting this issue. This was introduced by my PR https://github.com/otcshare/chromium-src/pull/40. Sorry for that. It would be helpful if we have submission test tool in place.

**Comment by huningxin** [comment]
Fixed. @Christywl , please help verify. Thanks!

**Comment by Christywl** [comment]
Verified with the nightly build **b7ce158**, BNNS works.
