### ISSUE TITLE
[Image classification Sample] Image classification Sample doesn't work on Chromium build

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#281]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**b7ce158**)
Platform: Mac OS 10.13.6, Linux Ubuntu 16.04

**Expected Result:**
The example works.

**Actual Result:**
An error occurs when switch backends or examples:
`Cannot read property '_deleteAll' of undefined`

**How to Reproduce:**
1. Launch chromium and visit https://brucedai.github.io/nt/examples/image_classification_tflite/index.html
2. Try to switch backends or examples

**Comment by Wenzhao-Xiang** [comment]
@huningxin Hi, now the `_deleteALL()` is just necessary in webml-polyfill. Do backend 'WebML' also need this operation?

**Comment by huningxin** [comment]
I would suggest we could have a placeholder (empty implementation) for `WebML` backend currently.

**Comment by Christywl** [comment]
Verified this on nightly build b7ce158 with https://github.com/intel/webml-polyfill/commit/6fc19ec7927fb775824d98b05815f4f02b69c1a6, the examples works.
