### ISSUE TITLE
[WebGL2] The output values don't match the expected for FULLY_CONNECTED operation

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#302]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**0ff81ee**)
Platform: Mac OS 10.13.6

**Expected Result:**
The test should pass.

**Actual Result:**
The output values don't match the expected for FULLY_CONNECTED operation:
For example: 
- check result for Fully connected float example:
 expected:
  `  [8, 68, 36]`
 actual:
`[68, 0, 0]`

**How to Reproduce:**
1. Launch chromium and disable WebML flag
2. Visit https://brucedai.github.io/nt/test/fully_connected.html?backend=webgl2:
   
     CTS & CTS Supplement Test:
    - check result for Fully connected float example
    - check result for Fully connected float relu example
    - check result for Fully connected float relu1 example
    - check result for Fully connected float relu6 example
    - check result for Fully connected float example/2
    - check result for Fully connected float weights as inputs example
    - check result for Fully connected float 3D input example

**Comment by GreyZzzzzzXh** [comment]
This bug has been fixed by replacing webgl2 with tfjs-core (PR #297).

**Comment by Christywl** [comment]
This issue was fixed on webgl backend with the latest commit https://github.com/intel/webml-polyfill/commit/63c1ca253e7fa7d19267b8e8eb71a3b618d3fa65.
