### ISSUE TITLE
[WebGL2] WebGL2 doesn't support broadcasting

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#316]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**16d3dad**)
Platform: MacOS/Linux/Windows/Android

**Expected Result:**
WebGL2 supports broadcasting

**Actual Result:**
WebGL2 doesn't support broadcasting

**How to Reproduce:**
1. Launch chromium and disable WebML flag
2. Visit https://brucedai.github.io/nt/test/cts_supplement.html?backend=webgl2, and check ADD/MUL broadcasting test cases

**Comment by GreyZzzzzzXh** [comment]
This bug has been fixed by replacing webgl2 with tfjs-core (PR #297).
