### ISSUE TITLE
[BNNS] Support MUL op

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#322]

**Comment by lisa0314** [comment]
@huningxin  After review the files inside the Accelerate.Framework , I can only find the supports for matrix add and mul op and the matrix is 2-D which only has x and y coord. Could you please help to ask for some help from stuff in Apple?

**Comment by lisa0314** [comment]
[`vDSP_mmul`](https://developer.apple.com/documentation/accelerate/1449984-vdsp_mmul?language=objc) is a function which performs an out-of-place multiplication of two matrices and the matrices is only 2D.

**Comment by Christywl** [comment]
MUL operation works on BNNS backend on the nightly build 8658220.
