### ISSUE TITLE
[MPS] performance optimization

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#332]
According to [Apple* Machine Learning on Intel® Processor Graphics](https://software.intel.com/en-us/articles/apple-machine-learning-on-intel-processor-graphics), the MobileNet inference performance is over 150 images/sec. It is faster than WebML/MPS inference performance. We need to investigate the data, identify potential gap and try to close it as much as possbile.

**Comment by fujunwei** [comment]
It only includes GPU time with l.2596 - l.2599 in main.mm, below are related code
```
commit = mach_absolute_time();
[cmdBufs[last] waitUntilCompleted];
complete = mach_absolute_time();
elapsedTime = complete - commit;
```

**Comment by fujunwei** [comment]
The default testing is random data that is fast as reported seeing `main.mm` l.1593, but the data is not a real image.
Set `gGetPrediction` variable true to test final0.jpg, the time of predicting is similar with WebML/MPS, so i don't think it's a gap we need to fill.

**Comment by fujunwei** [comment]
The predicted time is 13ms using coreml model, but webml is 16ms with mps backend.
