### ISSUE TITLE
[NNAPI] support RESIZE_BILINEAR op

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#341]

**Comment by huningxin** [comment]
This op should be mapped to [ANEURALNETWORKS_RESIZE_BILINEAR](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a42bd92518e273b6716ecd56b571fcd3e)

@Christywl , could you please help verify it?

**Comment by Christywl** [comment]
Yes, RESIZE_BILINEAR operation works on NNAPI backend.

**Comment by huningxin** [comment]
Cool. Thanks!
