### ISSUE TITLE
[MPS] Mobilenet v2(Onnx) example works abnormally on Mac

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#348]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**9012a59**)
Platform: Mac OS 10.13.6

**Expected Result:**
Mobilenet v2(Onnx) example works fine.

**Actual Result:**
MobileNet v2(Onnx) example works abnormally on Mac. When choosing `Mobilenet v2(Onnx)`+MPS, the box is stuck on "Setting...". If changing MPS to BNNS,  the "Failed to setup MPS backend" exception continuously alerts.
In devtools console: `Uncaught (in promise) DOMException: finishfails: 4`

<img width="1280" alt="screen shot 2018-11-29 at 2 28 58 pm" src="https://user-images.githubusercontent.com/20039821/49203698-33166980-f3e4-11e8-8108-139d3ee1e198.png">
<img width="1280" alt="screen shot 2018-11-29 at 2 29 44 pm" src="https://user-images.githubusercontent.com/20039821/49203712-40335880-f3e4-11e8-86cc-6ba23fc7bbff.png">

**How to Reproduce:**
1. Launch chromium and visit https://brucedai.github.io/nt/examples/image_classification/index.html
2. Select `Mobilenet v2(Onnx)`

**Comment by pinzhenx** [comment]
Closed via https://github.com/intel/webml-polyfill/pull/469

**Comment by Christywl** [comment]
This issue was fixed with the examples codes https://github.com/intel/webml-polyfill/commit/c261a0afcd9e31e131a6dfa1ed9985abfdda375b.
