### ISSUE TITLE
Optimize ONNX.js with WebNN API

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#350]
https://github.com/Microsoft/onnxjs

**Comment by pinzhenx** [comment]
@huningxin @ibelem 
I put the first working version of [WebNN-optimized ONNX.js](https://pinzhenx.github.io/onnxjs/examples/browser/resnet50/index.html) online. Please have a look.

Current implementation is not very efficient, and I used their simple demo shipped with the ONNX.js. Later I will integrate it into their Vue based demo, and leverage their benchmark tool to improve the performance.

**Comment by pinzhenx** [comment]
@huningxin I have added op-level profiling and benchmark tool in the resnet and squeezenet examples. Now it's still executing in completely eager mode. Please let me know if you need some statistics.

**Comment by pinzhenx** [comment]
@huningxin I have made some optimizations and here are some results.

model: [resnet50_8.onnx](https://github.com/Microsoft/onnxjs-demo/blob/data/data/examples/models/resnet50_8.onnx)
WebNN

To make our two implementations comparable, I have disabled BN & RELU fusion and used eager mode in our benchmark, and disabled tensor reordering in ONNX.js benchmark demo (there's an option to do this):

ONNX.js (offload all ops, disable tensor reordering) | Ours (disable BN, RELU fusion, eager mode)
-- | --
315.175 ± 21.812 ms | 296.31+-27.04

Profiling shows that, in the ONNX.js results above, calls to the `startCompute` took 92.7%, which is pretty close to our results.

Some other results:

**ONNX.js (pure WASM, enable tensor reordering)**
1236.303 ± 50.586 ms

**ONNX.js (offload CONV, enable tensor reordering)**
993.631 ± 45.944 ms

**Ours (enable BN & RELU fusion, eager mode)**
166.03 ± 21.70 ms

**Ours (enable BN & RELU fusion, non-eager mode)**
111.77 ± 20.32 ms

**Comment by pinzhenx** [comment]
@huningxin Supported graph mode & subgraph partitioning. Now it can function like our polyfill.

https://pinzhenx.github.io/onnxjs/examples/

**Comment by ibelem** [comment]
@BruceDai @Christywl Please collect latest data for the optimization.

**Comment by huningxin** [comment]
Nice job @pinzhenx !  

There are notes I've taken based on our talk:
1. allow to switch backends of ONNX.js, say WebGL and WASM
2. clean your code modification to ONNX.js

**Comment by pinzhenx** [comment]
@huningxin Finished code clean & webgl selection
[git diff](https://github.com/Microsoft/onnxjs/compare/master...pinzhenx:webnn?expand=1)

**Comment by huningxin** [comment]
@pinzhenx , are you able to rebase your branch to ToT onnx.js master branch? There is conflict.

**Comment by pinzhenx** [comment]
@huningxin rebased.

**Comment by huningxin** [comment]
Cool. Thanks.

**Comment by huningxin** [comment]
@pinzhenx , could you please create a PR based on your branch to [the webnn branch of my fork](https://github.com/huningxin/onnxjs/tree/webnn). So we can review and discuss based on that. Thanks!

**Comment by pinzhenx** [comment]
refer to https://github.com/huningxin/onnxjs/pull/1

**Comment by pinzhenx** [comment]
Done. Close it
