### ISSUE TITLE
[BNNS] ResNet50(Onnx) doesn't work on BNNS backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#357]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**9012a59**)
Platform: Mac OS 10.13.6

**Expected Result:**
ResNet50(Onnx) example works fine.

**Actual Result:**
ResNet50(Onnx) doesn't work on BNNS backend:

`Failed to setup BNNS backend`

**How to Reproduce:**
1. Launch chromium and visit https://brucedai.github.io/nt/examples/image_classification/index.html
2. Select `ResNet50 v1(Onnx) ` or `ResNet50 v2(Onnx)`, and then select BNNS

**Comment by Christywl** [comment]
ResNet50 v1(Onnx) and ResNet50 v2(Onnx)works on BNNS backend on nightly build 8755e6b.

**Comment by huningxin** [comment]
Great job! @BruceDai , I think it makes sense to compare performance of ResNet-50 between WebAssembly and BNNS on CPU. Thoughts?

**Comment by BruceDai** [comment]
OK, I will submitted PR for updating Benchmark to support more model soon, thus those performance data will be provided later.
