### ISSUE TITLE
[Example] support OpenVINO models

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#358]
OpenVINO IR: https://software.intel.com/en-us/articles/OpenVINO-ModelOptimizer#intermediate-representation-notation-catalog
OpenVINO model zoo: https://github.com/opencv/open_model_zoo/blob/2018/intel_models/index.md

**Comment by huningxin** [comment]
I'd propose this feature as June milestone. @belem

**Comment by huningxin** [comment]
Thanks @pinzhenx . I understand we need the OpenVINO model loader and parser. Please layout a plan, so we can review.

**Comment by pinzhenx** [comment]
Netron has partial support for OpenVINO: it can parse the `.xml` network file but still lacks the support for getting weights from the `.bin` file.
So my plan is to follow the structure of ONNX.js importer:
- use [openvino.js](https://github.com/lutzroeder/netron/blob/master/src/openvino.js) to parse the network file
- extract tensor data and convert from NCHW to NHWC in `OpenVINOModelUtils.js`
- convert to WebNN model in `OpenVINOModelImporter.js`

**Comment by huningxin** [comment]
Sounds good, thanks @pinzhenx
