### ISSUE TITLE
[test] Add test case for ATROUS_CONV_2D op

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#374]
https://github.com/intel/webml-polyfill/blob/master/src/nn/Enums.js#L1174

**Comment by huningxin** [comment]
This is important for backend implementation. Target it to Jan milestone. Any thoughts @BruceDai ?

**Comment by BruceDai** [comment]
We have implemented 16 CTS test cases for  ATROUS_CONV_2D op by PR #463, and we are implementing more Unit test cases and CTS test cases.

**Comment by BruceDai** [comment]
Patch #543 implemented 27 Unit test cases for ATROUS_CONV_2D op, close this issue.
