### ISSUE TITLE
[WebGL] The browser crashed for some examples with WebGL backend on Android

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#376]
**Test Env:**
**Chromium** nightly build 70.0.3503.0 (**46503cb**) ,  **chrome stable** 70.0.3538.110
 Platform: Google Pixel 2(Android 8.1.0),  Huawei P20(Android 8.1.0)

**Expected Result:**
Crash doesn't happen.

**Actual Result:**
The browser crashed for some examples with WebGL backend on Android:
- Inception V4(TFlite)
- Incep. Res. V2(TFlite)
- ResNet50 v2(Onnx)
- DenseNet(Onnx)

Crash log: 
[crash.log](https://github.com/intel/webml-polyfill/files/2674557/crash.log)

**How to Reproduce:**
1. Setup the local server according to [example README](https://github.com/intel/webml-polyfill/blob/master/examples/image_classification/model/README.md)
2. Launch chromium or chrome on Android device and visit http://127.0.0.1:8080/examples/image_classification
3. Switch to WebGL backend and select the example:
    - Inception V4(TFlite)
    - Incep. Res. V2(TFlite)
    - ResNet50 v2(Onnx)
    - DenseNet(Onnx)

**Comment by Christywl** [comment]
On Google Pixel 2 XL device, chromium and chrome stable 71.0.3578.83 crashed for DenseNet(Onnx) WebGL. Other examples worked on WebGL backend.

**Comment by Christywl** [comment]
This issue can't reproduce wiht the latest codes https://github.com/intel/webml-polyfill/commit/19522266121edf4dbbebf214bcd16c24b1aaf1b8 on the nightly build 8755e6b.

**Comment by ibelem** [comment]
@Christywl please double confirm if we can close this issue if it's not reproducible.

**Comment by Christywl** [comment]
Close this issue, these examples work on WebGL on Android.
