### ISSUE TITLE
[WebGL] The outputs don't match the expected values for AVERAGE_POOL_2D operation with WebGL backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#380]
**Test Env:**
**Chromium** nightly build 70.0.3503.0 (**6540a81**) 
 Platform: Mac/Linux/Windows/Android

**Expected Result:**
Tests should pass.

**Actual Result:**
The outputs don't match the expected values for AVERAGE_POOL_2D operation with WebGL backend:
check result for Avg pool float example/2:
![image](https://user-images.githubusercontent.com/20039821/49985739-02b7f900-ffa8-11e8-80c3-8a448dd95139.png)

check result for Avg pool float example/4:
![image](https://user-images.githubusercontent.com/20039821/49985885-9984b580-ffa8-11e8-96f4-afeec540d752.png)

**How to Reproduce:**
1. Launch chromium and disable WebML flag
2. Visit https://brucedai.github.io/nt/test/avg_pool_2d.html?backend=webgl
    - check result for Avg pool float example/2
    - check result for Avg pool float example/4

_They passed before with webgl2 backend._

**Comment by Wenzhao-Xiang** [comment]
Different results for ResNet50 v1(Onnx) and Inception v2(Onnx) between WASM and WebGL backend.

Inception v2(Onnx):
WASM:
![inception_v2_wasm](https://user-images.githubusercontent.com/40754037/50194418-c0ab0080-0375-11e9-831d-37e9253f11d6.png)
WebGL:
![inception_v2_webgl](https://user-images.githubusercontent.com/40754037/50194452-f18b3580-0375-11e9-81de-a4c5a4d8ad80.png)

ResNet50 v1(Onnx):
WASM:
![resnet50_v1_wasm](https://user-images.githubusercontent.com/40754037/50194468-049e0580-0376-11e9-9766-23a0b779dba9.png)
WebGL:
![resnet50_v1_webgl](https://user-images.githubusercontent.com/40754037/50194479-1089c780-0376-11e9-9b33-755775b7abff.png)

These two models contains AveragePool with fuse padding, which leads to the difference.
