### ISSUE TITLE
[Test] RegressionChecker reports Linux-clDNN regression against latest master code 

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#384]
I ran RegressionChecker on Linux for clDNN backend against latest master code. It reports regression.
### Baseline Information:
Chromium version: 9012a59
Webml-polyfill version: 4778f20
### PR Submission Message:
Total Test Cases: 1704
Pass to Fail: 83
Fail to Pass: 157

My local webm-polyfill commit is 5644d444338bcdd846d07589593f746d637f0e1e
Chromium commit is https://github.com/otcshare/chromium-src/commit/46503cb7ae11be3a483646435a17382baa956a4d

According to https://github.com/otcshare/chromium-src/pull/62, it passed RegressionChecker before merged.

**Comment by BruceDai** [comment]
We have caught the root cause, and now are fixing it. 
@huningxin Please rerun latest RegressionChecker tool kit of latest baseline data #387 on Linux for clDNN backend to check your code firstly, Thanks.

**Comment by huningxin** [comment]
Fixed. Thanks!
