### ISSUE TITLE
[WASM] The outputs don't match the expected values for RESIZE_BILINEAR operation on WASM backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#386]
**Test Env:**
**Chromium** nightly build 70.0.3503.0 (**46503cb**) 
 Platform: Mac OS 10.13.6

**Expected Result:**
The test should pass.

**Actual Result:**
The outputs don't match the expected values for RESIZE_BILINEAR operation on WASM backend:
![image](https://user-images.githubusercontent.com/20039821/50128311-7cedc380-02af-11e9-80fd-0978cd20b42f.png)

**How to Reproduce:**
1. Launch chromium and disable WebML flag
2. Visit https://brucedai.github.io/nt/test/issue386_resize_bilinear.html?backend=wasm

_The expected values were from the tensorflow + python.
And only one test failed on WASM backend, other resize_bilinear tests got passed(https://brucedai.github.io/nt/test/resize_bilinear.html?backend=wasm)._

**Comment by Wenzhao-Xiang** [comment]
Fixed with #356, closed it.

**Comment by Christywl** [comment]
This issue has been fixed with webml-polyfill commit https://github.com/intel/webml-polyfill/commit/df292601737a2d03514c9a69a2faae7131f8383a.
