### ISSUE TITLE
[Example] Performance improvement of DeepLab

### ISSUE THREAD

**Issue by pinzhenx** [intel/webml-polyfill#395]
As stated in this [comment](https://github.com/intel/webml-polyfill/pull/335#issuecomment-449731108), the performance of DeepLab demo with WebGL is significantly hurt by the `dataSync()` call, whether on an integrated or dedicated GPU.

This issue on WebGL is caused by two factors:
- Lack of Argmax
- I/O bottleneck

### Lack of Argmax

Argmax is required by DeepLab model and always the last node in the graph. The current workaround is cutting the `argmax` from the graph and implementing it in JS. However, the input size of `argmax` is 21x larger than the output size, which means we need to download 20x more data from GPU without Argmax. 

![lutzroeder github io_netron_ 1](https://user-images.githubusercontent.com/7313938/50433868-caa0a680-0915-11e9-83c6-9362b7e7f37e.png)

Moreover, [the WebGL implementation](https://github.com/tensorflow/tfjs-core/blob/27766458746bbc5da44cffcee92ef605fdc1ec5c/src/kernels/webgl/gpgpu_util.ts#L351) has to allocate two large arrays to unpack the data when synchronizing with GPU (data in texture is stored in a packed format). Through profiling, allocating gigantic arrays appears very time-consuming, and directly leads to these two blank areas (~20ms) in the timing diagram.

![screen shot 2018-12-24 at 7 54 28 pm](https://user-images.githubusercontent.com/7313938/50432458-d0de5500-090c-11e9-82f4-bf35b5ac795c.png)

The latter readback behavior might not be an issue on native platforms, but we can still improve the performance by eliminating the overhead of computing argmax in JS and frequent garbage collection by Chrome (profiling shows that DOM GC will run on average every 3 frames and take about 20ms).

After supporting `argmax`, we can gain a huge performance boost in WebGL as shown below.

**Model:** DeepLab 257 atrous
**GPU:** NVIDIA GTX 960
**Backend:** WebGL

**Total  = (infer + sync + pre-/post- process) * frames + misc**

**With Argmax**
avg fps: 18
system gpu util: 70%
sum infer time (% of total): 28.0%

**Without Argmax**
avg fps: 10
system gpu util: 60%
sum infer time (% of total): 16.5%

### I/O bottleneck

Even with `argmax`, sync time still dominates the whole process. **The infer time makes no difference when using 224, 257 or 513 models, all takes ~10ms**, while the sync time grows rapidly, 30ms for 257 model and ~320ms for 513 model. This is a common problem in all examples now.

Specifically, in the DeepLab demo, outputs can be immediately used for rendering, so the ideal situation is just leaving the data in the GPU, but neither our API nor TFJS can do this at present. As a test, I attempted to disable `dataSync()` in WebGL, then the max fps could go up to 40+ but fluctuated a lot.

**Comment by huningxin** [comment]
Great investigation! 



> so the ideal situation is just leaving the data in the GPU, but neither our API nor TFJS can do this at present.

The WebNN API doesn't support GPU memory handle yet. However, could you investigate whether TFJS support that? I understand you can get the underlying texture of TFJS tensor.

**Comment by huningxin** [comment]
@pinzhenx , WebGL draw call is asynchronous. I am wondering whether it is fair to count the `readPixel` time all to I/O, because the `readPixel` might wait for the shader's computation. When you say for different input sizes, the inference time are similar, it looks more like the "inference time" is just "submission time". Could you please do more investigations? And we can consult with some WebGL experts.

**Comment by pinzhenx** [comment]
@huningxin You were right. From my experiments, I used the same output size with smaller output stride, i.e., the 'downsampling' factor, so it would keep the amount of data transferred but significantly increased the intermediate computation. Then I observed that the sync time did surge rapidly. So the computation time in the profiling is very likely to be only the issuing time.

**Comment by pinzhenx** [comment]
I’m closing this issue because according to the reasons above, I don't think IO is an urgent issue (or even a real issue). The support of GPU data manipulation will be tracked by an earlier issue https://github.com/intel/webml-polyfill/issues/115.

**Comment by pinzhenx** [comment]
@huningxin 
As I looked into the performance issue, I found that the lack of Argmax also has a big impact on native platforms. I used the 1x1 Conv to simulate Argmax that squeezes the output from 513x513x21 to 513x513x1 and get the following results:

**model:** 513 output stride: 16
**backend:** cldnn
**platform:** Windows i5-8250u   UHD620

no argmax | pseudo argmax
-- | --
122 ms | 65 ms

**Comment by huningxin** [comment]
@pinzhenx , thanks, that's interesting. could you share your code? so we can investigate the native support.

**Comment by pinzhenx** [comment]
@huningxin 
It's been updated on the demo website. The last two models all use atrous convolution and are of output stride of 16. The one with 'Argmax' should be faster.
https://pinzhenx.github.io/webml-demo/benchmark/
https://github.com/pinzhenx/webml-polyfill/tree/pseudo_argmax

**Comment by ibelem** [comment]
@BruceDai Please improve example with Argmax based on @pinzhenx's code above. @Christywl Please file Argmax enhancement requests/issues for cross platforms.

**Comment by pinzhenx** [comment]
Here a **real** argmax implementation just for reference. As it was committed last year, lots of code has changed.
https://github.com/pinzhenx/webml-demo/commit/a968f9969c3c14e15e492be9f8260c6841e178a5

The main change was in the `DrawOutputs.js` by removing the JS implementation of argmax from [_argmaxClippedSegMap()](https://github.com/pinzhenx/webml-demo/commit/a968f9969c3c14e15e492be9f8260c6841e178a5#diff-2db1ed7c4fe68ff5e3b5debe5b0b0f7eR795) and [_argmaxClippedSegMapPerson()](https://github.com/pinzhenx/webml-demo/commit/a968f9969c3c14e15e492be9f8260c6841e178a5#diff-2db1ed7c4fe68ff5e3b5debe5b0b0f7eR813)

Then set the input dims in `base.js` from `[x, x, 21]` to `[x, x, 1]`

**Comment by BruceDai** [comment]
Track by #1056, close it.
