### ISSUE TITLE
[API] Support 'align_corners' in RESIZE_BILINEAR op

### ISSUE THREAD

**Issue by pinzhenx** [intel/webml-polyfill#400]
By [definition](https://js.tensorflow.org/api/0.11.1/#image.resizeBilinear) of Tensorflow, `RESIZE_BILINEAR` has an extra parameter called `align_corners`. It's required by DeepLab models.

Without it, the output mask will have a slight bias towarding top-left corner.

__Without `align_corners`__
![without_align](https://user-images.githubusercontent.com/7313938/50625964-6bbadd00-0f66-11e9-8482-ab21a08106bc.png)

__With `align_corners`__
![with_align](https://user-images.githubusercontent.com/7313938/50625968-71b0be00-0f66-11e9-9c6f-ce92905200b9.png)

**Comment by huningxin** [comment]
Thanks @pinzhenx ! Could you please help send a PR to fix WebGL polyfill?

**Comment by huningxin** [comment]
The WebGL support has been merged. @pinzhenx , do you see gap in other backends?

**Comment by pinzhenx** [comment]
### About `align_corner`

Since Tensorflow has little detailed documentation on this argument, it's likely to cause confusion in development.

Intuitively we assume the bilinear interpolation algorithm will 'align corner', but it not the default behavior in tensorflow. This argument will result in a slight difference in the scaling factor.

From [Tensorflow doc](https://www.tensorflow.org/api_docs/python/tf/image/resize_bilinear):
> align_corners: An optional bool. Defaults to False. If true,  the centers of the 4 corner pixels of the input and output tensors are aligned, __preserving the values at the corner pixels__.

From [Tensorflow.js doc](https://js.tensorflow.org/api/0.14.1/#image.resizeBilinear):
> alignCorners (boolean) Defaults to False. __If true, rescale input by (new_height - 1) / (height - 1), which exactly aligns the 4 corners of images and resized images__. If false, rescale by new_height / height. Treat similarly the width dimension. Optional

[TFLite Implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/optimized/optimized_ops.h#L5453)
```c++
    float height_scale = static_cast<float>(input_height) / output_height;
    float width_scale = static_cast<float>(input_width) / output_width;
    if (op_params.align_corners && output_height > 1) {
      height_scale = static_cast<float>(input_height - 1) / (output_height - 1);
    }
    if (op_params.align_corners && output_width > 1) {
      width_scale = static_cast<float>(input_width - 1) / (output_width - 1);
    }

    ResizeBilinearGeneric(batches, input_height, input_width, depth,
                          output_height, output_width, height_scale,
                          width_scale, input_shape, input_data, output_shape,
                          output_data);
```

### `align_corner` in NNAPI

NNAPI doesn't has `align_corner` and it also doesn't keep the corner pixels. From [NNAPI doc](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a42bd92518e273b6716ecd56b571fcd3e):
> Resized images must be distorted if their output aspect ratio is not the same as input aspect ratio. __The corner pixels of output may not be the same as corner pixels of input.__


### Current solution

For now, the API itself remains unchanged, but we change its definition such that it will align corner by default for the sake of the DeepLab result.

**Comment by BruceDai** [comment]
@huningxin, As to RESIZE_BILINEAR op, should all backend support align_coners (true)? Or only NNAPI don't support align_coners (true) ?

**Comment by ibelem** [comment]
1. @BruceDai provide requirements
2. @huningxin  to change API
3. @pinzhenx review

**Comment by BruceDai** [comment]
@huningxin May we add '**align_corners**' attribute as **input3** of Inputs for **RESIZE_BILINEAR** op

- 0: A 4-D tensor, of shape [batches, height, width, depth], specifying the input.
- 1: An INT32 value, specifying the output height of the output tensor.
- 2: An INT32 value, specifying the output width of the output tensor.
- **3(new): An INT32 value, 0: align_corners false 1: align_corners true**.

thus we can config this attribute easily.

**Comment by huningxin** [comment]
@BruceDai , thanks for the inputs! Please help review #464
