### ISSUE TITLE
[Test] regression checker reports Linux-clDNN regression against baseline build

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#405]
Download baseline build 46503cb on Linux and run regression checker against it. Regression checker reports regression as screenshot:
![screenshot from 2019-01-04 11-21-59](https://user-images.githubusercontent.com/1005673/50672520-85fec480-1013-11e9-980c-69a72ab0ae3b.png)

@BruceDai , could you please take a look?

**Comment by Christywl** [comment]
I can't reproduce this issue with the baseline build 46503cb on Linux. The test results are the same as the baseline.

**Comment by huningxin** [comment]
It's my test environment issue. Sorry for noise. Close it.
