### ISSUE TITLE
[Example] Support SSD_Mobilenet_v2 and SSDLite_Mobilenet_v2

### ISSUE THREAD

**Issue by Wenzhao-Xiang** [intel/webml-polyfill#410]
Now our old model for object detection is:
![image](https://user-images.githubusercontent.com/40754037/50750814-afbd2300-1281-11e9-9342-941dbc3a72d1.png)

And I found new SSD_Mobilenet models for object detection:
![image](https://user-images.githubusercontent.com/40754037/50750687-070ec380-1281-11e9-8838-ef6265643628.png)
![image](https://user-images.githubusercontent.com/40754037/50750699-17bf3980-1281-11e9-9800-bdd0159b4dfe.png)

Ssdlite_mobilenet_v2 seems to have a better balance between performance and quality.

**Comment by Wenzhao-Xiang** [comment]
[SSD_Mobienet_V2](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz) and [SSDLite_Mobienet_V2](http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz) can download here.
Referrence: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by Wenzhao-Xiang** [comment]
SSD_Mobilenet_v1:

![image](https://user-images.githubusercontent.com/40754037/50751595-7686b200-1285-11e9-800a-68b3107278ef.png)

SSD_Mobilenet_v2:

![image](https://user-images.githubusercontent.com/40754037/50751629-9ae28e80-1285-11e9-9923-c5567025efb4.png)

SSDLite_Mobilenet_v2:
![image](https://user-images.githubusercontent.com/40754037/50751661-b2217c00-1285-11e9-9a38-f80e9a0b3990.png)

**Comment by huningxin** [comment]
Thanks @Wenzhao-Xiang ! Please file PR to enhance the SSD MobileNet example.
