### ISSUE TITLE
[BNNS] Inception Resnet V2(TFlite) example doesn't work on BNNS

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#436]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**022e2ff**)
Platform: Mac OS 10.13.6

**Expected Result:**
Inception Resnet V2(TFlite) example works.

**Actual Result:**
Inception Resnet V2(TFlite) example doesn't work on BNNS:
<img width="1280" alt="screen shot 2019-01-09 at 3 16 43 pm" src="https://user-images.githubusercontent.com/20039821/50883330-b1721c80-1422-11e9-862a-da5c1a8581b8.png">

**How to Reproduce:**
1. git clone https://github.com/intel/webml-polyfill
2. Download the example models according to https://github.com/intel/webml-polyfill/tree/master/examples/image_classification/model
3. Run: npm start
4. Visit http://127.0.0.1:8080/examples/image_classification/index.html?api_info=true
5. Select `Inception Resnet V2(TFlite)` and `FAST_SINGLE_ANSWER`

**Comment by lisa0314** [comment]
@Christywl After this [PR](https://github.com/otcshare/chromium-src/pull/71/files) is merged, this issue will be fixed.

**Comment by Christywl** [comment]
This issue was fixed on the nightly build 95ba69b.
