### ISSUE TITLE
[Doc] update native mapping MPS column with MPSNNGraph API

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#437]
https://github.com/intel/webml-polyfill/blob/master/docs/native_mapping.md

**Comment by fujunwei** [comment]
Update in https://docs.google.com/spreadsheets/d/17FP1DwWa840nvoaUlb_2alttjSq8U_x80AKLVCpk2Bg/edit?usp=sharing.

**Comment by huningxin** [comment]
Thanks @fujunwei ! I've replied to your questions in that doc. Please take a look.

**Comment by fujunwei** [comment]
@huningxin Do you have other commands?

**Comment by huningxin** [comment]
No other comments and changes have been merged. Thanks!
