### ISSUE TITLE
[DNNL] implement RESIZE_BILINEAR

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#461]

**Comment by huningxin** [comment]
MKLDNN doesn't provide resize bilinear primitive. I'd like to mark it low priority before MKLDNN supports it natively.

**Comment by pinzhenx** [comment]
Will be available in v1.2 https://github.com/intel/mkl-dnn/issues/563

**Comment by huningxin** [comment]
> Will be available in v1.2 [intel/mkl-dnn#563](https://github.com/intel/mkl-dnn/issues/563)

@pinzhenx , thanks for this info!

**Comment by ibelem** [comment]
@lisa0314 @huningxin @pinzhenx @BruceDai @fujunwei @Christywl Based on https://github.com/intel/mkl-dnn/issues/563, it has been implemented in https://github.com/intel/mkl-dnn/commit/16b9a5d3abfd5e4b900f07fbd1ba09662952f38f . Since all the performance test failed for Semantic Segmentation, please consider to implement this op.

**Comment by lisa0314** [comment]
@belem I found that the `argmax` op will block the testing for Semantic Segmention after I implemented `resize_bilinear`.

**Comment by ibelem** [comment]
@BruceDai @Christywl , is that possible to provide old models for Lisha to run the testing? Any other test ways?

**Comment by huningxin** [comment]
I remember we agreed to make the semantic segmentation example works for backends with argmax op supported and not supported. What's the status of that? @BruceDai

**Comment by BruceDai** [comment]
@huningxin As previous discussions, we use **dual backend** to run updated models with argmax op if argmax op wasn't implemented by WebNN sides.

**Comment by BruceDai** [comment]
@ibelem I provided those models without argmax ops to @lisa0314  yesterday. And I sent the mail to @lisha with the old test server URL for semantic segmentation example without argmax.

**Comment by huningxin** [comment]
@lisa0314 , I think this one should be closed by https://github.com/otcshare/chromium-src/pull/24, correct?

**Comment by lisa0314** [comment]
@huningxin yes, it should be closed and I will close this issue.
