### ISSUE TITLE
[Windows] Crash('Aw, Snap' error) occurs on the nightly build 95ba69b on Windows

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#470]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**95ba69b**)
Platform: Windows 10 (Dell XPS 13) [OS: Windows 10 Pro, CPU: Intel i5-8250U, GPU: Intel UHD Craphics 620(driver: 25.20.100.6471), Memory: 8GB]

**Expected Result:**
The chromium works fine.

**Actual Result:**
**'Aw, Snap'** error occurs on the latest nightly build **95ba69b** on Windows. 

`debug.log` in the directory `win_x64_SUCCEED\Chrome-bin`:
`[0116/135249.976:ERROR:main_dll_loader_win.cc(134)] Failed to load Chrome DLL from C:\workspace\web-test-suite\tool\WMLTP\output\chromiumBuild\95ba69b\win_x64_SUCCEED\Chrome-bin\70.0.3503.0\chrome_child.dll: The specified module could not be found. (0x7E)`

But chrome_child.dl exists in the directory `win_x64_SUCCEED\Chrome-bin\70.0.3503.0`.

I tried to remove the build and download again or restart the machine, all failed.

**How to Reproduce:**
1. Download the nightly build 95ba69b on Windows, and unzip it
2. Start chrome.exe

Note: Other builds work fine on Windows.

**Comment by huningxin** [comment]
I can't reproduce this in my dev environment. I am wondering whether it is related to https://bugs.chromium.org/p/chromium/issues/detail?id=880699. Let's double check.

**Comment by Christywl** [comment]
This issue was fixed on the nightly build 8b58220.
