### ISSUE TITLE
[Example] object detection example link is broken

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#481]
Test against fcfd06da0b47d580d6732e0fedf1e3cbf3b9667c , the object detection example link is broken, e.g. on local host it points to "http://localhost:8080/examples/ssd_mobilenet/index.html"

**Comment by ibelem** [comment]
I see, @Wenzhao-Xiang just updated ssd_mobilenet to object_detection, will fix it soon. Sorry about that.
