### ISSUE TITLE
[API] Support MAXIMUM op

### ISSUE THREAD

**Issue by Wenzhao-Xiang** [intel/webml-polyfill#494]
Now Object/Face detection (Tiny Yolo V2) and Super Resolution both required MAXIMUM op.

**Comment by huningxin** [comment]
Thanks @Wenzhao-Xiang ! We need to investigate and report out the MAXIMUM op reference in native frameworks and APIs, say TensorFlow, TensorFlow-Lite, ONNX, MPS, NNAPI. Could you please help?

**Comment by Wenzhao-Xiang** [comment]
Yeah! I have investigated Polyfill, NNAPI and ONNX, here is the result:

**WebGL(tf-js)**: Supported.
**WASM(Tflite)**: Just support a matrix and scalar do maximum op.
**NNAPI**: Go on supporting it.
**ONNX**: Have a "**Max**" op that can replace it.

Here is the tensoorflow MAXIMUM op reference https://www.tensorflow.org/api_docs/python/tf/math/maximum .

@huningxin @fujunwei @lisa0314 Please help investigate it with CLDNN, MPS and BNNS backend.

**Comment by huningxin** [comment]
@Wenzhao-Xiang thanks!

clDNN supports [max in element-wise primitive](https://intel.github.io/clDNN/group__cpp__primitives.html#gaa0a55214d8b45e135a753957707dace3)

**Comment by huningxin** [comment]
BTW, Leakly Relu is supported in both clDNN ([activation_relu_negative_slope](https://intel.github.io/clDNN/group__c__topology.html#ga5488c3a630352fd2586b23d2e75fa4ea)) and mkl-dnn ([mkldnn_eltwise_relu:alpha](https://github.com/intel/mkl-dnn/blob/8395a169e07e2beeabf18832a5c79cd53e2462a8/include/mkldnn_types.h#L757))

**Comment by Wenzhao-Xiang** [comment]
For NNAPI, MAXIMUM op will be supported from API level 29.
https://android.googlesource.com/platform/frameworks/ml/+/refs/heads/master/nn/runtime/include/NeuralNetworks.h#3405

**Comment by huningxin** [comment]
Thanks for investigation. I recall that you mentioned the NNAPI supports a combined MAXIMUM and MINIMUM op. Is it not the case?

**Comment by Wenzhao-Xiang** [comment]
> NNAPI supports a combined MAXIMUM and MINIMUM op

That is the ops implementation, rather than ops definition. 

I found that MAXIMUM and MINIMUM are two independent ops in NNAPI level 29.

**Comment by Wenzhao-Xiang** [comment]
closed by #584
