### ISSUE TITLE
Convert these 39 native Google's NNAPI CTS which use supported operations to WebML test cases for feature/performance

### ISSUE THREAD

**Issue by halton** [intel/webml-polyfill#50]

**Comment by BruceDai** [comment]
Those [39 tests](https://github.com/01org/web-test-suite/blob/master/tool/CTSConverter/filename.txt), which use supported operations have been converted to [Web ML CTS tests](https://github.com/BruceDai/nt/tree/master/test/cts). 
Android CTS uses 1e-5 as accuracy, our uses 1e-6, so 9 converted tests would fail due to 1e-6 accuracy, and other 29 test got pass.

**Comment by BruceDai** [comment]
Currently the following 39 Android CTS test specs in https://android.googlesource.com/platform/frameworks/ml/+/master/nn/runtime/test/specs/V1_0/
```
add.mod.py
avg_pool_float_1.mod.py
avg_pool_float_2.mod.py
avg_pool_float_3.mod.py
avg_pool_float_4.mod.py
concat_float_1.mod.py
concat_float_2.mod.py
concat_float_3.mod.py
conv_1_h3_w2_SAME.mod.py
conv_1_h3_w2_VALID.mod.py
conv_3_h3_w2_SAME.mod.py
conv_3_h3_w2_VALID.mod.py
conv_float.mod.py
conv_float_channels.mod.py
conv_float_channels_weights_as_inputs.mod.py
conv_float_large.mod.py
conv_float_large_weights_as_inputs.mod.py
conv_float_weights_as_inputs.mod.py
depthwise_conv.mod.py
depthwise_conv2d_float.mod.py
depthwise_conv2d_float_large.mod.py
depthwise_conv2d_float_large_2.mod.py
depthwise_conv2d_float_large_2_weights_as_inputs.mod.py
depthwise_conv2d_float_large_weights_as_inputs.mod.py
depthwise_conv2d_float_weights_as_inputs.mod.py
max_pool_float_1.mod.py
max_pool_float_2.mod.py
max_pool_float_3.mod.py
mul.mod.py
mul_relu.mod.py
reshape.mod.py
reshape_weights_as_inputs.mod.py
softmax_float_1.mod.py
softmax_float_2.mod.py
```
have been converted to tests which cover all [supported operations](https://github.com/intel/webml-polyfill/blob/master/docs/supported_ops.md).

**Comment by huningxin** [comment]
good work!

**Comment by BruceDai** [comment]
Fixed by PR https://github.com/intel/webml-polyfill/pull/68, new issue https://github.com/intel/webml-polyfill/issues/78 to track convert todo work, closed it.
