### ISSUE TITLE
[Doc] add fully connected and resize bilinear into native mapping doc

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#520]

**Comment by ibelem** [comment]
Close, track it in #621

**Comment by huningxin** [comment]
Let's break down the task:
NNAPI/clDNN: @huningxin 
MPS: @fujunwei 
BNNS: @lisa0314

**Comment by huningxin** [comment]
NNAPI/clDNN done.

**Comment by fujunwei** [comment]
MPS Done in https://drive.google.com/file/d/1jgo9TnjRIXoLtH2cj_A-gKdV3EL5MPD1/view?usp=sharing.

**Comment by lisa0314** [comment]
BNNS done in https://docs.google.com/spreadsheets/d/1X8A0EQapB5pXg3udnleqlCxnngy3z1DBy1_k8G_umAA/edit#gid=0.

**Comment by huningxin** [comment]
Thanks @fujunwei @lisa0314 , your modifications have been merged.
