### ISSUE TITLE
Optimize TensorFlow.js with WebML API with kernel layer backend

### ISSUE THREAD

**Issue by halton** [intel/webml-polyfill#54]
Decouple from issue #11

**Comment by sunlin-link** [comment]
https://github.com/sunlin-link/tfjs-core/tree/webml
https://github.com/sunlin-link/tfjs-layers/tree/webml

**Comment by huningxin** [comment]
Thanks for sharing the code.

> https://github.com/sunlin-link/tfjs-core/tree/webml

Regarding to https://github.com/sunlin-link/tfjs-core/commit/09703b9f6d0502f2ecf603cd3a62fe3c3e5597b5, the `BackendWebML` looks like a starting template code by copying the `MathBackendWebGL`.

> https://github.com/sunlin-link/chromium/tree/webml

Regarding to https://github.com/sunlin-link/chromium/commit/90b9e2ad6d0e3312f3fd6bbb7558cc682969d54d, the new methods added into `Compilation` has incorrect IDL declaration and incomplete implementation.

Anyway, from the code shared so far, I got the idea that adding the function level primitives besides the current graph level primitives API defined by WebML. 

The function level primitives seem straight forward to be integrated into TensorFlow.js interpreter backend. However, we need to investigate the native platform support, e.g. Android NN API doesn't provide the function level primitives, and native performance, e.g. of MPSCNN API on MacOS, before moving to that direction.

**Comment by huningxin** [comment]
> So as next step, I will look into integrating the 'JIT' solution into WebGL backend.

Completed the prototype and pushed to `webml2` branch mentioned above.

**Comment by huningxin** [comment]
The WebML optimizer in WebGL backend prototype result indicates the bottleneck is the WebGL texture readback and WebML input upload. It would be ideal to support WebGL texture as input and output for WebML execution. File issue #115 to log it.
