### ISSUE TITLE
Error happened when running 'CONCATENATION' and 'SOFTMAX' operations using WebGL2 backend. 

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#56]
### Test Env
Chromium Version :  nightly build 65.0.3324.0 (revision 3d99cdd)
Operating System : MacOS

### Expected behavior

Test should be PASS.

### Actual behavior
Error happened as following:
```
   Error: [Tensor] Tensor shape does not match the length of data. 
          at new Tensor (https://brucedai.github.io/nt/dist/webml-polyfill.js:966:15) 
          at Input.call (https://brucedai.github.io/nt/dist/webml-polyfill.js:21357:28) 
          at https://brucedai.github.io/nt/dist/webml-polyfill.js:8090:52 at Array.forEach (<anonymous>) 
          at https://brucedai.github.io/nt/dist/webml-polyfill.js:8086:24 at new Promise (<anonymous>) 
          at Model.execute (https://brucedai.github.io/nt/dist/webml-polyfill.js:8078:14) 
          at Execution._callee$ (https://brucedai.github.io/nt/dist/webml-polyfill.js:7961:44) 
          at tryCatch (https://brucedai.github.io/nt/dist/webml-polyfill.js:13458:40) 
          at Generator.invoke [as _invoke] (https://brucedai.github.io/nt/dist/webml-polyfill.js:13696:22) 
```

### How to reproduce  
1. Download and install nightly build Chromium
2. Launch  Chromium,  disabled the flag of "WebML" in chrome://flags, then relaunch Chromium
3. Run test case on Chromium: 
(1) https://brucedai.github.io/nt/test/concatenation.html?backend=webgl2 for concatenation test
(2) https://brucedai.github.io/nt/test/softmax.html?backend=webgl2 for softmax test

**Comment by Christywl** [comment]
This issue is also reproduced for AVERAGE_POOL_2D and MAX_POOL_2D operations.

**Comment by Christywl** [comment]
This issue wasn't reproduced now, and the related tests failed due to #95.

**Comment by BruceDai** [comment]
closed it.
