### ISSUE TITLE
[Investigation] CPU custom ops

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#564]
https://github.com/webmachinelearning/webnn/issues/6

**Comment by huningxin** [comment]
Layout a draft plan:
1. Integrate WebNN into ONNX.js #350 (by focusing on WebAssembly backend as first step)
2. Use [ResNet50](https://github.com/onnx/models/tree/master/resnet50) as workload
3. Execute ResNet50 with different options
3.1 all wasm op
3.2 some wasm ops (e.g. BN, RELU) + some WebNN ops (CONV, GEMM, POOL) (allow to configure for different combinations)
3.3 all WebNN ops
4. Implement ADD (#456) and FC (#460) in MKL-DNN backend
5. Move MKL-DNN backend into renderer process from GPU process (#569)

**Comment by pinzhenx** [comment]
@huningxin I'm wondering if we can close this issue?

**Comment by huningxin** [comment]
> 3\. Execute ResNet50 (e.g. modifying [demo](https://microsoft.github.io/onnxjs-demo/#/resnet50)) with different options
>     3.1 all wasm op
>     3.2 some wasm ops (e.g. BN, RELU) + some WebNN ops (CONV, GEMM, POOL) (allow to configure for different combinations)
>     3.3 all WebNN ops

This part has been covered by https://github.com/intel/webml-polyfill/issues/594

Let's keep this issue open until webnn issue closed. Thanks!

**Comment by pinzhenx** [comment]
@huningxin Got it. ETA of the first ONNX integration demo will be later next week.
