### ISSUE TITLE
[WebGL/Example] Fail to run PoseNet image example on Android WebGL when the scale is set to 0.5

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#572]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**efb0f90**)
Platform: Android 9(Google Pixel 2 XL)

**Expected Result:**
The example should work.

**Actual Result:**
Fail to run PoseNet image example on Android WebGL when the scale is set to **0.5**:

![image](https://user-images.githubusercontent.com/20039821/53315947-cafef300-3900-11e9-98f0-2e3af1fbed09.png)

When the scale is set to **0.25**/**0.75**/**1**, PoseNet works on Android WebGL.
When the scale is set to **0.5**, PoseNet works on Linux/Windows/Mac WebGL.

**How to Reproduce:**
  1. git clone https://github.com/intel/webml-polyfill
  2. `npm i` & `npm run build`
  3. `npm start`
  4.  Visit http://127.0.0.1:8080/examples/skeleton_detection/index.html on Android chromium and switch to WebGL

**Comment by GreyZzzzzzXh** [comment]
This issue has been fixed by tensorflow/tfjs-core#1489. Just need to upgrade tfjs-core version.

**Comment by Christywl** [comment]
This issue was fixed on https://github.com/intel/webml-polyfill/commit/8839867b328dcc8b5bbbcb7cbde4cfbe247da0a0. PoseNet works on Android WebGL.
