### ISSUE TITLE
Chromium crashed when running 'RESHAPE', 'SOFTMAX' operations test for WebML API on MacOS(MPS) devices

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#59]
### Test Env
Chromium Version :  nightly build 65.0.3324.0 (revision 3d99cdd)
Operating System : MacOS

### Expected behavior

Test should be PASS.

### Actual behavior
Crash occurs.

### How to reproduce  
1. Download and install Chromium
2. Launch  Chromium
3. Run test case on Chromium: 
(1) https://brucedai.github.io/nt/test/reshape.html for reshape test
(2) https://brucedai.github.io/nt/test/softmax.html for softmax test

**Comment by BruceDai** [comment]
We will verify this issue on latest nightly build revision f9e1a31.

**Comment by BruceDai** [comment]
This issue can be reproduced on latest nightly build revision f9e1a31.  
Detail crash log can also refer to [the log file](https://github.com/intel/webml-polyfill/files/2075089/concatenation_3.crash.log) .

**Comment by sunlin-link** [comment]
Issue 1 and 2 have the same root cause. 
In `execution_impl_mac.mm`, `CreateMPSImageDescriptor` may return null `MPSImageDescriptor`. Crash happened when using this return value to initialize a `MPSImage`.

**Comment by sunlin-link** [comment]
https://github.com/otcshare/chromium-src/pull/8

**Comment by Christywl** [comment]
Chromium also crashed when running the following cts tests on Mac:
Enable WebML flag and access to https://brucedai.github.io/nt/test/cts-all.html:
```
check result for Avg pool float example/2
check result for Depthwise conv2d float large 2 weights as inputs example
check result for Max pool float example/2
check result for Reshape example
check result for Reshape weights as inputs example
check result for Softmax float example/2
```

**Comment by sunlin-link** [comment]
@BruceDai Please help to verify the fix.
