### ISSUE TITLE
[NNAPI] Crash happened when testing reshape using special value -1 on Android

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#62]
### Test Env
Chromium Version :  nightly build 70.0.3503.0
Operating System : Android
Test Device: Google Pixel 2 (Android 8.1)

### Expected behavior

Test should be PASS.

### Actual behavior
Crash happened when testing reshape using special value -1.

### How to reproduce  
1. Download and install Chromium
2. Launch Chromium and enable WebML
3. Run test case on Chromium: 
https://brucedai.github.io/nt/test/reshape_neg1.html?backend=nnapi for reshape test using special value -1.

[reshape_neg1_crash.log](https://github.com/intel/webml-polyfill/files/2304478/reshape_neg1_crash.log)

**Comment by Christywl** [comment]
For webml-polyfill(webgl2) on Mac, it throws another error: 


```
Error: Invalid value 0,0,0,0
    at Execution.setOutput (https://brucedai.github.io/nt/dist/webml-polyfill.js:7935:15)
    at r.<anonymous> (operations/reshape_neg1.js:32:17)
```
Test: https://github.com/BruceDai/nt/blob/master/test/operations/reshape_neg1.js#L32

**Comment by Christywl** [comment]
Filed a new issue #110 for https://github.com/intel/webml-polyfill/issues/62#issuecomment-401994511.

**Comment by Christywl** [comment]
Close this issue since the test case with special value -1 has been removed.
