### ISSUE TITLE
[NNAPI] Support TANH op

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#626]

**Comment by mingmingtasd** [comment]
Testing on Huawei P20 pro will cause chrome to crash, while on pixel 3, there will be an error :"Model is not implemented".

**Comment by mingmingtasd** [comment]
TANH is supported on Android 9 and Android 10 now.

**Comment by Christywl** [comment]
TANH op works for NNAPI on Google pixel 3(Android 9.0) with build with https://github.com/otcshare/chromium-src/commit/def95eb6c61c0eeb40f654873d6faeb98e1ca66c.
