### ISSUE TITLE
[NNAPI] The outputs don't match the expected values when testing concatenation using axis being -1 on Android

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#63]
### Test Env
Chromium Version :  nightly build 70.0.3503.0
Operating System : Android
Test Device: Google Pixel 2  (Android 8.1)

### Expected behavior
Test should be PASS.

### Actual behavior
The actual outputs don't match the expected values.
- Concatenation Test for 4-D input with axis being -1
expected:
```
[101.0, 102.0, 201.0, 202.0,
 103.0, 104.0, 203.0, 204.0,
 105.0, 106.0, 205.0, 206.0,
 107.0, 108.0, 207.0, 208.0,
 109.0, 110.0, 209.0, 210.0,
 111.0, 112.0, 211.0, 212.0,
 113.0, 114.0, 213.0, 214.0,
 115.0, 116.0, 215.0, 216.0]
```
actual:

```
[0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0]
```

### How to reproduce  
1. Download and install Chromium
2. Launch  Chromium
3. Run test case on Chromium: 
https://brucedai.github.io/nt/testa/concatenation_neg1.html?backend=nnapi for concatenationtest using axis being -1.

**Comment by Christywl** [comment]
Close this issue since the test case with special value -1 has been removed.
