### ISSUE TITLE
[Backend] OpenVINO based backend for Linux

### ISSUE THREAD

**Issue by ibelem** [intel/webml-polyfill#653]

**Comment by huningxin** [comment]
I plan to use open source version of OpenVINO - [dldt](https://github.com/opencv/dldt)

**Comment by huningxin** [comment]
Layout initial plan for this task

- [ ] integrate build of dldt/inference_engine (ie) and one plugin (MKLDNN) into chromium
- [ ] implement inference engine based compilation delegate
- [ ] implement inference engine based execution
- [ ] implement ops

**Comment by huningxin** [comment]
https://github.com/otcshare/chromium-src/pull/108 adds `ADD`, `MUL` and `CONV_2D` ops. I will file issues for remaining ops and GPU/VPU plugins.

**Comment by huningxin** [comment]
Ops:
 * DEPTHWISE_CONV_2D/ATROUS: https://github.com/intel/webml-polyfill/issues/698
 * AVERAGE_POOL_2D and MAX_POOL_2D: https://github.com/intel/webml-polyfill/issues/699
 * CONCATENATION: https://github.com/intel/webml-polyfill/issues/700
 * SOFTMAX: https://github.com/intel/webml-polyfill/issues/701
 * RESHAPE: https://github.com/intel/webml-polyfill/issues/702
 * FULLY_CONNECTED: https://github.com/intel/webml-polyfill/issues/703
 * RESIZE_BILINEAR: https://github.com/intel/webml-polyfill/issues/704

Plugins:
 * GPU plugin: https://github.com/intel/webml-polyfill/issues/705
 * VPU Plugin: https://github.com/intel/webml-polyfill/issues/706

**Comment by fujunwei** [comment]
> [otcshare/chromium-src#108](https://github.com/otcshare/chromium-src/pull/108) adds `ADD`, `MUL` and `CONV_2D` ops. I will file issues for remaining ops and GPU/VPU plugins.

Nightly version of Linux builds successfully in 8babc60.

**Comment by huningxin** [comment]
> Nightly version of Linux builds successfully in 8babc60.

@fujunwei , thanks! It passes my smoke test. @BruceDai , please help verify the build. To use IE backend, please append `--use-inference-engine`. Currently, only CPU (MKLDNN) backend is enabled.

**Comment by Christywl** [comment]
IE backend works on the nightly build ef9d267(--use-inference-engine): https://brucedai.github.io/nt/test/index-local.html?backend=mkldnn 
Test result: passes 311, failures: 403
And tried some examples(Image Classification/Object Detection), they also work on IE backend.
