### ISSUE TITLE
[webml/MPS] No exception is thrown when passing an invalid argument to addOperand()

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#66]
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision f9e1a31)
OS : Mac OS X 10.13.4

**Expected Result:**
Pass an invalid argument to addOperand(), it should throw an exception

**Actual Result:** 
No exception is thrown when passing an invalid argument to addOperand()

**How to reproduce:**
Pass the following invalid arguments to addOperand():

- 	TENSOR_FLOAT32 type: no "dimensions"
- 	TENSOR_INT32 type: no "dimensions"
- 	TENSOR_QUANT8_ASYMM type:  no "dimensions"
- 	TENSOR_QUANT8_ASYMM type:  no "scale"
- 	TENSOR_QUANT8_ASYMM type:  no "zeroPoint"
- 	TENSOR_QUANT8_ASYMM type:  no "scale" and "zeroPoint"
- 	TENSOR_QUANT8_ASYMM type:  "zeroPoint" < 0 
- 	TENSOR_QUANT8_ASYMM type:  "zeroPoint" > 255
- 	TENSOR_QUANT8_ASYMM type:  "scale" is negative 
- 	addOperand() only requires one argument, passing two arguments should raise an error: two scalars or two tensors

	
For example:
1.TENSOR_FLOAT32 type: no "dimensions":

```
it('raise error when passing a TENSOR_FLOAT32 tensor not having "dimensions" option', function() {
  return nn.createModel(options).then((model)=>{
    assert.throws(() => {
      model.addOperand({type: nn.TENSOR_FLOAT32});
    });
  });
});
```

2.addOperand() only requires one argument, passing two arguments should raise an error: pass two scalars
```
it('raise error when passing two scalars', function() {
  return nn.createModel(options).then((model)=>{
    assert.throws(() => {
      model.addOperand({type: nn.INT32}, {type: nn.INT32});
    });
  });
});
```

**Comment by sunlin-link** [comment]
`addOperand()` just save the data without checking.  in `finish()` and subsequent execution, every saved operands and operations will be checked for the availability and exceptions could be thrown.

**Comment by sunlin-link** [comment]
@Christywl Fixed. Please verify

**Comment by Christywl** [comment]
@sunlin-link , I tried the chromium nightly build **_313c1c2_**, most negative tests passed except for the following case:

- addOperand() only requires one argument, passing two arguments should raise an error: two scalars or two tensors

**Comment by fujunwei** [comment]
The SyntaxError is thrown while the code is being parsed and not while it's running. you can use window.onerror and figure out that there's an error.

```
<script>
  window.onerror = function (e) {
    console.log('Error: ', e);
  };
</script>
```

**Comment by BruceDai** [comment]
@fujunwei About "addOperand() only requires one argument, passing two arguments should raise an error....",  we find it doesn't throw any error, so we couldn't catch it by test case. Please help to handle this exception to throw error, thanks

**Comment by fujunwei** [comment]
It's not a issue for javascript, remaining parameters will be ignored but don't raise a error, for example
```
<textarea id="textarea" rows=100 cols=100></textarea>
var textarea = document.getElementById("textarea", "normal");
```
but `var textarea` will be null if the first parameter is not found
```
<textarea id="textarea" rows=100 cols=100></textarea>
var textarea = document.getElementById("notFound", "textarea");
```
