### ISSUE TITLE
[MPS] The compilation and warmup time is abnormal on new MacBook Pro

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#663]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**b3ad1c0**)
Platform: 
   - macOS 10.14.3(CPU: Intel i7-8559U, GPU: Intel Iris Plus Graphics 655)
   - macOS 10.14.3(CPU: Intel i5-8259U, GPU: Intel Iris Plus Graphics 655)

**Actual Result:**
Compared with the old MacBook Pro, the MPS compilation and warmup time on new devices is abnormal:
For example:
Image Classification/MobileNet v1(TFLite)/SUSTAINED_SPEED:

   - **Old devices:**

macOS   Version | CPU | GPU | Compilation Time | Warmup Time | Inference Time
-- | -- | -- | -- | -- | --
10.13.6 | Intel i5-5257U | Intel Iris Graphics   6100 | 83.5 | 3821.7 | 19.6
10.14.3 | Intel i5-5257U | Intel Iris Graphics   6100 | 94.5 | 2013.6 | 19.2

   - **New devices:**

macOS   Version | CPU | GPU | Compilation Time | Warmup Time | Inference Time
-- | -- | -- | -- | -- | --
10.14.3 | Intel i5-8259U | Intel Iris Plus   Graphics 655 | 3152.7 | 74.1 | 19.2
10.14.3 | Intel i7-8559U | Intel Iris Plus   Graphics 655 | 2959.4 | 145 | 25.1

**How to Reproduce:**
1. git clone https://github.com/intel/webml-polyfill
2. npm i & npm run build
3. Download the model files
4. npm start
5. Visit http://localhost:8080/examples/image_classification/index.html on chromium
6. Choose any example and select SUSTAINED_SPEED
7. Open devtools and check the compilation and warmup time on the console

**Comment by fujunwei** [comment]
Below feedback come from MPS team.

```
The newer platforms SKL+(in this case 655) uses Intel plugin  where we perform all the compilation 
@init time(node creating time), at node execution time no compilation should happen.

Looks to me for non-plugin version(6100) most compilation happen @the first inference
```
