### ISSUE TITLE
[webml/MPS] No exception is thrown when an argument passed to setOperandValue() is incompatible with the type expected

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#67]
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision f9e1a31)
OS : Mac OS X 10.13.4

**Expected Result:**

- Exception should be thrown when operand has the type of INT32 or TENSOR_INT32 and its value isn’t Int32Arrary 
- Exception should be thrown when operand has the type of FLOAT32 or TENSOR_FLOAT32 and its value isn’t Float32Arrary
- Exception should be thrown when operand has the type of UINT32 and its value isn’t Uint32Arrary
- Exception should be thrown when operand has the type of TENSOR_QUANT8_ASYMM and its value isn’t Uint8Arrary
- Exception should be thrown when operand is scale and the length of its value is greater than 1.

**Actual Result:** 
No exception is thrown when an argument passed to setOperandValue() is incompatible with the type expected

**How to reproduce:**
Set the following incompatible value:
       

- Add an operand with a FLOAT32 scalar or TENSOR_FLOAT32 tesnsor, but set its value to a different type(not Float32Arrary):

```
	an Int8Array data
	an Uint8ClampedArray data
	an Int16Array data
	an Uint16Array data
	a Float64Array data
	a DataView data
```
- Add an operand with a INT32 scalar or TENSOR_INT32 tensor, but set its value to a different type(not Int32Arrary):
```
	an Int8Array data
	an Uint8ClampedArray data
	an Int16Array data
	an Uint16Array data
	a Float64Array data
	a DataView data
```
- Add an operand with a UINT32 scalar, but set its value to a different type(not Uint32Arrary):
```
	an Int8Array data
	an Uint8ClampedArray data
	an Int16Array data
	an Uint16Array data
	a Float64Array data
	a DataView data
```
- Add an operand with a TENSOR_QUANT8_ASYMM tensor, but set its value to a different type(not Uint8Arrary):

```
	an Int8Array data
	an Uint8ClampedArray data
	an Int16Array data
	an Uint16Array data
	a Float64Array data
	a DataView data
```
- Add an operand for a scalar, but the length of its value is greater than 1
	
For example:
1. set an Int8Array data for a FLOAT32 scalar
```
it('raise error when setting an Int8Array data for a FLOAT32 scalar', function() {
  return nn.createModel(options).then((model)=>{
    model.addOperand({type: nn.FLOAT32});
    assert.throws(() => {
      model.setOperandValue(0, new Int8Array([0]));
    });
  });
});
```
2. set a Float32Array data which length > 1 for a FLOAT32 scalar
```
it('raise error when setting a Float32Array data which length > 1 for a FLOAT32 scalar', function() {
  return nn.createModel(options).then((model)=>{
    model.addOperand({type: nn.FLOAT32});
    assert.throws(() => {
      model.setOperandValue(0, new Float32Array([0, 0]));
    });
  });
});
```

**Comment by sunlin-link** [comment]
When setting operand value, the data is save into raw memory with the type erased. Is it necessary to check the data type in this case? Even if it is, because `addOperand` and `setOperandValue` are discrete operations, the check step should be done in `finish()`.

**Comment by sunlin-link** [comment]
After synced with ningxin, we should change the argument type

**Comment by sunlin-link** [comment]
@Christywl Fixed. Please verify

**Comment by Christywl** [comment]
@sunlin-link , I tried the chromium nightly build **_313c1c2_**, most negative tests passed except for the following case:

- Exception should be thrown when operand is scale and the length of its value is greater than 1.

Steps: 
Run https://brucedai.github.io/nt/testm/index-local.html?backend=mps, check the tests in `#setOperandValue API`: 

- raise error when   setting a Float32Array data which length > 1 for a FLOAT32 scalar
- raise error when   setting an Int32Array data which length > 1 for an INT32 scalar
- raise error when   setting an Uint32Array data which length > 1 for an UINT32 scalar
