### ISSUE TITLE
[MPS] DeepLab 224 example has different results on macOS 10.13.6 and 10.14.3

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#673]
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (b3ad1c0)
Platform: macOS

**Actual Result:**
DeepLab 224 example has different results on macOS 10.13.6 and 10.14.3:

- Doesn't work on macOS 10.14.3 since #446:
<img width="1280" alt="Screenshot 2019-03-22 at 10 10 03" src="https://user-images.githubusercontent.com/20039821/54796724-56fc0480-4c8c-11e9-8fa3-abbb8b73bc67.png">

- Works on macOS 10.13.6.
<img width="1280" alt="Screen Shot 2019-03-22 at 10 11 02 AM" src="https://user-images.githubusercontent.com/20039821/54796713-43e93480-4c8c-11e9-8d8f-708c75032a4f.png">

**How to Reproduce:**
Visit https://brucedai.github.io/nt/examples/semantic_segmentation/index.html?prefer=sustained&b=WebML&m=deeplab_mobilenet_v2_224&t=tflite&s=image&d=0

**Comment by fujunwei** [comment]
The 224 model has been supported from  macOS 13.14.04.

**Comment by Christywl** [comment]
Verified that DeepLab 224 model worked on macOS 10.14.4.
