### ISSUE TITLE
[IE] enable VPU plugin

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#706]

**Comment by huningxin** [comment]
Please follow steps of OpenVINO https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html#additional-NCS-steps to install NCS2

**Comment by huningxin** [comment]
To build the https://github.com/otcshare/chromium-src with myriad vpu support, there are two pre-requests:
1. add the build argument `enable_ie_myriad = true` into `args.gn`
2. use the inference-engine tree which has vpu source code

**Comment by BruceDai** [comment]
@miaobin please follow above two prerequests configurations to build for VPU on Linux platform, thanks.
