### ISSUE TITLE
[clDNN] DenseNet(ONNX) froze on Linux Chromium 75

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#712]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (c623981)
Platform: Linux

**Expected Result:**
DenseNet(ONNX) should work.

**Actual Result:**
DenseNet(ONNX) froze on Linux Chromium 75:
![linux-densenet-freeze](https://user-images.githubusercontent.com/20039821/55446220-4edb8780-55f1-11e9-8369-67c5492e935a.png)

**How to Reproduce:**
1. Setup test server and start
2. Visit http://localhost:8080/examples/image_classification/
3. Select SUSTAINED and unselect WASM
4. Select DenseNet model
5. Wait for a few minutes

Note: This issue didn't happen on the build b3ad1c0(70.0.3503.0), DenseNet works fine.

**Comment by Christywl** [comment]
Same issue #714 on Android, it doesn't happen on Windows and macOS Chromium 75.

**Comment by mingmingtasd** [comment]
The general reason for this issue has been found. The function in blink fails to call the function in services. To be specific, when the function named "ScriptPromise Model::finish ()" in model.cpp  calls the function named "ModelImp::Finish() " in model_impl.cc, the latter dose not work. But the way to fix this issue need more time to find.

**Comment by mingmingtasd** [comment]
It has been verified that this issue will be solved after upgrading the chromium version to 78. So the issue can be closed after rebasing.

**Comment by Christywl** [comment]
This issue was fixed on the build https://github.com/otcshare/chromium/commit/e7b9a67db6608d4358141193994194705dc95b0d (79.0.3917.0).
