### ISSUE TITLE
[NNAPI] DenseNet(ONNX) froze on Android Chromium 75

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#714]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (c623981)
Platform: Android(Google Pixle 3, Google Pixel 2 XL)

**Expected Result:**
DenseNet(ONNX) should work.

**Actual Result:**
DenseNet(ONNX) froze on Android Chromium 75.

**How to Reproduce:**
1. Setup test server and start
2. Visit http://localhost:8080/examples/image_classification/
3. Select SUSTAINED and unselect WASM
4. Select DenseNet model
5. Wait for a few minutes

Note: This issue didn't happen on the build b3ad1c0(70.0.3503.0), DenseNet works fine.

**Comment by Christywl** [comment]
Same issue #712 on Linux, DenseNet(ONNX) works fine on Windows and macOS Chromium 75.

**Comment by ibelem** [comment]
Reassign to @lisa0314 as it's cross OS issue.

**Comment by mingmingtasd** [comment]
This issue may be the same as #712.

**Comment by mingmingtasd** [comment]
It has been verified that this issue will be solved after upgrading the chromium version to 78. So the issue can be closed after rebasing.

**Comment by Christywl** [comment]
This issue was fixed on the build https://github.com/otcshare/chromium/commit/e7b9a67db6608d4358141193994194705dc95b0d (79.0.3917.0).
