### ISSUE TITLE
[MPS] Chromium crashed when running the quantized models

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#717]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (c623981)
Platform: macOS 

**Expected Result:**
Chromium shouldn't crash, should throw an error because MPS doesn't support TENSOR_QUANT8_ASYMM type.

**Actual Result:**
Chromium crashed when running the quantized models:
<img width="1280" alt="Screen Shot 2019-04-04 at 2 39 04 PM" src="https://user-images.githubusercontent.com/20039821/55534590-69902800-56e7-11e9-845c-9bb21f91e9d3.png">

**How to Reproduce:**
1. Setup test server and start
2. Visit http://localhost:8080/examples/image_classification
3. Select SUSTAINED and unselect WASM
4. Select one model
   - MobileNet v1 Quant 
   - MobileNet v2 Quant
Or 
    - SSD MobileNet v2 Quant in http://localhost:8080/examples/object_detection

**Comment by ibelem** [comment]
@Christywl please re-test to check if this bug has been fixed.

**Comment by Christywl** [comment]
This issue was fixed on the build 9642fde.
