### ISSUE TITLE
Using webml with polyfill

### ISSUE THREAD

**Issue by startupgurukul** [intel/webml-polyfill#719]
Hi folks awesome work with hitting native performance via web. 

Coming to my question,  To use webml, can we just use the polyfill?   it doesn't seem to be working though(Should we build the webml branch of chromium for it to work)

Second question, now processors seem to have APU(mediatek p90) and NPU (Kirin 980), my understanding is that webml can use it to accelerate inference, can you confirm
https://www.mediatek.com/blog/googles-ml-kit-arrives-on-the-p90

**Comment by huningxin** [comment]
@startupgurukul , thanks for your interests.

> To use webml, can we just use the polyfill?

polyfill can only give you performance that WebAssembly and WebGL can provide.

> Should we build the webml branch of chromium fork for it to work

To get close-to-native performance, yes, you need to build `webml` branch of chromium.

> Second question, now processors seem to have APU(mediatek p90) and NPU (Kirin 980), my understanding is that webml can use it to accelerate inference, can you confirm
> https://www.mediatek.com/blog/googles-ml-kit-arrives-on-the-p90

The WebNN (Web Neural Network) API implementation (in `webml` branch of chromium fork) is based on NNAPI for Android. So if the APU or NPU is supported by NNAPI, WebNN should be able to use it. We don't have the two phones you mentioned, so we can't confirm. Feel free to file issues, if it doesn't work. Thanks in advance!

**Comment by startupgurukul** [comment]
Awesome, thanks for the reply. Are there nightly builds of webml enabled
chromium, building from code is taking lot of time for every new commit in
repo.

I will keep you posted about the performance on these devices

**Comment by startupgurukul** [comment]
Pardon my naive question isn't WASM natively supported in major browsers, I thought polyfill would be good enough and with WASM we hit near device performance

I understand  the need to fork  of webnn to implement android NN API  but to currently use it, wouldn't the WASM backed work with just a polyfill and hit realtime performance
