### ISSUE TITLE
[WebGL] Chromium crashed when running Super Resolution(SRGAN 128x4) on Windows/Android

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#720]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (c623981)
Platform: Windows (Dell XPS 13, GPU: Intel Graphics 620, CPU: Intel i5-8250U), Android (Google Pixel 2 XL, GPU: Qualcomm Adreno 540, CPU: Qualcomm Snapdragon 835)

**Expected Result:**
Chromium shouldn't crash.

**Actual Result:**
Chromium crashed when running Super Resolution(SRGAN 128x4):
<img width="960" alt="super-resolution-windows-webgl" src="https://user-images.githubusercontent.com/20039821/55694242-deb07580-59e5-11e9-9a75-20bf286806d8.png">

**How to Reproduce:**
1. Setup test server and start
2. Visit http://localhost:8080/examples/super_resolution
3. Select WebGL
4. Select `SRGAN 128x4`

**Comment by ibelem** [comment]
@Christywl @GreyZzzzzzXh Please list all the test results for different OS/Devices/models (different sizes)

**Comment by Christywl** [comment]
Super Resolution on WebGL:

| OS | Device | CPU | GPU | Memory | SRGAN 96x4 | SRGAN 128x4 | 
| ------ | ------ | ------ | ------ | ------ | ------ | ------ | 
| Windows | Dell XPS 13 | Intel i5-8250U | Intel Graphics 620 | 8GB | Pass | Error: Failed to compile vertex shader | 
| Linux | Dell XPS 13 | Intel i7-8550U | Intel UHD Graphics 620 (Kabylake GT2) | 16GB | Pass | Pass | 
| macOS 10.13.6 | MacBook Pro(Retina, 13-inch, Early 2015) | Intel i5-5257U | Intel Iris Graphics 6100 | 8GB | Pass | Pass | 
| macOS 10.14.4 | MacBook Pro(13-inch, 2018, Four Thunderbolt 3 Ports) | Intel i5-8259U | Intel Iris Plus Graphics 655 | 16GB | Pass | Pass | 
| Android 9 | Google Pixel 3 | Qualcomm Snapdragon 845 | Qualcomm Adreno 630 | 4GB | Pass | Error: Failed to compile fragment shader | 
| Android 9 | Google Pixel 2 XL | Qualcomm Snapdragon 835 | Qualcomm Adreno 540 | 4GB | Pass | RangeError: Array buffer allocation failed | 
| Android 8.1.0 | HUAWEI P20 Pro | Kirin 970 | Mali-G72 MP12 | 6GB | Pass | RangeError: Array buffer allocation failed |

**Comment by GreyZzzzzzXh** [comment]
@Christywl , thanks!

**Comment by Christywl** [comment]
Checked with commit https://github.com/intel/webml-polyfill/commit/83d9d19358a7728bee99c256eab11ebc675d2210 and nightly build ab32401 on WebGL backend for Android and Windows, this issue didn't happen, so close it.
