### ISSUE TITLE
[IE] Fused ReLU1 activation function doesn't work on IE backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#734]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (**ef9d267**)
Platform: Linux

**Expected Result:**
The tests should pass.

**Actual Result:**
Fused ReLU1 activation function doesn't work on IE backend.

**How to Reproduce:**
  Launch chromium with `/usr/bin/chromium-browser-unstable --no-sandbox --use-inference-engine` and visit https://brucedai.github.io/nt/test/issue_relu1.html?backend=mkldnn

**Comment by huningxin** [comment]
fixed by https://github.com/otcshare/chromium-src/pull/121

**Comment by Christywl** [comment]
This issue was fixed on the build 3acec85.
