### ISSUE TITLE
[tool] Enable RegressionChecker tool kit to support Linux-IE-clDNN and Linux-IE-MYRIAD

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#744]
for checking #705

**Comment by BruceDai** [comment]
<table>
  <tr>
    <th rowspan="2">Platform</th>
    <th rowspan="2">Switch</th>
    <th colspan="3">Preference</th>
  </tr>
  <tr>
    <td>fast</td>
    <td>sustained</td>
    <td>low</td>
  </tr>
  <tr>
    <th rowspan="2">Windows</th>
    <td>--use-dml</td>
    <td>MKLDNN</td>
    <td>DirectML</td>
    <td>DirectML</td>
  </tr>
  <tr>
    <td>w/o --use-dml</td>
    <td>MKLDNN</td>
    <td>clDNN</td>
    <td></td>
  </tr>
  <tr>
    <th rowspan="2">Linux</th>
    <td>--use-inference-engine</td>
    <td>IE-MKLDNN</td>
    <td>IE-clDNN</td>
    <td>IE-MYRIAD</td>
  </tr>
  <tr>
    <td>w/o --use-inference-engine</td>
    <td>MKLDNN</td>
    <td>clDNN</td>
    <td></td>
  </tr>
  <tr>
    <th rowspan="2">macOS</th>
    <td>--use-mkldnn-mac</td>
    <td>MKLDNN</td>
    <td>MPS</td>
    <td></td>
  </tr>
  <tr>
    <td>w/o --use-mkldnn-mac</td>
    <td>BNNS</td>
    <td>MPS</td>
    <td></td>
  </tr>
</table>

**Comment by huningxin** [comment]
@BruceDai , looks good. Please post the table in a wiki page. It is part of our documentations.

**Comment by BruceDai** [comment]
@huningxin Yes, we have already documented https://github.com/intel/webml-polyfill/wiki/Proposed-Chromium-Switches-for-Backends, please take a review, thanks.

**Comment by huningxin** [comment]
@BruceDai , thanks. It looks good.
