### ISSUE TITLE
[Linux] nightly build failed

### ISSUE THREAD

**Issue by miaobin** [intel/webml-polyfill#745]
Nightly build failed on https://github.com/otcshare/chromium-src/commit/22d23107c0d4306c65aa221c00f5cc7bb8b88c42
```
CXX obj/services/ml/ie/execution_impl_ie.o
FAILED: obj/services/ml/ie/execution_impl_ie.o

...

../../services/ml/common.h:12:10: fatal error: 'services/ml/public/mojom/constants.mojom.h' file not found
#include "services/ml/public/mojom/constants.mojom.h"
```

**Comment by huningxin** [comment]
I cannot reproduce on my dev machine. @fujunwei , could you please help investigate it? Thanks!

**Comment by huningxin** [comment]
Reproduce with a fresh build. Thanks @fujunwei 's help. Fixed and please verify.

**Comment by miaobin** [comment]
Nightly build successfully on https://github.com/otcshare/chromium-src/commit/b8348e878bb7a8295a6072fcc3943fcf594bf211 @huningxin
