### ISSUE TITLE
[wasm] Return type of some Model methods is not consistent between API doc and implementation

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#75]
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision f9e1a31)
OS : Mac OS X 10.13.4

**Expected Result:**
The returned type of Model methods is 'void' type

**Actual Result:**
The returned type of Model methods is not 'void' type, it returns 0

**How to reproduce:**
1.Download and install Chromium
2.Launch Chromium
3.Run test case on Chromium: https://brucedai.github.io/nt/test/index-local.html?backend=webgl2
4.Check the result for this test in addOperand API/setOperandValue API/addOperation API/identifyInputsAndOutputs API
for example:

```
    it('check return value is of "void" type', function() {
      return nn.createModel(options).then((model)=>{
        assert.equal(model.addOperand({type: nn.INT32}), undefined);
      });
    });
```
```
    it('check return value is of "void" type', function() {
      return nn.createModel(options).then((model)=>{
        model.addOperand({type: nn.INT32});
        assert.equal(model.setOperandValue(0, new Int32Array([0])), undefined);
      });
    });
```

**Comment by BruceDai** [comment]
The root cause is that the functions addOperand API/setOperandValue API/addOperation API/identifyInputsAndOutputs in src/nn/Model.js return their values.

**Comment by ibelem** [comment]
API doc

```
interface Model {
  void addOperand(OperandOptions options);
  void setOperandValue(unsigned long index, ArrayBufferView data);
  void addOperation(long type, sequence<unsigned long> inputs, sequence<unsigned long> outputs);
  void identifyInputsAndOutputs(sequence<unsigned long> inputs, sequence<unsigned long> outputs);
};
```
webml-polyfill/src/nn/Model.js

```
addOperation(type, inputs, outputs) {
 ...
  return ResultCode.NO_ERROR;
 }
```

**Comment by Christywl** [comment]
This issue was fixed with https://github.com/intel/webml-polyfill/commit/5b85adea5d575b6180c469170e6ff76a862f8678 on nightly build 8e6c6d1.
