### ISSUE TITLE
[Tool] CircleCI fail, cause chrome version not match chromedriver

### ISSUE THREAD

**Issue by zhaoming0** [intel/webml-polyfill#778]
#756 Chrome version must be between 71 and 75.

Some parameter for circleCI image
https://circleci.com/docs/2.0/docker-image-tags.json

@BruceDai @ibelem

**Comment by zhaoming0** [comment]
BTW get error when  `npm install ` on master branch

error info

```
npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ecstatic@^2.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'http-server'
npm ERR! notarget 
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2019-05-03T06_13_46_281Z-debug.log
Command exited with code 1
```

It seems that the dependency of `http-server` is the cause. I didn't find out where it is useful.
It is not caused by this PR :smile: 
When I remove `http-server` from the `package.json`, it will be normal

I hope that will help you @BruceDai :handshake:

**Comment by ibelem** [comment]
@zhaoming0 Thanks a lot for helping on the CI issue!

**Comment by BruceDai** [comment]
Thanks @zhaoming0 
Regard to PR#779, I don't think it's good to use latest docker image for chromedriver of "2.46.0", we will keep on upgrade this docker image manually, so I will close your PR and submit another PR to fix issue.
