### ISSUE TITLE
[WebGL][Example] DeepLab(without Atrous) does not work when tfjs-core is upgraded to 1.2.0

### ISSUE THREAD

**Issue by liyananxl** [intel/webml-polyfill#821]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (34a8a0d)
Platform: Android
Device: Google Pixel 3

**Expected Result:**
The DeepLab(without Atrous) should work fine.

**Actual Result:**
DeepLab 224/257/321/513 examples do not work on commit https://github.com/intel/webml-polyfill/commit/1d60d59081f48126424df42ef4cba57955594d69 (tfjs-core is upgraded to 1.2.0).
Note: These examples work fine on commit https://github.com/intel/webml-polyfill/commit/ddf5344b933632e2a6aaf72d7f81979228b2db4f (tfjs-core is 0.15.4)
Issue1:
![deeplab](https://user-images.githubusercontent.com/44693101/58397803-2d44cc80-8085-11e9-946f-9b89f9a03aea.png)

Issue2:
![error](https://user-images.githubusercontent.com/44693101/58399366-8a8f4c80-808a-11e9-9bcd-6c4a1bc43dff.png)

**How to Reproduce:**

1. Setup test server and start
2. Visit http://localhost:8080/examples/semantic_segmentation/
3. Select WebGL
4. Select Deeplab 224/257/321/513

**Comment by liyananxl** [comment]
Run on Google Pixel 2XL:
Only DeepLab 513 example does not work on commit https://github.com/intel/webml-polyfill/commit/1d60d59081f48126424df42ef4cba57955594d69 (tfjs-core is upgraded to 1.2.0).
It also works fine on commit https://github.com/intel/webml-polyfill/commit/ddf5344b933632e2a6aaf72d7f81979228b2db4f (tfjs-core is 0.15.4)

![Pixel 2 xl error](https://user-images.githubusercontent.com/44693101/58402612-5e2bfe00-8093-11e9-9b2e-cff9fb38662a.png)

**Comment by ibelem** [comment]
tfjs solved this issue, just wait for tfjs-core 1.2.2.

**Comment by liyananxl** [comment]
This issue was fixed on webml-polyfill commit https://github.com/intel/webml-polyfill/commit/83d9d19358a7728bee99c256eab11ebc675d2210 (tfjs-core version: 1.2.2).
