### ISSUE TITLE
[WebGL][Benchmark] DeepLab(without Atrous) performance with tfjs-core 1.2.0 is worse than tfjs-core 0.15.4

### ISSUE THREAD

**Issue by liyananxl** [intel/webml-polyfill#849]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (1a2331d)
Platform: Linux/Windows/macOS

**Expected Result:**
The DeepLab(without Atrous) performance should be improved.

**Actual Result:**
DeepLab(without Atrous) performance with tfjs-core 1.2.0 is worse than tfjs-core 0.15.4
For example:

macOS | 0.15.4 | 1.2.0
-- | -- | --
DeepLab 224 | 85.59+-6.11 | 175.76+-41.38
DeepLab 257 | 119.99+-6.16 | 220.71+-17.94
DeepLab 321 | 174.45+-6.59 | 324.15+-24.93
DeepLab 513 | 404.83+-8.06 | 780.75+-55.63

Linux | 0.15.4 | 1.2.0
-- | -- | --
DeepLab 224 | 160.53+-4.45 | 245.90+-19.26
DeepLab 257 | 258.36+-10.88 | 358.17+-48.47
DeepLab 321 | 393.31+-37.38 | 525.90+-40.07
DeepLab 513 | 931.90+-25.44 | 1350.50+-113.88

Windows | 0.15.4 | 1.2.0
-- | -- | --
DeepLab 224 | 139.59+-12.51 | 159.85+-15.96
DeepLab 257 | 194.11+-11.36 | 217.77+-20.83
DeepLab 321 | 282.84+-13.06 | 329.81+-28.27
DeepLab 513 | 681.32+-15.97 | 1117.17+-88.00

**How to Reproduce:**

1. Setup test server and start
2. Visit http://localhost:8080/benchmark
3. Select Deeplab 224/257/321/513
4. Select WebGL

**Comment by ibelem** [comment]
tfjs solved this issue, just wait for tfjs-core 1.2.2.

**Comment by liyananxl** [comment]
This issue was fixed on webml-polyfill commit https://github.com/intel/webml-polyfill/commit/83d9d19358a7728bee99c256eab11ebc675d2210 (tfjs-core version: 1.2.2).


macOS | 0.15.4 | 1.2.0 | 1.2.2
-- | -- | -- | --
DeepLab 224 | 85.59+-6.11 | 175.76+-41.38 | 73.91+-7.85
DeepLab 257 | 119.99+-6.16 | 220.71+-17.94 | 97.82+-9.57
DeepLab 321 | 174.45+-6.59 | 324.15+-24.93 | 139.94+-11.97
DeepLab 513 | 404.83+-8.06 | 780.75+-55.63 | 338.64+-25.81


Linux | 0.15.4 | 1.2.0 | 1.2.2
-- | -- | -- | --
DeepLab 224 | 160.53+-4.45 | 245.90+-19.26 | 126.15+-11.02
DeepLab 257 | 258.36+-10.88 | 358.17+-48.47 | 174.49+-13.46
DeepLab 321 | 393.31+-37.38 | 525.90+-40.07 | 264.41+-20.27
DeepLab 513 | 931.90+-25.44 | 1350.50+-113.88 | 696.09+-63.42


Windows | 0.15.4 | 1.2.0 | 1.2.2
-- | -- | -- | --
DeepLab 224 | 139.59+-12.51 | 159.85+-15.96 | 115.35+-15.20
DeepLab 257 | 194.11+-11.36 | 217.77+-20.83 | 159.98+-20.11
DeepLab 321 | 282.84+-13.06 | 329.81+-28.27 | 243.09+-26.59
DeepLab 513 | 681.32+-15.97 | 1117.17+-88.00 | 612.68+-53.28
