### ISSUE TITLE
[Examples] UI Enhancement

### ISSUE THREAD

**Issue by kenny-yuan** [intel/webml-polyfill#870]
When showing demo to various audience, I've found the following defects:

 - The current status is just one label, user can't see the progress and have no idea of the whole progress (num of steps, purpose of each steps, etc.). Since some of the steps are just in a jiffy, users can only see the longest step and it feels confusing.

Suggestion: use something like below (text mock-up)
```
| ------------ Preparation Stage --------------- | ---------------- Inference Stage ----------- |
Updating backend (X) ----> Loading Model (X)----> <b>Doing inference (<Blinking>) </b> ----> Done
```
Note: the checkmarks can be Chinese style

- The touch area of Model / Backend selection is kind of small, and it's not so obvious in UI

Suggestion: increase it to be >= 1.x cm (average finger tip width), make it more like a button with selection state.

- User have to switch among different backend and run them multiple times to remember the performance data to do the comparison by heart

Suggestion: show recent performance stat of inference as history info (or maybe even simple bar chart), no need to run different models over and over again to compare the performance difference

**Comment by ibelem** [comment]
@kenny-yuan thanks for the great suggestions, i will improve them. :)
