### ISSUE TITLE
[webml/NNAPI] Crash happened when attempting to do extra actions for the finished model

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#89]
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision f9e1a31)
OS : Android 8.1.0;Pixel 2

**Expected Result:**
No crash happens

**Actual Result:**
Crash happened when attempting to do extra actions for the finished model

**How to reproduce:**

 Run test case on Chromium: https://brucedai.github.io/nt/testa/index-local.html

**Test Cases:**

1. raise error when attempting to add an operand into the finished model: https://github.com/intel/webml-polyfill/blob/master/test/unit-test/test-Model.js#L204
2. raise error when attempting to reset the value for an operand of the finished model: https://github.com/intel/webml-polyfill/blob/master/test/unit-test/test-Model.js#L903
3. raise error when attempting to reset the operation of the finished model:https://github.com/intel/webml-polyfill/blob/master/test/unit-test/test-Model.js#L3246
4. raise error when attempting to modify inputs/outputs of the finished model: https://github.com/intel/webml-polyfill/blob/master/test/unit-test/test-Model.js#L3347

**Comment by sunlin-link** [comment]
@BruceDai Please help to verify the fix.

**Comment by Christywl** [comment]
Verified it with Chromium nightly build(007f215), this issue can't reproduce, so close it.

**Comment by Christywl** [comment]
Reopen this issue since this issue occurs again on the Chromium nightly build [279911e](http://powerbuilder.sh.intel.com/public/webml/nightly/279911e/) [1fd54ed](http://powerbuilder.sh.intel.com/public/webml/nightly/1fd54ed/).
Test URL: https://brucedai.github.io/nt/test/model.html?backend=nnapi

**Comment by sunlin-link** [comment]
regression by https://github.com/otcshare/chromium-src/pull/20

**Comment by sunlin-link** [comment]
@Christywl Fixed. Please verify

**Comment by Christywl** [comment]
Verified it with the chromium nightly build 3677b5f, this issue wasn't reproduced.
