### ISSUE TITLE
[MPS] ADD is not supported for MPS

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#92]
`ADD` operation is not supported for MPS:
https://github.com/intel/webml-polyfill/blob/master/docs/supported_ops.md

Op Type |  MPS
-- | -- 
ADD | no 
MUL | no

**Comment by huningxin** [comment]
Split the `MUL` into #117

**Comment by huningxin** [comment]
After review the `ADD` related test cases:
https://github.com/intel/webml-polyfill/blob/master/test/operations/add.js
https://github.com/intel/webml-polyfill/blob/master/test/cts/test/V1_0/add.js

and the examples:
https://github.com/intel/webml-polyfill/tree/master/examples/simple (also requires `MUL` op support)
https://github.com/intel/webml-polyfill/tree/master/examples/mobilenet (by using the MobileNet v2 model)

The TODOs include:
1. need to support tensor with dimension 1 (tests)
2. need to support uploading multiple model inputs to MPS images (simple example)
3. need to support uploading constants of `ADD` op to MPS images (tests)
4. create `MPSCNNAdd` instance when compile the model (all)
5. link the inputs and output of op when execute the model (all)

This would also setup a base to add `MUL` which only requires to change step 4 to `MPSCNNMultiply `

**Comment by huningxin** [comment]
Fixed. @BruceDai , please verify. Thanks!

**Comment by Christywl** [comment]
Verified on nightly build **b7ce158**, the tests passed.
https://brucedai.github.io/nt/test/add.html?backend=mps
