### ISSUE TITLE
[example] Implement Face Recognition example

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#928]

**Comment by cuiyanx** [comment]
I try to add face recognition use case using [facenet](https://github.com/davidsandberg/facenet). When I try to convert this model [InceptionResNetv1.pb](https://drive.google.com/open?id=1R77HmFADxe87GmoLwzfgMu_HY0IhcyBz) to .tflite file, I found that there are several ops that have not supported yet: Merge, Switch. This is tensorflow issue [Control flow is missing](https://github.com/tensorflow/community/pull/83).

**Comment by cuiyanx** [comment]
I try to add face recognition use case using [ArcFace](https://github.com/onnx/models/tree/master/vision/body_analysis/arcface) that is ONNX model. And I optimiz this model with following code base on [Optimizer.md](https://github.com/onnx/onnx/blob/master/docs/Optimizer.md):

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import onnx
import os
from onnx import optimizer

model_path = os.path.join('20180402-114759', 'resnet100.onnx')
original_model = onnx.load(model_path)

all_passes = optimizer.get_available_passes()
print("Available optimization passes:")
for p in all_passes:
    print('\t{}'.format(p))
print()

passes = ['eliminate_identity', 'eliminate_nop_pad', 'fuse_matmul_add_bias_into_gemm', 'fuse_pad_into_conv']
onnx_optimized = 'resnet100_optimized.onnx'
optimized_model = optimizer.optimize(original_model, passes)
onnx.save(optimized_model, onnx_optimized)

**Comment by cuiyanx** [comment]
I build [ArcFace](https://github.com/onnx/models/tree/master/vision/body_analysis/arcface) model with MacOS platform and workaround [Arcface_inference #158](https://github.com/onnx/models/issues/158). And build this model into Webml-polyfill. I implement **PRelu** op in [/src/nn/webgl/WebGLModel.js](https://github.com/intel/webml-polyfill/blob/master/src/nn/webgl/WebGLModel.js). But when I input the same image data, I got the different output data. I will locate and fix this problem on [my working repo](https://github.com/cuiyanx/webml-polyfill/tree/add-face-recognition-example).

**Comment by cuiyanx** [comment]
The episilon of Webml-polyfill is e-7 in [/test/utils.js](https://github.com/intel/webml-polyfill/blob/master/test/utils.js) and the episilon of ONNX model is e-39. Webml-polyfill read too small data like **-1.95620144580973e-39** as **0**. So, I got different output data.

Src data:
![Screenshot from 2019-08-27 14-44-48](https://user-images.githubusercontent.com/22387607/63748383-d21cb300-c8db-11e9-9a20-1908b788c234.png)

Read data:
![Screenshot from 2019-08-27 14-44-21](https://user-images.githubusercontent.com/22387607/63748409-e06acf00-c8db-11e9-9e79-fc0b901bf7c3.png)

**Comment by cuiyanx** [comment]
I download and convert [**FaceNet**](https://drive.google.com/open?id=1R77HmFADxe87GmoLwzfgMu_HY0IhcyBz) to **OpenVino** model, and implement Int32 data type, and support '**Permute, Normalize**' ops, and fix none-value bug for '**FullyConnected** 'op. The URL of face recognition demo is https://github.com/cuiyanx/webml-polyfill/tree/add-face-recognition-example-with-facenet-openvino/examples/face_recognition/model.

**Comment by cuiyanx** [comment]
I download and convert [sphereface](https://github.com/wy1iu/sphereface) model, and build into webml-polyfill, and I implement **PRelu** op. I got the same problem as [arcface](https://github.com/onnx/models/tree/master/vision/body_analysis/arcface). That problem is not distinguish facial features very well. 
Checked in my repo:
https://github.com/cuiyanx/webml-polyfill/tree/add-face-recognition-use-case-with-sphereface-model

Src data:
![Screenshot from 2019-09-09 09-52-33](https://user-images.githubusercontent.com/22387607/64498567-a4763780-d2e7-11e9-8095-bd3ccbd377fc.png)

Read data:
![Screenshot from 2019-09-09 09-52-58](https://user-images.githubusercontent.com/22387607/64498573-ad670900-d2e7-11e9-8c4b-c697fcd46aee.png)

**Comment by cuiyanx** [comment]
I build [face-reidentification](https://github.com/opencv/open_model_zoo/blob/master/intel_models/face-reidentification-retail-0095/description/face-reidentification-retail-0095.md) OpenVino model for face recognition example, and implement **PRelu**  and **Activation**(sigmoid) ops. I also complete supporting multiple models for Example UI.
 The URL of face recognition demo is https://github.com/cuiyanx/webml-polyfill/tree/add-face-recognition-use-case-with-face-reidentification-model
