### ISSUE TITLE
[MPS] All the examples don't work on macOS Catalina 10.15 beta

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#930]
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (79fdab0)
Platform: macOS

**Expected Result:**
The examples should work on macOS 10.15 beta.

**Actual Result:**
All the examples don't work on macOS Catalina 10.15 beta:
<img width="1280" alt="Screen Shot 2019-08-13 at 2 34 53 PM" src="https://user-images.githubusercontent.com/20039821/62920180-8a743280-bdd7-11e9-8340-f918f2c4e22f.png">

**How to Reproduce:**
1. Launch chromium and visit https://intel.github.io/webml-polyfill/examples/
2. Select one example(e.g. Image Classification)
2. Select SUSTAINED_SPEED and one model

**Comment by fujunwei** [comment]
[The native example](https://github.com/fujunwei/MPSNNGraph/tree/simple/MPSNNGraphSample)  can work as expected, so the root cause of it is to add "--no-sandbox" option.

**Comment by ibelem** [comment]
Still need to explain why "--no-sandbox" is needed on 10.15 since 10.14 doesn't need it. Both our stakeholder and I asked this question.

**Comment by Christywl** [comment]
The new build https://github.com/otcshare/chromium-src/commit/235e045f23e78e8871690c8af32fadbda2ed9964 (without `--no-sandbox`) works fine on both macOS 10.14 and 10.15 beta.
