### ISSUE TITLE
[NNAPI] Crash happened when setting the 'index' value is equal or greater than the size of inputs/ouputs

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#94]
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision f9e1a31)
OS : Android 8.1.0;Pixel 2

**Expected Result:**
No crash happens

**Actual Result:**
Crash happened when setting the 'index' value is equal or greater than the size of inputs/ouputs

**How to reproduce:**
1. Launch chromium and enable WebML flag
2. Run test case on Chromium: 
a. https://brucedai.github.io/nt/test/setinput_neg.html 
b. https://brucedai.github.io/nt/test/setoutput_neg.html
c. https://brucedai.github.io/nt/test/execution.html

_Run the test with single mode(a or b), sometimes it passed, sometimes it crashed.
Run it with other Execution tests(c), it always crashed._

**Test Cases:**
1. raise error when the value being set to \'index\' is equal or greater than the size of inputs:
https://github.com/intel/webml-polyfill/blob/master/test/unit-test/test-Execution.js#L69
2. raise error when the value being set to \'index\' is equal or greater than the size of output
https://github.com/intel/webml-polyfill/blob/master/test/unit-test/test-Execution.js#L358

[execution_crash.log](https://github.com/intel/webml-polyfill/files/2256110/execution_crash.log)

**Comment by Christywl** [comment]
Reopen this issue because chromium crashed sometimes.
Updated the description above and added the crash log in the issue.

**Comment by sunlin-link** [comment]
@BruceDai This bug should be fixed by previous commits. Please verify with latest build again.

**Comment by Christywl** [comment]
I checked it with the Chromium nightly build(8fcce67), this issue wasn't reproduced, so close it.
