### ISSUE TITLE
[DML] Support ARGMAX op

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#943]

**Comment by fujunwei** [comment]
The inference time for deeplab v3 atrous models:

| model | model inference time | post-processing time | total |
|----------|----------------|------------|-----------|
| 224 OS 8 without argmax | 43ms | 13ms | 56ms |
| 224 OS 8 with argmax | 37ms | 2 ms | 39ms |

For 224 OS 8 model, the argmax op can give 1.43X speedup.

**Comment by fujunwei** [comment]
Done with https://github.com/otcshare/chromium-src/pull/3

**Comment by Christywl** [comment]
ARGMAX op works on DML backend with https://github.com/otcshare/chromium-src/commit/4e4a1a3c08ac0dc84d9d313c50f14e56c82dca8c.
