### ISSUE TITLE
[clDNN] Support ARGMAX op

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#945]

**Comment by ibelem** [comment]
@lisa0314 @Christywl @lisa0314 Based on Friday's sharing, we need to prioritize this issue.

> ARGMAX – Implement ops on clDNN to verify the performance improvement gains at first

**Comment by huningxin** [comment]
As mentioned in https://github.com/intel/webml-polyfill/issues/968#issuecomment-541290709, `arg_max_min` is supported in clDNN we currently use:
https://github.com/otcshare/chromium-src/blob/webml/third_party/clDNN/api/C/arg_max_min.h

We can map argmax to it without upgrading clDNN.

**Comment by huningxin** [comment]
Synced with @lisa0314 , I am going to implement the argmax on current clDNN and Lisa will keep investigating upgrade clDNN of dldt.

**Comment by huningxin** [comment]
Update:
1. Prototyped with https://github.com/intel/clDNN, but its argmax performance is not optimal.
2. https://github.com/opencv/dldt/tree/2019/inference-engine/thirdparty/clDNN doesn't support C API anymore. We cannot use it directly.

**Comment by huningxin** [comment]
Update:

I ported the optimized argmax cl kernel from dldt repo. With that kernel, I collected the inference time for deeplab v3 models on my dev machine:

| model | model inference time | post-processing time | total |
|----------|----------------|------------|-----------|
| 513 OS 16 without argmax | 81 ms | 18 ms | 99 ms |
| 513 OS 16 with argmax | 52 ms | 2 ms | 54 ms |
| 513 OS 8 without argmax | 150 ms | 18 ms | 168 ms |
| 513 OS 8 with argmax | 125 ms | 2 ms | 127 ms |

For 513 OS 16 model, the argmax op can give 1.83X speedup. For 513 OS 8 model, the argmax op can give 1.32X speedup. This result aligns to @pinzhenx 's [investigation ](https://github.com/intel/webml-polyfill/issues/395#issuecomment-493335554).

I am going to put together a PR for clDNN implementation.

**Comment by Christywl** [comment]
ARGMAX op works on clDNN with https://github.com/otcshare/chromium-src/commit/dcbd4abd891e918adf5d66b536ac1ba27b34c06e.
