### ISSUE TITLE
[MPS] Support ARGMAX op

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#949]

**Comment by fujunwei** [comment]
The inference time for deeplab v3 atrous models:

| model | model inference time | post-processing time | total |
|----------|----------------|------------|-----------|
| 224 OS 8 without argmax | 45ms | 34ms | 78ms |
| 224 OS 8 with argmax | 40ms | 11 ms | 51ms |

For 224 OS 8 model, the argmax op can give 1.6X speedup.

**Comment by fujunwei** [comment]
Done with https://github.com/otcshare/chromium-src/pull/5

**Comment by Christywl** [comment]
ARGMAX can work on macOS 10.15. But it doesn't work on macOS 10.14(see #1087). And there is one common issue on both macOS 10.14 and 10.15(see #1086).
