### ISSUE TITLE
[Doc] Add DirectML column into native mapping spreadsheet

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#967]
Please add DirectML column into https://docs.google.com/spreadsheets/d/1nthZOwgIKsj34EB-SymEwoNTPsxo4X8Pxavm-JaBwME/edit?usp=sharing

**Comment by fujunwei** [comment]
Update in https://docs.google.com/spreadsheets/d/1i3ckDLZVB7JRJCFwq4nC4IGQ_Hk4Qt3RMvQxJOejvc0/edit?usp=sharing, PTAL thanks.

**Comment by huningxin** [comment]
thanks, merged.
