### ISSUE TITLE
Propose to support ArgMax op for Deeplap model of Semantic Segmentation example

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#968]
Deeplab model has ArgMax as the last node in the graph.
![lutzroeder github io_netron_ 1](https://user-images.githubusercontent.com/7313938/50433868-caa0a680-0915-11e9-83c6-9362b7e7f37e.png)

While current we don't support ArgMax op, so we do JavaScript workaround to implement ArgMax on handling the output tensor of dimensions [1, 513, 513, 21] of the last ResizeBilinear node to get target tensor of dimensions [1, 513, 513, 1].
 
Here is the Extra Time of JavaScript workaround comparing with enabling ArgMax op by tfjs-core

Platform | Extra Time (ms)
-- | --
Windows | ~20
Android - Pixel 3| ~50

The performance data with enabling ArgMax on WASM and WebGL backend by desktop of i7-6700K, HD530

Model | WASM (ms) | WebGL (ms)
-- | -- | -- 
deeplab os8 513 dilated w/o ArgMax | 3979.48+-282.84 | 383.23+-29.31
deeplab os8 513 dilated with ArgMax | 3900.43+-19.69 | 362.68+-17.41
 
As to argmax computing, NNAPI has ANEURALNETWORKS_ARGMAX, while ONNX has ArgMax. 
From [tensorflow/lite/kernels/internal/reference/reference_ops.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/reference_ops.h), the ArgMax is enabled, while ArgMin isn't supported.

**Comment by BruceDai** [comment]
@huningxin @fujunwei @mingmingtasd PTAL, thanks

**Comment by BruceDai** [comment]
I couldn't find argmax related description from [clDNN Primitives](https://intel.github.io/clDNN/group__c__primitives.html) which aren't maintained from Jan 9, 2018, while there's a declaration in [opencv/dldt/blob/2019_R2/inference-engine/thirdparty/clDNN/api/C/arg_max_min.h ](https://github.com/opencv/dldt/blob/2019_R2/inference-engine/thirdparty/clDNN/api/C/arg_max_min.h)

**Comment by BruceDai** [comment]
From [mkl-dnn primitives](https://github.com/intel/mkl-dnn/tree/master/doc/primitives), MKLDNN doesn't provide argmax primitive.

**Comment by BruceDai** [comment]
@fujunwei please help investigate argmax for DML, MPS 
@lisa0314 please help investigate argmax for BNNS
Thanks

**Comment by ibelem** [comment]
1. Upgrade clDNN to r3+ version
2. Add Argmax support

**Comment by BruceDai** [comment]
Detail | NNAPI | ONNX | clDNN | MKLDNN | DML | MPS | BNNS
-- | -- | -- | -- | -- | -- | -- | --
op | [ANEURALNETWORKS_ARGMAX](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0af78048ff71a1e79bbc6034d30cad7cbc) | [ArgMax](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ArgMax) |   |   |   |   |  
input | input[0]:        Supported tensor rank: from 1.     An n-D tensor specifying the input. Must be non-empty. | inputs[“data”]: An   input tensor. |   |   |   |   |  
axis | input[1]:        An ANEURALNETWORKS_INT32 scalar specifying the axis to reduce across.   Negative index is used to specify axis from the end (e.g. -1 for the last   axis).      Must be in the range [-n, n). | Attributes["axis"]: int (default is 0)     The axis in which to compute the arg indices. |   |   |   |   |  
  |   | Attributes["keepdims"]   : int (default is 1)     Keep the reduced dimension or not, default 1 mean keep reduced dimension. |   |   |   |   |  
output | output[0]:        An (n - 1)-D ANEURALNETWORKS_TENSOR_INT32 tensor. | outputs["reduced   "]: tensor(int64)     Reduced output tensor with integer data type.          The resulted tensor has the same rank as the input if   keepdims equal 1.      If keepdims equal 0, then the resulted tensor have the reduced dimension   pruned. |   |   |   |   |

**Comment by BruceDai** [comment]
@lisa0314 @fujunwei Please help fill in above table, thanks

**Comment by huningxin** [comment]
> I couldn't find argmax related description from [clDNN Primitives](https://intel.github.io/clDNN/group__c__primitives.html) which aren't maintained from Jan 9, 2018,

`arg_max_min` is supported in clDNN we currently use:
https://github.com/otcshare/chromium-src/blob/webml/third_party/clDNN/api/C/arg_max_min.h

Updated the clDNN column in above table.

**Comment by fujunwei** [comment]
There is no existing operation to support argmax in DML and MPS, maybe Shading language is a optional.

**Comment by huningxin** [comment]
Updated the DML column with `DML_REDUCE_OPERATOR_DESC` and `DML_REDUCE_FUNCTION_ARGMAX`.

**Comment by huningxin** [comment]
For MPS, do MPSNNReduction functions meet the requirement, e.g. [`MPSNNReductionFeatureChannelsMaxNode`](https://developer.apple.com/documentation/metalperformanceshaders/mpsnnreductionfeaturechannelsmaxnode)? @fujunwei

**Comment by fujunwei** [comment]
Yes, [MPSNNReductionFeatureChannelsArgumentMaxNode](https://developer.apple.com/documentation/metalperformanceshaders/mpsnnreductionfeaturechannelsargumentmaxnode) can return the argument index that is the location of the maximum value for feature channels of image,  the DeepLab also reduce across axis = 3.

**Comment by BruceDai** [comment]
We decided to support this ARGMAX OP, close this issue.
