### ISSUE TITLE
[MPS] DeepLab 224 Atrous works normally from the build e633308

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#998]
**Test Env:**
Chromium Version: nightly build https://github.com/otcshare/chromium-src/commit/e633308a77a1c98db6362e41a95a883a99715d5d (75.0.3739.0), https://github.com/otcshare/chromium/commit/e7b9a67db6608d4358141193994194705dc95b0d (79.0.3917.0)
Platform: macOS 10.14.5

**Expected Result:**
The examples should work.

**Actual Result:**
This issue happened from https://github.com/otcshare/chromium-src/commit/e633308a77a1c98db6362e41a95a883a99715d5d (75.0.3739.0).

<img width="1440" alt="Screen Shot 2019-09-29 at 10 48 22 AM" src="https://user-images.githubusercontent.com/20039821/65825197-d0f9ef80-e2a6-11e9-9cf5-a57f9954c65a.png">

On the build https://github.com/otcshare/chromium-src/commit/235e045f23e78e8871690c8af32fadbda2ed9964, it works fine.
<img width="1440" alt="Screen Shot 2019-09-29 at 10 48 55 AM" src="https://user-images.githubusercontent.com/20039821/65825200-d7886700-e2a6-11e9-9f8c-1de082829180.png">

**How to Reproduce:**

1. Launch Chromium and visit https://intel.github.io/webml-polyfill/examples/semantic_segmentation
2. Select SUSTAINED_SPEED
3. Select Deeplab 224 Atrous

**Comment by Christywl** [comment]
@lisa0314 , this issue happened from https://github.com/otcshare/chromium-src/commit/e633308a77a1c98db6362e41a95a883a99715d5d, could you please help check it?

**Comment by fujunwei** [comment]
@lisa0314 do you fouce on checking this regressed issue?
